In [1]:
#csv파일이랑 audio폴더 test 양만큼 개줄여서 디버그하며 할 것

import os
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import pandas as pd
import csv

import scipy
from scipy.stats import skew
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.svm import SVC

In [2]:
filename = np.array(pd.read_csv('data/SC_file_name.csv'))
answer = np.array(pd.read_csv('data/SC_answer.csv'))

audio_train_files = os.listdir('./audio_train/')
audio_test_files = os.listdir('./audio_test/')
train=pd.read_csv('./file_name.csv')

In [3]:
#print(audio_train_files)
#print(audio_test_files)

In [4]:
def get_mfcc(name, path):
    data, _ = librosa.core.load(path+name) #엑셀에 .wav까지 붙여 저장해야됨 안그러면 path+name+'.wav' 이렇게해야
    print(data,_)
    #data, _ = librosa.load(path)
    try:
        #ft1 = librosa.feature.mfcc(data, sr = SAMPLE_RATE, n_mfcc=30)
        ft1 = librosa.feature.mfcc(data, n_mfcc=30) #이게핵심 Sample_rate를 어떻게 조절하느냐
        ft2 = librosa.feature.zero_crossing_rate(data)[0] # n_mfcc 값을 어떻게 조절하느냐에 따라 Feature개수가 달리 뽑힘
        ft3 = librosa.feature.spectral_rolloff(data)[0]
        ft4 = librosa.feature.spectral_centroid(data)[0]
        ft5 = librosa.feature.spectral_contrast(data)[0]
        ft6 = librosa.feature.spectral_bandwidth(data)[0]
        ft1_trunc = np.hstack((np.mean(ft1, axis=1), np.std(ft1, axis=1), skew(ft1, axis = 1), np.max(ft1, axis = 1), np.median(ft1, axis = 1), np.min(ft1, axis = 1)))
        ft2_trunc = np.hstack((np.mean(ft2), np.std(ft2), skew(ft2), np.max(ft2), np.median(ft2), np.min(ft2)))
        ft3_trunc = np.hstack((np.mean(ft3), np.std(ft3), skew(ft3), np.max(ft3), np.median(ft3), np.min(ft3)))
        ft4_trunc = np.hstack((np.mean(ft4), np.std(ft4), skew(ft4), np.max(ft4), np.median(ft4), np.min(ft4)))
        ft5_trunc = np.hstack((np.mean(ft5), np.std(ft5), skew(ft5), np.max(ft5), np.median(ft5), np.min(ft5)))
        ft6_trunc = np.hstack((np.mean(ft6), np.std(ft6), skew(ft6), np.max(ft6), np.median(ft6), np.max(ft6)))
        return pd.Series(np.hstack((ft1_trunc, ft2_trunc, ft3_trunc, ft4_trunc, ft5_trunc, ft6_trunc)))
    except:
        print('bad file')
        return pd.Series([0]*210)

In [5]:
train_data = pd.DataFrame()
train_data['fname'] = train['fname']
test_data=pd.DataFrame()
test_data['fname']=audio_test_files

In [6]:
#print(train_data)
#print(test_data)


In [7]:
train_data=train_data['fname'].progress_apply(get_mfcc,path='./audio_train/')
print('done loading train mfcc')
test_data = test_data['fname'].progress_apply(get_mfcc, path='./audio_test/')
print('done loading test mfcc')



  0%|                                                                                           | 0/99 [00:00<?, ?it/s]

[0.06973912 0.10266001 0.09116188 ... 0.08305359 0.08018959 0.08612607] 22050


  2%|█▋                                                                                 | 2/99 [00:07<05:45,  3.57s/it]

[-0.02710845 -0.03993477 -0.03530764 ... -0.04230448 -0.0414599
 -0.04527015] 22050


  3%|██▌                                                                                | 3/99 [00:10<05:29,  3.43s/it]

[ 0.00283427  0.00423394  0.0036414  ... -0.01369482 -0.01395124
 -0.01601286] 22050


  4%|███▎                                                                               | 4/99 [00:13<05:26,  3.43s/it]

[-0.2545665  -0.37054616 -0.3232944  ... -0.05147256 -0.04832996
 -0.0513258 ] 22050


  5%|████▏                                                                              | 5/99 [00:16<05:18,  3.38s/it]

[ 3.1871754e-05  6.1540527e-06 -3.7155998e-05 ... -1.4125325e-02
 -8.7606525e-03  0.0000000e+00] 22050


  6%|█████                                                                              | 6/99 [00:18<04:32,  2.93s/it]

[ 0.00079253  0.00089992  0.00091092 ... -0.0049351  -0.00259066
  0.        ] 22050


  7%|█████▊                                                                             | 7/99 [00:21<04:18,  2.81s/it]

[ 3.0208554e-05  3.0756044e-05  2.5381032e-05 ... -1.8259089e-02
 -1.1751885e-02 -5.7575861e-03] 22050


  8%|██████▋                                                                            | 8/99 [00:23<03:52,  2.56s/it]

[-0.00064508 -0.00077814 -0.0008623  ... -0.01482992 -0.00782498
  0.        ] 22050


  9%|███████▌                                                                           | 9/99 [00:24<03:19,  2.22s/it]

[ 0.00110417  0.00130484  0.00140896 ... -0.01235658 -0.00798214
 -0.00392708] 22050


 10%|████████▎                                                                         | 10/99 [00:26<03:14,  2.19s/it]

[ 4.3292630e-07  3.4875336e-06  7.9502988e-06 ... -4.9829770e-02
 -2.8054921e-02  0.0000000e+00] 22050


 11%|█████████                                                                         | 11/99 [00:29<03:31,  2.40s/it]

[0.00072087 0.00177281 0.00336674 ... 0.03278232 0.03167795 0.0341762 ] 22050


 12%|█████████▉                                                                        | 12/99 [00:33<03:51,  2.66s/it]

[-0.00511142 -0.00661265 -0.00532051 ...  0.05818591  0.05825811
  0.06405238] 22050


 13%|██████████▊                                                                       | 13/99 [00:36<04:07,  2.88s/it]

[ 0.13884057  0.20461525  0.18165357 ... -0.07205642 -0.07238604
 -0.08182055] 22050


 14%|███████████▌                                                                      | 14/99 [00:39<04:18,  3.04s/it]

[ 0.          0.          0.         ... -0.03222465 -0.02863552
 -0.02814007] 22050


 15%|████████████▍                                                                     | 15/99 [00:43<04:22,  3.13s/it]

[0.         0.         0.         ... 0.81409144 0.7837968  0.8404915 ] 22050


 16%|█████████████▎                                                                    | 16/99 [00:46<04:25,  3.20s/it]

[0.         0.         0.         ... 0.2893713  0.28139624 0.3021213 ] 22050


 17%|██████████████                                                                    | 17/99 [00:49<04:08,  3.03s/it]

[ 0.          0.          0.         ... -0.15555128 -0.14919281
 -0.1552921 ] 22050


 18%|██████████████▉                                                                   | 18/99 [00:52<04:04,  3.02s/it]

[0.         0.         0.         ... 0.02468135 0.02214165 0.01943384] 22050


 19%|███████████████▋                                                                  | 19/99 [00:55<04:07,  3.09s/it]

[ 0.          0.          0.         ... -0.34570888 -0.34052533
 -0.37189066] 22050


 20%|████████████████▌                                                                 | 20/99 [00:57<03:46,  2.87s/it]

[ 0.          0.          0.         ... -0.36525172 -0.35147998
 -0.3764349 ] 22050


 21%|█████████████████▍                                                                | 21/99 [01:01<03:55,  3.01s/it]

[0.         0.         0.         ... 0.29563662 0.29204592 0.32384074] 22050


 22%|██████████████████▏                                                               | 22/99 [01:04<03:54,  3.04s/it]

[ 0.          0.          0.         ... -0.87329555 -0.8426997
 -0.904122  ] 22050


 23%|███████████████████                                                               | 23/99 [01:07<03:46,  2.98s/it]

[0.         0.         0.         ... 0.08035016 0.07610521 0.08158155] 22050


 24%|███████████████████▉                                                              | 24/99 [01:10<03:50,  3.08s/it]

[0.         0.         0.         ... 0.07361161 0.07532007 0.08183191] 22050


 25%|████████████████████▋                                                             | 25/99 [01:13<03:51,  3.13s/it]

[ 0.          0.          0.         ... -0.05342972 -0.0532412
 -0.06048   ] 22050


 26%|█████████████████████▌                                                            | 26/99 [01:16<03:42,  3.05s/it]

[0.         0.         0.         ... 0.48654523 0.47395992 0.5123876 ] 22050


 27%|██████████████████████▎                                                           | 27/99 [01:19<03:48,  3.17s/it]

[0.         0.         0.         ... 0.01937228 0.01565968 0.01233602] 22050


 28%|███████████████████████▏                                                          | 28/99 [01:23<03:49,  3.24s/it]

[0.         0.         0.         ... 0.21377535 0.19589575 0.19898888] 22050


 29%|████████████████████████                                                          | 29/99 [01:26<03:51,  3.31s/it]

[ 0.          0.          0.         ... -0.03692322 -0.04029846
 -0.03779646] 22050


 30%|████████████████████████▊                                                         | 30/99 [01:29<03:44,  3.25s/it]

[ 0.          0.          0.         ... -0.00111335  0.00120612
 -0.00136599] 22050


 31%|█████████████████████████▋                                                        | 31/99 [01:33<03:50,  3.39s/it]

[ 0.          0.          0.         ... -0.27843747 -0.2646894
 -0.28205138] 22050


 32%|██████████████████████████▌                                                       | 32/99 [01:37<03:51,  3.45s/it]

[ 0.          0.          0.         ... -0.26306844 -0.2522001
 -0.26922488] 22050


 33%|███████████████████████████▎                                                      | 33/99 [01:41<03:58,  3.61s/it]

[0.         0.         0.         ... 0.1735332  0.17125647 0.19119985] 22050


 34%|████████████████████████████▏                                                     | 34/99 [01:45<04:00,  3.70s/it]

[ 0.          0.          0.         ... -0.2167718  -0.2080332
 -0.22265384] 22050


 35%|████████████████████████████▉                                                     | 35/99 [01:48<03:50,  3.60s/it]

[ 0.          0.          0.         ... -0.05900886 -0.06246108
 -0.06871106] 22050


 36%|█████████████████████████████▊                                                    | 36/99 [01:52<03:45,  3.59s/it]

[0.         0.         0.         ... 0.7010785  0.68610245 0.7446819 ] 22050


 37%|██████████████████████████████▋                                                   | 37/99 [01:55<03:43,  3.60s/it]

[ 0.          0.          0.         ... -0.1005215  -0.09558512
 -0.09833872] 22050


 38%|███████████████████████████████▍                                                  | 38/99 [01:59<03:40,  3.61s/it]

[ 0.          0.          0.         ... -0.09970824 -0.10170659
 -0.11256789] 22050


 39%|████████████████████████████████▎                                                 | 39/99 [02:02<03:36,  3.61s/it]

[ 0.          0.          0.         ... -0.09393648 -0.0905112
 -0.09887574] 22050


 40%|█████████████████████████████████▏                                                | 40/99 [02:06<03:30,  3.56s/it]

[ 0.          0.          0.         ... -0.10736632 -0.10226438
 -0.10872729] 22050


 41%|█████████████████████████████████▉                                                | 41/99 [02:10<03:36,  3.73s/it]

[ 0.          0.          0.         ... -0.3698437  -0.36839765
 -0.4094729 ] 22050


 42%|██████████████████████████████████▊                                               | 42/99 [02:14<03:35,  3.78s/it]

[-0.00949201 -0.01515351 -0.01494985 ...  0.03122446  0.03000467
  0.03189378] 22050


 43%|███████████████████████████████████▌                                              | 43/99 [02:17<03:19,  3.55s/it]

[-1.7585522e-06 -2.2429733e-06 -1.9274846e-06 ... -1.1987473e-02
 -7.4312286e-03  0.0000000e+00] 22050


 44%|████████████████████████████████████▍                                             | 44/99 [02:19<02:49,  3.07s/it]

[-3.1364743e-05 -3.4258581e-05 -3.3931665e-05 ...  5.3538714e-04
  3.7836187e-04  0.0000000e+00] 22050


 45%|█████████████████████████████████████▎                                            | 45/99 [02:21<02:30,  2.79s/it]

[-2.9586021e-05 -3.3629472e-05 -3.4923316e-05 ... -2.4650006e-03
 -1.3031738e-03  0.0000000e+00] 22050


 46%|██████████████████████████████████████                                            | 46/99 [02:23<02:09,  2.44s/it]

[3.0384650e-05 3.1305051e-05 2.8012693e-05 ... 3.9614424e-02 2.4514157e-02
 0.0000000e+00] 22050


 47%|██████████████████████████████████████▉                                           | 47/99 [02:24<01:50,  2.13s/it]

[-0.00015414 -0.00019182 -0.00021949 ...  0.02211454  0.01247506
  0.        ] 22050


 48%|███████████████████████████████████████▊                                          | 48/99 [02:26<01:46,  2.08s/it]

[2.9788309e-05 3.2301657e-05 3.1995405e-05 ... 1.5126610e-03 9.7192550e-04
 4.7570144e-04] 22050


 49%|████████████████████████████████████████▌                                         | 49/99 [02:28<01:49,  2.20s/it]

[-0.30551556 -0.337594   -0.35426965 ...  0.04488467  0.02582479
  0.        ] 22050


 51%|█████████████████████████████████████████▍                                        | 50/99 [02:35<02:54,  3.56s/it]

[-0.30030748 -0.3313869  -0.3471481  ... -0.10257331 -0.06606323
 -0.03239066] 22050


 52%|██████████████████████████████████████████▏                                       | 51/99 [02:38<02:46,  3.46s/it]

[-0.5566892  -0.61342674 -0.6413218  ... -0.07702224 -0.0493612
 -0.02408693] 22050


 53%|███████████████████████████████████████████                                       | 52/99 [02:41<02:33,  3.26s/it]

[-0.87746686 -0.9691256  -1.0164407  ... -0.2245433  -0.14452285
 -0.07082193] 22050


 54%|███████████████████████████████████████████▉                                      | 53/99 [02:45<02:32,  3.32s/it]

[-0.14500825 -0.16018207 -0.16798463 ...  0.11473081  0.06627245
  0.        ] 22050


 55%|████████████████████████████████████████████▋                                     | 54/99 [02:52<03:23,  4.53s/it]

[-0.00199708 -0.00319508 -0.00331803 ... -0.00064225 -0.00038474
  0.        ] 22050


 56%|█████████████████████████████████████████████▌                                    | 55/99 [02:55<02:54,  3.97s/it]

[-0.00066345 -0.00110385 -0.00104151 ...  0.00647592  0.00655071
  0.        ] 22050


 57%|██████████████████████████████████████████████▍                                   | 56/99 [02:58<02:36,  3.63s/it]

[-0.2739319  -0.3025994  -0.31744638 ...  0.01044763  0.00608007
  0.        ] 22050


 58%|███████████████████████████████████████████████▏                                  | 57/99 [03:04<03:08,  4.49s/it]

[-0.06291798 -0.07026124 -0.07465484 ... -0.14951584 -0.09621288
 -0.04716552] 22050


 59%|████████████████████████████████████████████████                                  | 58/99 [03:08<02:53,  4.24s/it]

[-1.7918481e-06 -5.5685846e-06 -9.9844920e-06 ...  2.7333383e-02
  1.7636651e-02  8.6638099e-03] 22050


 60%|████████████████████████████████████████████████▊                                 | 59/99 [03:11<02:36,  3.91s/it]

[ 8.5524260e-07 -2.3861974e-06 -7.3340552e-06 ... -1.3542055e-01
 -8.7212533e-02 -4.2756353e-02] 22050


 61%|█████████████████████████████████████████████████▋                                | 60/99 [03:13<02:15,  3.48s/it]

[-0.00027686 -0.00032779 -0.00035314 ... -0.03754111 -0.02402511
 -0.01169831] 22050


 62%|██████████████████████████████████████████████████▌                               | 61/99 [03:17<02:10,  3.42s/it]

[-1.7565626e-06 -1.2353955e-06  5.4582960e-09 ... -2.6573552e-02
 -1.6467988e-02  0.0000000e+00] 22050


 63%|███████████████████████████████████████████████████▎                              | 62/99 [03:18<01:46,  2.89s/it]

[0.000215   0.00023683 0.00023057 ... 0.0034874  0.00196025 0.        ] 22050


 64%|████████████████████████████████████████████████████▏                             | 63/99 [03:21<01:37,  2.71s/it]

[-3.0497395e-07  1.2244502e-06  3.1903026e-06 ... -9.8866746e-03
 -5.5146376e-03  0.0000000e+00] 22050


 65%|█████████████████████████████████████████████████████                             | 64/99 [03:22<01:25,  2.44s/it]

[6.2300285e-05 7.5929711e-05 8.4309846e-05 ... 9.5062396e-03 5.8767227e-03
 0.0000000e+00] 22050


 66%|█████████████████████████████████████████████████████▊                            | 65/99 [03:24<01:18,  2.32s/it]

[2.0636191e-06 5.3742210e-06 7.9173615e-06 ... 8.8258702e-03 5.2438602e-03
 0.0000000e+00] 22050


 67%|██████████████████████████████████████████████████████▋                           | 66/99 [03:26<01:10,  2.13s/it]

[-1.5476845e-06 -1.4929913e-06  7.7756016e-07 ...  1.0041645e-03
  6.2980881e-04  0.0000000e+00] 22050


 68%|███████████████████████████████████████████████████████▍                          | 67/99 [03:29<01:11,  2.23s/it]

[ 0.          0.          0.         ... -0.12468348 -0.1273278
 -0.14731203] 22050


 69%|████████████████████████████████████████████████████████▎                         | 68/99 [03:31<01:12,  2.34s/it]

[ 0.          0.          0.         ... -0.02251784 -0.02150127
 -0.02269199] 22050


 70%|█████████████████████████████████████████████████████████▏                        | 69/99 [03:34<01:13,  2.46s/it]

[ 0.          0.          0.         ... -0.01567137 -0.01457954
 -0.0151326 ] 22050


 71%|█████████████████████████████████████████████████████████▉                        | 70/99 [03:37<01:17,  2.68s/it]

[0.         0.         0.         ... 0.06823757 0.06161449 0.0576618 ] 22050


 72%|██████████████████████████████████████████████████████████▊                       | 71/99 [03:40<01:17,  2.76s/it]

[ 0.          0.          0.         ... -0.0593754  -0.06029727
 -0.06811669] 22050


 73%|███████████████████████████████████████████████████████████▋                      | 72/99 [03:43<01:17,  2.86s/it]

[ 0.15286843  0.22476168  0.19892806 ... -0.01032892 -0.01059519
 -0.01229354] 22050


 74%|████████████████████████████████████████████████████████████▍                     | 73/99 [03:47<01:18,  3.02s/it]

[0.01386719 0.02011131 0.01776993 ... 0.00524451 0.00579907 0.        ] 22050


 75%|█████████████████████████████████████████████████████████████▎                    | 74/99 [03:49<01:14,  3.00s/it]

[-0.00679656 -0.01003796 -0.00873371 ... -0.02517475 -0.03054456
  0.        ] 22050


 76%|██████████████████████████████████████████████████████████████                    | 75/99 [03:53<01:16,  3.18s/it]

[ 0.00579983  0.00852321  0.00752403 ... -0.00082801 -0.00068914
 -0.00070964] 22050


 77%|██████████████████████████████████████████████████████████████▉                   | 76/99 [03:56<01:12,  3.14s/it]

[-0.00053421 -0.00082033 -0.00076593 ... -0.00522986 -0.00525398
 -0.00585139] 22050


 78%|███████████████████████████████████████████████████████████████▊                  | 77/99 [03:59<01:04,  2.95s/it]

[-2.8764509e-05 -3.0061437e-05 -2.9183469e-05 ... -1.0795601e-03
 -5.5044401e-04  0.0000000e+00] 22050


 79%|████████████████████████████████████████████████████████████████▌                 | 78/99 [04:01<00:56,  2.69s/it]

[-7.8413684e-08  9.5552173e-07  1.9807621e-06 ... -3.6296784e-03
 -2.0876050e-03  0.0000000e+00] 22050


 80%|█████████████████████████████████████████████████████████████████▍                | 79/99 [04:02<00:48,  2.42s/it]

[1.8421345e-06 3.9703418e-06 4.0728492e-06 ... 1.1935446e-03 6.8373588e-04
 0.0000000e+00] 22050


 81%|██████████████████████████████████████████████████████████████████▎               | 80/99 [04:04<00:43,  2.29s/it]

[-2.2084580e-06 -5.9585232e-06 -8.7529661e-06 ... -3.4101740e-02
 -2.1929748e-02 -1.0731890e-02] 22050


 82%|███████████████████████████████████████████████████████████████████               | 81/99 [04:07<00:44,  2.48s/it]

[-5.8840362e-07  2.2181875e-06  5.4235775e-06 ...  3.1400897e-02
  1.6541665e-02  0.0000000e+00] 22050


 83%|███████████████████████████████████████████████████████████████████▉              | 82/99 [04:10<00:43,  2.54s/it]

[ 5.9769508e-07  8.8926954e-06  2.1092692e-05 ... -1.6348783e-02
 -8.8511044e-03  0.0000000e+00] 22050


 84%|████████████████████████████████████████████████████████████████████▋             | 83/99 [04:12<00:37,  2.33s/it]

[ 0.00772112  0.01154974  0.01025985 ... -0.00331298 -0.00319685
 -0.0037348 ] 22050


 85%|█████████████████████████████████████████████████████████████████████▌            | 84/99 [04:16<00:40,  2.73s/it]

[0.28596535 0.3158219  0.33115914 ... 0.08994886 0.05179574 0.        ] 22050


 86%|██████████████████████████████████████████████████████████████████████▍           | 85/99 [04:24<01:00,  4.29s/it]

[-0.27563092 -0.30399603 -0.31818    ...  0.00215952  0.00126481
  0.        ] 22050


 87%|███████████████████████████████████████████████████████████████████████▏          | 86/99 [04:32<01:14,  5.69s/it]

[0.03946353 0.04340422 0.04541007 ... 0.4538223  0.29210246 0.14312147] 22050


 88%|████████████████████████████████████████████████████████████████████████          | 87/99 [04:41<01:18,  6.52s/it]

[-0.3726952  -0.41175988 -0.43205068 ... -0.15957749 -0.10276388
 -0.05036703] 22050


 89%|████████████████████████████████████████████████████████████████████████▉         | 88/99 [04:47<01:10,  6.44s/it]

[-0.2810858  -0.31157294 -0.32829928 ... -0.1266794  -0.08168591
 -0.04014152] 22050


 90%|█████████████████████████████████████████████████████████████████████████▋        | 89/99 [04:54<01:04,  6.48s/it]

[-0.07494406 -0.10856454 -0.09363515 ...  0.01878147  0.01818044
  0.01986458] 22050


 91%|██████████████████████████████████████████████████████████████████████████▌       | 90/99 [04:56<00:48,  5.35s/it]

[ 0.03124345  0.04578807  0.04021889 ... -0.01389698 -0.01351108
 -0.01445538] 22050


 92%|███████████████████████████████████████████████████████████████████████████▎      | 91/99 [04:59<00:36,  4.58s/it]

[-0.02912769 -0.04266582 -0.03835926 ... -0.07225096 -0.07003564
 -0.07565343] 22050


 93%|████████████████████████████████████████████████████████████████████████████▏     | 92/99 [05:03<00:29,  4.26s/it]

[ 0.00182807  0.00246826  0.00192033 ... -0.00439787 -0.00413904
 -0.00436127] 22050


 94%|█████████████████████████████████████████████████████████████████████████████     | 93/99 [05:05<00:22,  3.75s/it]

[-0.06445651 -0.09444108 -0.08404209 ... -0.01689324 -0.01542289
 -0.01585781] 22050


 95%|█████████████████████████████████████████████████████████████████████████████▊    | 94/99 [05:08<00:17,  3.42s/it]

[0.06414742 0.09454045 0.08388222 ... 0.24822964 0.24023329 0.2587387 ] 22050


 96%|██████████████████████████████████████████████████████████████████████████████▋   | 95/99 [05:11<00:12,  3.17s/it]

[ 0.08259647  0.12127037  0.1070242  ... -0.02367939 -0.02266011
 -0.0243049 ] 22050


 97%|███████████████████████████████████████████████████████████████████████████████▌  | 96/99 [05:14<00:09,  3.20s/it]

[-0.0151329  -0.02294918 -0.0202172  ... -0.04157927 -0.04070212
 -0.04374132] 22050


 98%|████████████████████████████████████████████████████████████████████████████████▎ | 97/99 [05:17<00:06,  3.17s/it]

[-0.00485999 -0.00679087 -0.00545568 ...  0.01482467  0.0137242
  0.01388321] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████▏| 98/99 [05:20<00:03,  3.12s/it]

[0.13323113 0.19474407 0.17157386 ... 0.08486681 0.08216646 0.08880045] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 99/99 [05:23<00:00,  3.03s/it]

[0.02923446 0.04403316 0.04038239 ... 0.07650845 0.07465485 0.08051185] 22050


done loading train mfcc


  0%|                                                                                           | 0/85 [00:00<?, ?it/s]

[ 0.          0.          0.         ... -0.15097117 -0.14199436
 -0.15616187] 22050


  2%|█▉                                                                                 | 2/85 [00:02<01:40,  1.21s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


  4%|██▉                                                                                | 3/85 [00:04<02:12,  1.62s/it]

[0.         0.         0.         ... 0.11905885 0.1190711  0.13462272] 22050


  5%|███▉                                                                               | 4/85 [00:07<02:34,  1.91s/it]

[ 0.          0.          0.         ... -0.14376757 -0.14634912
 -0.16929877] 22050


  6%|████▉                                                                              | 5/85 [00:10<02:48,  2.10s/it]

[0.        0.        0.        ... 0.2842634 0.2742911 0.2978991] 22050


  7%|█████▊                                                                             | 6/85 [00:12<03:02,  2.31s/it]

[ 0.          0.          0.         ... -1.0097158  -0.97754306
 -1.0540003 ] 22050


  8%|██████▊                                                                            | 7/85 [00:15<03:03,  2.35s/it]

[ 0.          0.          0.         ... -0.5240373  -0.51735884
 -0.5599158 ] 22050


  9%|███████▊                                                                           | 8/85 [00:18<03:14,  2.53s/it]

[ 0.          0.          0.         ... -0.24339022 -0.23302886
 -0.24892566] 22050


 11%|████████▊                                                                          | 9/85 [00:20<03:06,  2.45s/it]

[0.         0.         0.         ... 0.07006744 0.06390787 0.06843111] 22050


 12%|█████████▋                                                                        | 10/85 [00:23<03:12,  2.56s/it]

[0.         0.         0.         ... 0.23463461 0.22792263 0.26713893] 22050


 13%|██████████▌                                                                       | 11/85 [00:25<03:09,  2.56s/it]

[0.         0.         0.         ... 0.20498481 0.20232959 0.22086047] 22050


 14%|███████████▌                                                                      | 12/85 [00:28<03:06,  2.55s/it]

[-0.00283933 -0.00401512 -0.00344597 ...  0.0097526   0.01072497
  0.        ] 22050


 15%|████████████▌                                                                     | 13/85 [00:31<03:09,  2.63s/it]

[-0.02181281 -0.03193489 -0.02826805 ...  0.00575696  0.00659533
  0.        ] 22050


 16%|█████████████▌                                                                    | 14/85 [00:33<03:03,  2.59s/it]

[ 0.00773429  0.01167202  0.01085229 ... -0.00154025 -0.00176283
  0.        ] 22050


 18%|██████████████▍                                                                   | 15/85 [00:36<03:01,  2.59s/it]

[-9.4293209e-04 -1.5129785e-03 -1.3976007e-03 ...  2.1218079e-04
  7.5372486e-07  0.0000000e+00] 22050


 19%|███████████████▍                                                                  | 16/85 [00:39<03:00,  2.62s/it]

[ 0.0016893   0.00271707  0.00256709 ... -0.00106804 -0.00115121
  0.        ] 22050


 20%|████████████████▍                                                                 | 17/85 [00:42<03:09,  2.79s/it]

[-8.8425225e-04 -1.0659160e-03 -8.0528628e-04 ... -4.2387831e-04
 -5.7793855e-05  0.0000000e+00] 22050


 21%|█████████████████▎                                                                | 18/85 [00:45<03:17,  2.95s/it]

[0.01710793 0.02544549 0.0228809  ... 0.04074765 0.03925414 0.04185763] 22050


 22%|██████████████████▎                                                               | 19/85 [00:48<03:08,  2.86s/it]

[ 0.          0.          0.         ... -0.00365696  0.00048274
 -0.00258029] 22050


 24%|███████████████████▎                                                              | 20/85 [00:51<03:09,  2.92s/it]

[ 0.          0.          0.         ... -0.15257472 -0.14495775
 -0.1533123 ] 22050


 25%|████████████████████▎                                                             | 21/85 [00:54<03:10,  2.98s/it]

[ 0.          0.          0.         ... -0.11059644 -0.1085563
 -0.12142587] 22050


 26%|█████████████████████▏                                                            | 22/85 [00:57<03:05,  2.95s/it]

[ 0.          0.          0.         ... -0.02616313 -0.02832824
 -0.03311377] 22050


 27%|██████████████████████▏                                                           | 23/85 [01:00<03:00,  2.91s/it]

[ 0.          0.          0.         ... -0.10821859 -0.10085784
 -0.10736299] 22050


 28%|███████████████████████▏                                                          | 24/85 [01:03<03:09,  3.10s/it]

[0.         0.         0.         ... 0.26945388 0.2562324  0.27221316] 22050


 29%|████████████████████████                                                          | 25/85 [01:07<03:10,  3.18s/it]

[ 0.          0.          0.         ... -0.05926341 -0.05534621
 -0.05793385] 22050


 31%|█████████████████████████                                                         | 26/85 [01:10<03:08,  3.20s/it]

[ 0.          0.          0.         ... -0.04694906 -0.05055835
 -0.06256957] 22050


 32%|██████████████████████████                                                        | 27/85 [01:15<03:39,  3.78s/it]

[0.         0.         0.         ... 0.17112456 0.16861391 0.18079142] 22050


 33%|███████████████████████████                                                       | 28/85 [01:20<03:52,  4.09s/it]

[0.         0.         0.         ... 0.09519187 0.0919826  0.10184121] 22050


 34%|███████████████████████████▉                                                      | 29/85 [01:23<03:36,  3.87s/it]

[0.         0.         0.         ... 0.20328416 0.19927321 0.21701668] 22050


 35%|████████████████████████████▉                                                     | 30/85 [01:27<03:28,  3.78s/it]

[0.         0.         0.         ... 0.1784105  0.17279524 0.18705997] 22050


 36%|█████████████████████████████▉                                                    | 31/85 [01:30<03:16,  3.64s/it]

[0.         0.         0.         ... 0.15806355 0.15504608 0.16754578] 22050


 38%|██████████████████████████████▊                                                   | 32/85 [01:33<02:58,  3.38s/it]

[0.         0.         0.         ... 0.02381264 0.02345375 0.02424698] 22050


 39%|███████████████████████████████▊                                                  | 33/85 [01:36<02:45,  3.19s/it]

[0.         0.         0.         ... 0.0633135  0.06167608 0.06543391] 22050


 40%|████████████████████████████████▊                                                 | 34/85 [01:38<02:35,  3.05s/it]

[0.         0.         0.         ... 0.06957164 0.06568859 0.06777759] 22050


 41%|█████████████████████████████████▊                                                | 35/85 [01:40<02:19,  2.78s/it]

[0.         0.         0.         ... 0.5169264  0.49420917 0.52765614] 22050


 42%|██████████████████████████████████▋                                               | 36/85 [01:43<02:18,  2.84s/it]

[ 0.          0.          0.         ... -0.6361075  -0.61864734
 -0.67175263] 22050


 44%|███████████████████████████████████▋                                              | 37/85 [01:46<02:16,  2.85s/it]

[0.         0.         0.         ... 0.45760438 0.44249195 0.47693253] 22050


 45%|████████████████████████████████████▋                                             | 38/85 [01:50<02:21,  3.02s/it]

[ 0.          0.          0.         ... -0.07948826 -0.07436877
 -0.08173631] 22050


 46%|█████████████████████████████████████▌                                            | 39/85 [01:53<02:20,  3.04s/it]

[0.         0.         0.         ... 0.09586173 0.09115418 0.0959226 ] 22050


 47%|██████████████████████████████████████▌                                           | 40/85 [01:56<02:23,  3.20s/it]

[0.         0.         0.         ... 0.00059579 0.00040884 0.00018524] 22050


 48%|███████████████████████████████████████▌                                          | 41/85 [01:59<02:19,  3.16s/it]

[0.         0.         0.         ... 0.00061468 0.00073731 0.0010129 ] 22050


 49%|████████████████████████████████████████▌                                         | 42/85 [02:02<02:09,  3.01s/it]

[0.         0.         0.         ... 0.00469436 0.00457318 0.00489088] 22050


 51%|█████████████████████████████████████████▍                                        | 43/85 [02:04<01:57,  2.79s/it]

[ 0.          0.          0.         ... -0.03966789 -0.00456789
 -0.01253633] 22050


 52%|██████████████████████████████████████████▍                                       | 44/85 [02:07<01:51,  2.72s/it]

[ 0.          0.          0.         ... -0.01443889 -0.0036065
  0.00768639] 22050


 53%|███████████████████████████████████████████▍                                      | 45/85 [02:10<01:54,  2.85s/it]

[0.         0.         0.         ... 0.02293075 0.02522327 0.02491388] 22050


 54%|████████████████████████████████████████████▍                                     | 46/85 [02:13<01:57,  3.00s/it]

[ 0.          0.          0.         ... -0.01902727 -0.01628051
 -0.00893455] 22050


 55%|█████████████████████████████████████████████▎                                    | 47/85 [02:16<01:49,  2.88s/it]

[0.         0.         0.         ... 0.0115454  0.01240722 0.01308329] 22050


 56%|██████████████████████████████████████████████▎                                   | 48/85 [02:19<01:43,  2.79s/it]

[0.         0.         0.         ... 0.01450576 0.01357326 0.01446307] 22050


 58%|███████████████████████████████████████████████▎                                  | 49/85 [02:21<01:35,  2.66s/it]

[ 0.          0.          0.         ... -0.12028453 -0.11824434
 -0.13014063] 22050


 59%|████████████████████████████████████████████████▏                                 | 50/85 [02:24<01:32,  2.65s/it]

[0.         0.         0.         ... 0.0605499  0.05868293 0.06159526] 22050


 60%|█████████████████████████████████████████████████▏                                | 51/85 [02:26<01:24,  2.50s/it]

[0.         0.         0.         ... 0.01557782 0.01462343 0.01515078] 22050


 61%|██████████████████████████████████████████████████▏                               | 52/85 [02:29<01:26,  2.62s/it]

[ 0.          0.          0.         ... -0.02254345 -0.02208381
 -0.02349323] 22050


 62%|███████████████████████████████████████████████████▏                              | 53/85 [02:31<01:22,  2.56s/it]

[ 0.          0.          0.         ... -0.04213747 -0.04335009
 -0.05171286] 22050


 64%|████████████████████████████████████████████████████                              | 54/85 [02:33<01:18,  2.52s/it]

[ 0.          0.          0.         ... -0.00891681 -0.00817552
 -0.00768843] 22050


 65%|█████████████████████████████████████████████████████                             | 55/85 [02:36<01:17,  2.57s/it]

[0.         0.         0.         ... 0.02309799 0.02317885 0.02198694] 22050


 66%|██████████████████████████████████████████████████████                            | 56/85 [02:39<01:13,  2.53s/it]

[0.         0.         0.         ... 0.0338887  0.03054287 0.0315167 ] 22050


 67%|██████████████████████████████████████████████████████▉                           | 57/85 [02:41<01:13,  2.63s/it]

[0.         0.         0.         ... 0.00358016 0.0029045  0.00199023] 22050


 68%|███████████████████████████████████████████████████████▉                          | 58/85 [02:44<01:09,  2.59s/it]

[0.         0.         0.         ... 0.04359322 0.04235546 0.04606871] 22050


 69%|████████████████████████████████████████████████████████▉                         | 59/85 [02:47<01:08,  2.64s/it]

[0.         0.         0.         ... 0.07358634 0.06766799 0.07189249] 22050


 71%|█████████████████████████████████████████████████████████▉                        | 60/85 [02:49<01:05,  2.64s/it]

[ 0.          0.          0.         ... -0.06227456 -0.05999418
 -0.06597839] 22050


 72%|██████████████████████████████████████████████████████████▊                       | 61/85 [02:52<01:02,  2.61s/it]

[0.         0.         0.         ... 0.05142609 0.04925839 0.05164963] 22050


 73%|███████████████████████████████████████████████████████████▊                      | 62/85 [02:55<01:03,  2.75s/it]

[ 0.          0.          0.         ... -0.00450196 -0.00267744
 -0.00234501] 22050


 74%|████████████████████████████████████████████████████████████▊                     | 63/85 [02:57<00:57,  2.60s/it]

[ 0.          0.          0.         ... -0.02519566 -0.02452996
 -0.02345673] 22050


 75%|█████████████████████████████████████████████████████████████▋                    | 64/85 [03:00<00:56,  2.67s/it]

[0.         0.         0.         ... 0.08202307 0.08476666 0.09766038] 22050


 76%|██████████████████████████████████████████████████████████████▋                   | 65/85 [03:03<00:53,  2.66s/it]

[ 0.          0.          0.         ... -0.03965227 -0.04023258
 -0.04159994] 22050


 78%|███████████████████████████████████████████████████████████████▋                  | 66/85 [03:06<00:54,  2.84s/it]

[0.         0.         0.         ... 0.26817232 0.25902474 0.280427  ] 22050


 79%|████████████████████████████████████████████████████████████████▋                 | 67/85 [03:09<00:52,  2.92s/it]

[0.         0.         0.         ... 0.00342826 0.00317979 0.00364171] 22050


 80%|█████████████████████████████████████████████████████████████████▌                | 68/85 [03:12<00:50,  2.99s/it]

[0.         0.         0.         ... 0.07517342 0.07454691 0.07867888] 22050


 81%|██████████████████████████████████████████████████████████████████▌               | 69/85 [03:15<00:48,  3.02s/it]

[-0.07247163 -0.10745685 -0.09690773 ...  0.05467346  0.05316706
  0.05753393] 22050


 82%|███████████████████████████████████████████████████████████████████▌              | 70/85 [03:19<00:49,  3.31s/it]

[-0.05803953 -0.08320587 -0.07533526 ...  0.03917618  0.0369745
  0.04105215] 22050


 84%|████████████████████████████████████████████████████████████████████▍             | 71/85 [03:23<00:47,  3.36s/it]

[ 0.17166029  0.250432    0.21842906 ... -0.03571897 -0.03179305
 -0.03728459] 22050


 85%|█████████████████████████████████████████████████████████████████████▍            | 72/85 [03:26<00:43,  3.37s/it]

[0.         0.         0.         ... 0.3051465  0.29893237 0.3225977 ] 22050


 86%|██████████████████████████████████████████████████████████████████████▍           | 73/85 [03:29<00:40,  3.36s/it]

[0.         0.         0.         ... 0.7375129  0.72093195 0.78232914] 22050


 87%|███████████████████████████████████████████████████████████████████████▍          | 74/85 [03:33<00:38,  3.54s/it]

[ 0.          0.          0.         ... -0.00942516 -0.00825206
 -0.00559559] 22050


 88%|████████████████████████████████████████████████████████████████████████▎         | 75/85 [03:38<00:37,  3.77s/it]

[0.         0.         0.         ... 0.15102854 0.14400037 0.16173281] 22050


 89%|█████████████████████████████████████████████████████████████████████████▎        | 76/85 [03:42<00:34,  3.84s/it]

[ 0.          0.          0.         ... -0.06790091 -0.10178107
 -0.13769501] 22050


 91%|██████████████████████████████████████████████████████████████████████████▎       | 77/85 [03:46<00:31,  3.92s/it]

[0.         0.         0.         ... 0.02256879 0.02788899 0.03947941] 22050


 92%|███████████████████████████████████████████████████████████████████████████▏      | 78/85 [03:49<00:25,  3.68s/it]

[ 0.          0.          0.         ... -0.45220456 -0.43463495
 -0.45182434] 22050


 93%|████████████████████████████████████████████████████████████████████████████▏     | 79/85 [03:52<00:20,  3.40s/it]

[ 0.          0.          0.         ... -0.39158678 -0.38113743
 -0.41354823] 22050


 94%|█████████████████████████████████████████████████████████████████████████████▏    | 80/85 [03:55<00:17,  3.40s/it]

[0.         0.         0.         ... 0.06476758 0.05989117 0.0667561 ] 22050


 95%|██████████████████████████████████████████████████████████████████████████████▏   | 81/85 [03:58<00:13,  3.30s/it]

[0.        0.        0.        ... 1.0092846 0.9777773 1.0537751] 22050


 96%|███████████████████████████████████████████████████████████████████████████████   | 82/85 [04:02<00:09,  3.33s/it]

[0.         0.         0.         ... 0.02226742 0.02208254 0.02119073] 22050


 98%|████████████████████████████████████████████████████████████████████████████████  | 83/85 [04:05<00:06,  3.21s/it]

[0.         0.         0.         ... 0.02370285 0.02627874 0.028067  ] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████ | 84/85 [04:08<00:03,  3.27s/it]

[ 0.          0.          0.         ... -0.22099693 -0.21257466
 -0.23776534] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 85/85 [04:11<00:00,  3.34s/it]

[ 0.          0.          0.         ... -0.05103435 -0.05238643
 -0.05545169] 22050


done loading test mfcc


In [8]:
train_data['fname'] = train['fname']
train_data['label'] = train['label']

test_data['fname'] = audio_test_files
test_data['label'] = np.zeros((len(audio_test_files)))

In [9]:
#print(train_data)
#print(test_data)

In [10]:
X = train_data.drop(['label', 'fname'], axis=1)
feature_names = list(X.columns)
X = X.values
labels = np.sort(np.unique(train_data.label.values))
num_class = len(labels)
c2i = {}
i2c = {}
for i, c in enumerate(labels):
    c2i[c] = i
    i2c[i] = c
y = np.array([c2i[x] for x in train_data.label.values])

#print(X)
#y는 train 데이터들이 라벨링한 것
print(y)

[0 0 1 2 3 3 3 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 5 5 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 5 5
 3 3 3 3 3 3 3 3 0 3 3 3 3 3 1 1 6 6 6 6 6 6 6 6 6]


In [11]:
X_test = test_data.drop(['label', 'fname'], axis=1)
X_test = X_test.values

In [12]:
print(X.shape)
print(X_test.shape)
#test의 라벨링은 어디서?

(99, 210)
(85, 210)


In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)
#이놈이 뭘까

In [14]:
#pca = PCA(n_components=65).fit(X_scaled)
#65땜에 오류뜸
pca = PCA(n_components=65).fit(X_scaled)
#이 값 고쳐야
X_pca = pca.transform(X_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(sum(pca.explained_variance_ratio_)) 

0.9927819852312187


In [15]:
# Fit an SVM model
X_train, X_val, y_train, y_val = train_test_split(X_pca, y, test_size = 0.2, random_state = 42, shuffle = True)
#test_size와 random_state 확인

#train 관련
#print(X_train)
#print(y_train) - train 라벨링

#train 내에서 쪼개는 것으로 추측됨 test 0.2가 100개중 20개로 맞네
#test를 따로 만드는게 아니라 train 내에서 일부를 test에 사용하여 정확도 측정
print(X_val)
print(y_val)

clf = SVC(kernel = 'rbf', probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

[[ 4.88100404 -3.43397136 -3.29845388 ... -0.61609378  0.23458665
   0.97816446]
 [ 0.26160425  5.18237066 -2.43019333 ... -0.24010789 -0.35883319
  -0.09569657]
 [ 0.91343711 -2.02287154  2.09438045 ... -0.59792007 -1.20865358
  -0.2661965 ]
 ...
 [-6.1306718  -4.3883038  -6.27430465 ...  0.18317393  0.20533995
   0.42573345]
 [ 2.40666755  3.78935566  9.21096189 ... -0.21731497  0.16284491
  -0.09165545]
 [ 1.16133406  8.34994398  7.72972024 ...  0.04968694  0.01360946
  -0.70441906]]
[3 3 6 3 6 3 3 3 0 0 3 3 3 3 3 3 3 3 1 5]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.75


In [16]:
C_grid = [0.001, 0.01, 0.1, 1, 10]
gamma_grid = [0.001, 0.01, 0.1, 1, 10]
param_grid = {'C': C_grid, 'gamma' : gamma_grid}

#grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
#이부분 수정해야
#데이터 갯수 확 느니까 바로먹음
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
grid.fit(X_train, y_train)

# Find the best model
print(grid.best_score_)

print(grid.best_params_)

print(grid.best_estimator_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.8860759493670886
{'C': 10, 'gamma': 0.001}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [19]:
clf = SVC(kernel = 'rbf', C = 10, gamma = 0.001, probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

0.85


In [18]:
# Fit the entire training sets
clf.fit(X_pca, y)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)