In [1]:
#csv파일이랑 audio폴더 test 양만큼 개줄여서 디버그하며 할 것

import os
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import pandas as pd
import csv

import scipy
from scipy.stats import skew
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.svm import SVC

In [2]:
filename = np.array(pd.read_csv('data/SC_file_name.csv'))
answer = np.array(pd.read_csv('data/SC_answer.csv'))

audio_train_files = os.listdir('./audio_train/')
audio_test_files = os.listdir('./audio_test/')
train=pd.read_csv('./file_name.csv')

In [3]:
#print(audio_train_files)
#print(audio_test_files)

In [4]:
def get_mfcc(name, path):
    data, _ = librosa.core.load(path+name) #엑셀에 .wav까지 붙여 저장해야됨 안그러면 path+name+'.wav' 이렇게해야
    print(data,_)
    #data, _ = librosa.load(path)
    try:
        #ft1 = librosa.feature.mfcc(data, sr = SAMPLE_RATE, n_mfcc=30)
        ft1 = librosa.feature.mfcc(data, n_mfcc=30) #이게핵심 Sample_rate를 어떻게 조절하느냐
        ft2 = librosa.feature.zero_crossing_rate(data)[0] # n_mfcc 값을 어떻게 조절하느냐에 따라 Feature개수가 달리 뽑힘
        ft3 = librosa.feature.spectral_rolloff(data)[0]
        ft4 = librosa.feature.spectral_centroid(data)[0]
        ft5 = librosa.feature.spectral_contrast(data)[0]
        ft6 = librosa.feature.spectral_bandwidth(data)[0]
        ft1_trunc = np.hstack((np.mean(ft1, axis=1), np.std(ft1, axis=1), skew(ft1, axis = 1), np.max(ft1, axis = 1), np.median(ft1, axis = 1), np.min(ft1, axis = 1)))
        ft2_trunc = np.hstack((np.mean(ft2), np.std(ft2), skew(ft2), np.max(ft2), np.median(ft2), np.min(ft2)))
        ft3_trunc = np.hstack((np.mean(ft3), np.std(ft3), skew(ft3), np.max(ft3), np.median(ft3), np.min(ft3)))
        ft4_trunc = np.hstack((np.mean(ft4), np.std(ft4), skew(ft4), np.max(ft4), np.median(ft4), np.min(ft4)))
        ft5_trunc = np.hstack((np.mean(ft5), np.std(ft5), skew(ft5), np.max(ft5), np.median(ft5), np.min(ft5)))
        ft6_trunc = np.hstack((np.mean(ft6), np.std(ft6), skew(ft6), np.max(ft6), np.median(ft6), np.max(ft6)))
        return pd.Series(np.hstack((ft1_trunc, ft2_trunc, ft3_trunc, ft4_trunc, ft5_trunc, ft6_trunc)))
    except:
        print('bad file')
        return pd.Series([0]*210)

In [5]:
train_data = pd.DataFrame()
train_data['fname'] = train['fname']
test_data=pd.DataFrame()
test_data['fname']=audio_test_files

In [6]:
#print(train_data)
print(test_data)


                         fname
0   130_1p3_Al_mc_AKGC417L.wav
1   130_1p3_Ar_mc_AKGC417L.wav
2   130_1p3_Ll_mc_AKGC417L.wav
3   130_1p3_Lr_mc_AKGC417L.wav
4   130_1p3_Pl_mc_AKGC417L.wav
5   130_1p3_Pr_mc_AKGC417L.wav
6   130_1p3_Tc_mc_AKGC417L.wav
7   130_1p4_Al_mc_AKGC417L.wav
8   200_2p4_Al_mc_AKGC417L.wav
9   200_2p4_Ar_mc_AKGC417L.wav
10  200_2p4_Lr_mc_AKGC417L.wav
11  200_2p4_Pl_mc_AKGC417L.wav
12  200_2p4_Pr_mc_AKGC417L.wav
13  200_2p4_Tc_mc_AKGC417L.wav
14  200_3p4_Al_mc_AKGC417L.wav
15  200_3p4_Ar_mc_AKGC417L.wav
16  200_3p4_Pl_mc_AKGC417L.wav
17  200_3p4_Pr_mc_AKGC417L.wav
18  200_3p4_Tc_mc_AKGC417L.wav
19  201_1b1_Al_sc_Meditron.wav
20  201_1b1_Ar_sc_Meditron.wav
21  201_1b2_Al_sc_Meditron.wav
22  201_1b2_Ar_sc_Meditron.wav
23  201_1b3_Al_sc_Meditron.wav
24  201_1b3_Ar_sc_Meditron.wav
25  202_1b1_Ar_sc_Meditron.wav
26  203_1p2_Al_mc_AKGC417L.wav
27  203_1p2_Ar_mc_AKGC417L.wav
28  203_1p2_Lr_mc_AKGC417L.wav
29  203_1p2_Pl_mc_AKGC417L.wav
..                         ...
63  205_

In [7]:
train_data=train_data['fname'].progress_apply(get_mfcc,path='./audio_train/')
print('done loading train mfcc')
test_data = test_data['fname'].progress_apply(get_mfcc, path='./audio_test/')
print('done loading test mfcc')



  0%|                                                                                          | 0/299 [00:00<?, ?it/s]

[0.06973912 0.10266001 0.09116188 ... 0.08305359 0.08018959 0.08612607] 22050


  1%|▌                                                                                 | 2/299 [00:06<15:37,  3.16s/it]

[-0.02710845 -0.03993477 -0.03530764 ... -0.04230448 -0.0414599
 -0.04527015] 22050


  1%|▊                                                                                 | 3/299 [00:09<14:54,  3.02s/it]

[ 0.00283427  0.00423394  0.0036414  ... -0.01369482 -0.01395124
 -0.01601286] 22050


  1%|█                                                                                 | 4/299 [00:11<14:20,  2.92s/it]

[-0.2545665  -0.37054616 -0.3232944  ... -0.05147256 -0.04832996
 -0.0513258 ] 22050


  2%|█▎                                                                                | 5/299 [00:14<13:59,  2.86s/it]

[ 3.1871754e-05  6.1540527e-06 -3.7155998e-05 ... -1.4125325e-02
 -8.7606525e-03  0.0000000e+00] 22050


  2%|█▋                                                                                | 6/299 [00:16<12:26,  2.55s/it]

[ 0.00079253  0.00089992  0.00091092 ... -0.0049351  -0.00259066
  0.        ] 22050


  2%|█▉                                                                                | 7/299 [00:19<13:08,  2.70s/it]

[ 3.0208554e-05  3.0756044e-05  2.5381032e-05 ... -1.8259089e-02
 -1.1751885e-02 -5.7575861e-03] 22050


  3%|██▏                                                                               | 8/299 [00:20<11:32,  2.38s/it]

[-0.00064508 -0.00077814 -0.0008623  ... -0.01482992 -0.00782498
  0.        ] 22050


  3%|██▍                                                                               | 9/299 [00:22<10:50,  2.24s/it]

[ 0.00110417  0.00130484  0.00140896 ... -0.01235658 -0.00798214
 -0.00392708] 22050


  3%|██▋                                                                              | 10/299 [00:25<11:31,  2.39s/it]

[ 4.3292630e-07  3.4875336e-06  7.9502988e-06 ... -4.9829770e-02
 -2.8054921e-02  0.0000000e+00] 22050


  4%|██▉                                                                              | 11/299 [00:28<12:47,  2.67s/it]

[0.00072087 0.00177281 0.00336674 ... 0.03278232 0.03167795 0.0341762 ] 22050


  4%|███▎                                                                             | 12/299 [00:31<13:17,  2.78s/it]

[-0.00511142 -0.00661265 -0.00532051 ...  0.05818591  0.05825811
  0.06405238] 22050


  4%|███▌                                                                             | 13/299 [00:35<13:40,  2.87s/it]

[ 0.13884057  0.20461525  0.18165357 ... -0.07205642 -0.07238604
 -0.08182055] 22050


  5%|███▊                                                                             | 14/299 [00:37<13:14,  2.79s/it]

[ 0.          0.          0.         ... -0.03222465 -0.02863552
 -0.02814007] 22050


  5%|████                                                                             | 15/299 [00:40<13:45,  2.91s/it]

[0.         0.         0.         ... 0.81409144 0.7837968  0.8404915 ] 22050


  5%|████▎                                                                            | 16/299 [00:44<14:40,  3.11s/it]

[0.         0.         0.         ... 0.2893713  0.28139624 0.3021213 ] 22050


  6%|████▌                                                                            | 17/299 [00:47<14:10,  3.02s/it]

[ 0.          0.          0.         ... -0.15555128 -0.14919281
 -0.1552921 ] 22050


  6%|████▉                                                                            | 18/299 [00:49<13:45,  2.94s/it]

[0.         0.         0.         ... 0.02468135 0.02214165 0.01943384] 22050


  6%|█████▏                                                                           | 19/299 [00:52<12:51,  2.75s/it]

[ 0.          0.          0.         ... -0.34570888 -0.34052533
 -0.37189066] 22050


  7%|█████▍                                                                           | 20/299 [00:55<13:06,  2.82s/it]

[ 0.          0.          0.         ... -0.36525172 -0.35147998
 -0.3764349 ] 22050


  7%|█████▋                                                                           | 21/299 [00:57<12:47,  2.76s/it]

[0.         0.         0.         ... 0.29563662 0.29204592 0.32384074] 22050


  7%|█████▉                                                                           | 22/299 [01:00<13:13,  2.87s/it]

[ 0.          0.          0.         ... -0.87329555 -0.8426997
 -0.904122  ] 22050


  8%|██████▏                                                                          | 23/299 [01:03<12:59,  2.83s/it]

[0.         0.         0.         ... 0.08035016 0.07610521 0.08158155] 22050


  8%|██████▌                                                                          | 24/299 [01:06<12:28,  2.72s/it]

[0.         0.         0.         ... 0.07361161 0.07532007 0.08183191] 22050


  8%|██████▊                                                                          | 25/299 [01:08<12:20,  2.70s/it]

[ 0.          0.          0.         ... -0.05342972 -0.0532412
 -0.06048   ] 22050


  9%|███████                                                                          | 26/299 [01:11<11:52,  2.61s/it]

[0.         0.         0.         ... 0.48654523 0.47395992 0.5123876 ] 22050


  9%|███████▎                                                                         | 27/299 [01:13<11:16,  2.49s/it]

[0.         0.         0.         ... 0.01937228 0.01565968 0.01233602] 22050


  9%|███████▌                                                                         | 28/299 [01:15<11:08,  2.47s/it]

[0.         0.         0.         ... 0.21377535 0.19589575 0.19898888] 22050


 10%|███████▊                                                                         | 29/299 [01:18<11:10,  2.48s/it]

[ 0.          0.          0.         ... -0.03692322 -0.04029846
 -0.03779646] 22050


 10%|████████▏                                                                        | 30/299 [01:20<10:55,  2.44s/it]

[ 0.          0.          0.         ... -0.00111335  0.00120612
 -0.00136599] 22050


 10%|████████▍                                                                        | 31/299 [01:23<10:46,  2.41s/it]

[ 0.          0.          0.         ... -0.27843747 -0.2646894
 -0.28205138] 22050


 11%|████████▋                                                                        | 32/299 [01:25<10:38,  2.39s/it]

[ 0.          0.          0.         ... -0.26306844 -0.2522001
 -0.26922488] 22050


 11%|████████▉                                                                        | 33/299 [01:27<10:19,  2.33s/it]

[0.         0.         0.         ... 0.1735332  0.17125647 0.19119985] 22050


 11%|█████████▏                                                                       | 34/299 [01:29<10:22,  2.35s/it]

[ 0.          0.          0.         ... -0.2167718  -0.2080332
 -0.22265384] 22050


 12%|█████████▍                                                                       | 35/299 [01:32<10:26,  2.37s/it]

[ 0.          0.          0.         ... -0.05900886 -0.06246108
 -0.06871106] 22050


 12%|█████████▊                                                                       | 36/299 [01:34<10:29,  2.39s/it]

[0.         0.         0.         ... 0.7010785  0.68610245 0.7446819 ] 22050


 12%|██████████                                                                       | 37/299 [01:37<11:09,  2.56s/it]

[ 0.          0.          0.         ... -0.1005215  -0.09558512
 -0.09833872] 22050


 13%|██████████▎                                                                      | 38/299 [01:40<11:13,  2.58s/it]

[ 0.          0.          0.         ... -0.09970824 -0.10170659
 -0.11256789] 22050


 13%|██████████▌                                                                      | 39/299 [01:43<11:25,  2.64s/it]

[ 0.          0.          0.         ... -0.09393648 -0.0905112
 -0.09887574] 22050


 13%|██████████▊                                                                      | 40/299 [01:46<12:26,  2.88s/it]

[ 0.          0.          0.         ... -0.10736632 -0.10226438
 -0.10872729] 22050


 14%|███████████                                                                      | 41/299 [01:49<12:38,  2.94s/it]

[ 0.          0.          0.         ... -0.3698437  -0.36839765
 -0.4094729 ] 22050


 14%|███████████▍                                                                     | 42/299 [01:53<13:11,  3.08s/it]

[-0.00949201 -0.01515351 -0.01494985 ...  0.03122446  0.03000467
  0.03189378] 22050


 14%|███████████▋                                                                     | 43/299 [01:56<13:41,  3.21s/it]

[-1.7585522e-06 -2.2429733e-06 -1.9274846e-06 ... -1.1987473e-02
 -7.4312286e-03  0.0000000e+00] 22050


 15%|███████████▉                                                                     | 44/299 [01:58<12:25,  2.92s/it]

[-3.1364743e-05 -3.4258581e-05 -3.3931665e-05 ...  5.3538714e-04
  3.7836187e-04  0.0000000e+00] 22050


 15%|████████████▏                                                                    | 45/299 [02:01<12:31,  2.96s/it]

[-2.9586021e-05 -3.3629472e-05 -3.4923316e-05 ... -2.4650006e-03
 -1.3031738e-03  0.0000000e+00] 22050


 15%|████████████▍                                                                    | 46/299 [02:03<11:17,  2.68s/it]

[3.0384650e-05 3.1305051e-05 2.8012693e-05 ... 3.9614424e-02 2.4514157e-02
 0.0000000e+00] 22050


 16%|████████████▋                                                                    | 47/299 [02:05<09:53,  2.36s/it]

[-0.00015414 -0.00019182 -0.00021949 ...  0.02211454  0.01247506
  0.        ] 22050


 16%|█████████████                                                                    | 48/299 [02:07<09:50,  2.35s/it]

[2.9788309e-05 3.2301657e-05 3.1995405e-05 ... 1.5126610e-03 9.7192550e-04
 4.7570144e-04] 22050


 16%|█████████████▎                                                                   | 49/299 [02:12<12:35,  3.02s/it]

[-0.30551556 -0.337594   -0.35426965 ...  0.04488467  0.02582479
  0.        ] 22050


 17%|█████████████▌                                                                   | 50/299 [02:20<18:16,  4.41s/it]

[-0.30030748 -0.3313869  -0.3471481  ... -0.10257331 -0.06606323
 -0.03239066] 22050


 17%|█████████████▊                                                                   | 51/299 [02:23<16:40,  4.03s/it]

[-0.5566892  -0.61342674 -0.6413218  ... -0.07702224 -0.0493612
 -0.02408693] 22050


 17%|██████████████                                                                   | 52/299 [02:26<15:33,  3.78s/it]

[-0.87746686 -0.9691256  -1.0164407  ... -0.2245433  -0.14452285
 -0.07082193] 22050


 18%|██████████████▎                                                                  | 53/299 [02:29<14:35,  3.56s/it]

[-0.14500825 -0.16018207 -0.16798463 ...  0.11473081  0.06627245
  0.        ] 22050


 18%|██████████████▋                                                                  | 54/299 [02:36<18:37,  4.56s/it]

[-0.00199708 -0.00319508 -0.00331803 ... -0.00064225 -0.00038474
  0.        ] 22050


 18%|██████████████▉                                                                  | 55/299 [02:38<15:51,  3.90s/it]

[-0.00066345 -0.00110385 -0.00104151 ...  0.00647592  0.00655071
  0.        ] 22050


 19%|███████████████▏                                                                 | 56/299 [02:41<13:46,  3.40s/it]

[-0.2739319  -0.3025994  -0.31744638 ...  0.01044763  0.00608007
  0.        ] 22050


 19%|███████████████▍                                                                 | 57/299 [02:47<17:09,  4.25s/it]

[-0.06291798 -0.07026124 -0.07465484 ... -0.14951584 -0.09621288
 -0.04716552] 22050


 19%|███████████████▋                                                                 | 58/299 [02:50<16:21,  4.07s/it]

[-1.7918481e-06 -5.5685846e-06 -9.9844920e-06 ...  2.7333383e-02
  1.7636651e-02  8.6638099e-03] 22050


 20%|███████████████▉                                                                 | 59/299 [02:55<17:21,  4.34s/it]

[ 8.5524260e-07 -2.3861974e-06 -7.3340552e-06 ... -1.3542055e-01
 -8.7212533e-02 -4.2756353e-02] 22050


 20%|████████████████▎                                                                | 60/299 [02:59<16:01,  4.02s/it]

[-0.00027686 -0.00032779 -0.00035314 ... -0.03754111 -0.02402511
 -0.01169831] 22050


 20%|████████████████▌                                                                | 61/299 [03:02<15:03,  3.80s/it]

[-1.7565626e-06 -1.2353955e-06  5.4582960e-09 ... -2.6573552e-02
 -1.6467988e-02  0.0000000e+00] 22050


 21%|████████████████▊                                                                | 62/299 [03:03<12:09,  3.08s/it]

[0.000215   0.00023683 0.00023057 ... 0.0034874  0.00196025 0.        ] 22050


 21%|█████████████████                                                                | 63/299 [03:05<10:25,  2.65s/it]

[-3.0497395e-07  1.2244502e-06  3.1903026e-06 ... -9.8866746e-03
 -5.5146376e-03  0.0000000e+00] 22050


 21%|█████████████████▎                                                               | 64/299 [03:07<09:32,  2.44s/it]

[6.2300285e-05 7.5929711e-05 8.4309846e-05 ... 9.5062396e-03 5.8767227e-03
 0.0000000e+00] 22050


 22%|█████████████████▌                                                               | 65/299 [03:08<08:23,  2.15s/it]

[2.0636191e-06 5.3742210e-06 7.9173615e-06 ... 8.8258702e-03 5.2438602e-03
 0.0000000e+00] 22050


 22%|█████████████████▉                                                               | 66/299 [03:10<07:48,  2.01s/it]

[-1.5476845e-06 -1.4929913e-06  7.7756016e-07 ...  1.0041645e-03
  6.2980881e-04  0.0000000e+00] 22050


 22%|██████████████████▏                                                              | 67/299 [03:12<08:09,  2.11s/it]

[ 0.          0.          0.         ... -0.12468348 -0.1273278
 -0.14731203] 22050


 23%|██████████████████▍                                                              | 68/299 [03:15<08:52,  2.31s/it]

[ 0.          0.          0.         ... -0.02251784 -0.02150127
 -0.02269199] 22050


 23%|██████████████████▋                                                              | 69/299 [03:19<10:39,  2.78s/it]

[ 0.          0.          0.         ... -0.01567137 -0.01457954
 -0.0151326 ] 22050


 23%|██████████████████▉                                                              | 70/299 [03:22<10:54,  2.86s/it]

[0.         0.         0.         ... 0.06823757 0.06161449 0.0576618 ] 22050


 24%|███████████████████▏                                                             | 71/299 [03:26<11:59,  3.15s/it]

[ 0.          0.          0.         ... -0.0593754  -0.06029727
 -0.06811669] 22050


 24%|███████████████████▌                                                             | 72/299 [03:29<12:02,  3.18s/it]

[ 0.15286843  0.22476168  0.19892806 ... -0.01032892 -0.01059519
 -0.01229354] 22050


 24%|███████████████████▊                                                             | 73/299 [03:32<11:54,  3.16s/it]

[0.01386719 0.02011131 0.01776993 ... 0.00524451 0.00579907 0.        ] 22050


 25%|████████████████████                                                             | 74/299 [03:35<11:20,  3.02s/it]

[-0.00679656 -0.01003796 -0.00873371 ... -0.02517475 -0.03054456
  0.        ] 22050


 25%|████████████████████▎                                                            | 75/299 [03:38<11:28,  3.07s/it]

[ 0.00579983  0.00852321  0.00752403 ... -0.00082801 -0.00068914
 -0.00070964] 22050


 25%|████████████████████▌                                                            | 76/299 [03:41<11:27,  3.08s/it]

[-0.00053421 -0.00082033 -0.00076593 ... -0.00522986 -0.00525398
 -0.00585139] 22050


 26%|████████████████████▊                                                            | 77/299 [03:45<11:45,  3.18s/it]

[-2.8764509e-05 -3.0061437e-05 -2.9183469e-05 ... -1.0795601e-03
 -5.5044401e-04  0.0000000e+00] 22050


 26%|█████████████████████▏                                                           | 78/299 [03:46<09:50,  2.67s/it]

[-7.8413684e-08  9.5552173e-07  1.9807621e-06 ... -3.6296784e-03
 -2.0876050e-03  0.0000000e+00] 22050


 26%|█████████████████████▍                                                           | 79/299 [03:48<08:59,  2.45s/it]

[1.8421345e-06 3.9703418e-06 4.0728492e-06 ... 1.1935446e-03 6.8373588e-04
 0.0000000e+00] 22050


 27%|█████████████████████▋                                                           | 80/299 [03:49<07:28,  2.05s/it]

[-2.2084580e-06 -5.9585232e-06 -8.7529661e-06 ... -3.4101740e-02
 -2.1929748e-02 -1.0731890e-02] 22050


 27%|█████████████████████▉                                                           | 81/299 [03:51<07:25,  2.04s/it]

[-5.8840362e-07  2.2181875e-06  5.4235775e-06 ...  3.1400897e-02
  1.6541665e-02  0.0000000e+00] 22050


 27%|██████████████████████▏                                                          | 82/299 [03:53<06:50,  1.89s/it]

[ 5.9769508e-07  8.8926954e-06  2.1092692e-05 ... -1.6348783e-02
 -8.8511044e-03  0.0000000e+00] 22050


 28%|██████████████████████▍                                                          | 83/299 [03:54<06:11,  1.72s/it]

[ 0.00772112  0.01154974  0.01025985 ... -0.00331298 -0.00319685
 -0.0037348 ] 22050


 28%|██████████████████████▊                                                          | 84/299 [03:58<08:18,  2.32s/it]

[0.28596535 0.3158219  0.33115914 ... 0.08994886 0.05179574 0.        ] 22050


 28%|███████████████████████                                                          | 85/299 [04:08<16:10,  4.54s/it]

[-0.27563092 -0.30399603 -0.31818    ...  0.00215952  0.00126481
  0.        ] 22050


 29%|███████████████████████▎                                                         | 86/299 [04:17<21:42,  6.11s/it]

[0.03946353 0.04340422 0.04541007 ... 0.4538223  0.29210246 0.14312147] 22050


 29%|███████████████████████▌                                                         | 87/299 [04:34<32:54,  9.31s/it]

[-0.3726952  -0.41175988 -0.43205068 ... -0.15957749 -0.10276388
 -0.05036703] 22050


 29%|███████████████████████▊                                                         | 88/299 [04:43<31:47,  9.04s/it]

[-0.2810858  -0.31157294 -0.32829928 ... -0.1266794  -0.08168591
 -0.04014152] 22050


 30%|████████████████████████                                                         | 89/299 [04:51<30:39,  8.76s/it]

[-0.07494406 -0.10856454 -0.09363515 ...  0.01878147  0.01818044
  0.01986458] 22050


 30%|████████████████████████▍                                                        | 90/299 [04:55<26:21,  7.57s/it]

[ 0.03124345  0.04578807  0.04021889 ... -0.01389698 -0.01351108
 -0.01445538] 22050


 30%|████████████████████████▋                                                        | 91/299 [04:59<22:05,  6.37s/it]

[-0.02912769 -0.04266582 -0.03835926 ... -0.07225096 -0.07003564
 -0.07565343] 22050


 31%|████████████████████████▉                                                        | 92/299 [05:02<18:53,  5.48s/it]

[ 0.00182807  0.00246826  0.00192033 ... -0.00439787 -0.00413904
 -0.00436127] 22050


 31%|█████████████████████████▏                                                       | 93/299 [05:06<17:01,  4.96s/it]

[-0.06445651 -0.09444108 -0.08404209 ... -0.01689324 -0.01542289
 -0.01585781] 22050


 31%|█████████████████████████▍                                                       | 94/299 [05:10<15:31,  4.55s/it]

[0.06414742 0.09454045 0.08388222 ... 0.24822964 0.24023329 0.2587387 ] 22050


 32%|█████████████████████████▋                                                       | 95/299 [05:13<13:46,  4.05s/it]

[ 0.08259647  0.12127037  0.1070242  ... -0.02367939 -0.02266011
 -0.0243049 ] 22050


 32%|██████████████████████████                                                       | 96/299 [05:16<13:02,  3.86s/it]

[-0.0151329  -0.02294918 -0.0202172  ... -0.04157927 -0.04070212
 -0.04374132] 22050


 32%|██████████████████████████▎                                                      | 97/299 [05:19<11:58,  3.56s/it]

[-0.00485999 -0.00679087 -0.00545568 ...  0.01482467  0.0137242
  0.01388321] 22050


 33%|██████████████████████████▌                                                      | 98/299 [05:22<11:16,  3.37s/it]

[0.13323113 0.19474407 0.17157386 ... 0.08486681 0.08216646 0.08880045] 22050


 33%|██████████████████████████▊                                                      | 99/299 [05:25<10:33,  3.17s/it]

[0.02923446 0.04403316 0.04038239 ... 0.07650845 0.07465485 0.08051185] 22050


 33%|██████████████████████████▊                                                     | 100/299 [05:28<10:24,  3.14s/it]

[ 0.03005545  0.04300415  0.03662321 ... -0.0114797  -0.01104879
 -0.01202029] 22050


 34%|███████████████████████████                                                     | 101/299 [05:30<09:56,  3.01s/it]

[6.0555729e-05 7.3114075e-05 8.1377519e-05 ... 8.7227272e-03 4.8832153e-03
 0.0000000e+00] 22050


 34%|███████████████████████████▎                                                    | 102/299 [05:32<08:19,  2.54s/it]

[ 1.3562662e-06  9.4506561e-07 -8.5865324e-09 ...  3.3021986e-02
  1.8553611e-02  0.0000000e+00] 22050


 34%|███████████████████████████▌                                                    | 103/299 [05:33<06:53,  2.11s/it]

[6.1053885e-05 7.3011215e-05 8.0253209e-05 ... 5.3349137e-03 2.8286560e-03
 0.0000000e+00] 22050


 35%|███████████████████████████▊                                                    | 104/299 [05:36<07:34,  2.33s/it]

[ 6.7988680e-07 -5.5855821e-06 -1.5208361e-05 ...  1.3006850e-02
  6.8495930e-03  0.0000000e+00] 22050


 35%|████████████████████████████                                                    | 105/299 [05:37<06:52,  2.13s/it]

[-8.7546437e-07 -1.6883479e-06 -2.0232412e-06 ...  8.1363264e-03
  4.2472398e-03  0.0000000e+00] 22050


 35%|████████████████████████████▎                                                   | 106/299 [05:39<05:58,  1.86s/it]

[-2.2965232e-06  1.4332079e-05  3.7568196e-05 ... -5.9282253e-03
 -3.7157908e-03  0.0000000e+00] 22050


 36%|████████████████████████████▋                                                   | 107/299 [05:39<04:52,  1.52s/it]

[-0.05889978 -0.08439805 -0.07164766 ... -0.03685347 -0.03530446
 -0.03779959] 22050


 36%|████████████████████████████▉                                                   | 108/299 [05:42<06:08,  1.93s/it]

[-0.00703423 -0.01040334 -0.00912582 ...  0.08334509  0.08262308
  0.08995433] 22050


 36%|█████████████████████████████▏                                                  | 109/299 [05:45<06:53,  2.18s/it]

[0.00841071 0.0121377  0.01047836 ... 0.01875647 0.01999779 0.        ] 22050


 37%|█████████████████████████████▍                                                  | 110/299 [05:48<07:44,  2.46s/it]

[-0.00168595 -0.00258133 -0.00231386 ...  0.00077115  0.0006065
  0.00061912] 22050


 37%|█████████████████████████████▋                                                  | 111/299 [05:51<08:01,  2.56s/it]

[ 0.00833424  0.01223366  0.01093073 ... -0.02901728 -0.02817109
 -0.03024289] 22050


 37%|█████████████████████████████▉                                                  | 112/299 [05:54<08:09,  2.62s/it]

[ 0.          0.          0.         ... -0.09031238 -0.08735766
 -0.09306031] 22050


 38%|██████████████████████████████▏                                                 | 113/299 [05:57<08:32,  2.75s/it]

[0.         0.         0.         ... 0.00044038 0.00028749 0.00024897] 22050


 38%|██████████████████████████████▌                                                 | 114/299 [06:00<09:14,  3.00s/it]

[0.         0.         0.         ... 0.25428715 0.24422075 0.26595703] 22050


 38%|██████████████████████████████▊                                                 | 115/299 [06:04<09:30,  3.10s/it]

[ 0.          0.          0.         ... -0.18821347 -0.18663183
 -0.2047519 ] 22050


 39%|███████████████████████████████                                                 | 116/299 [06:09<11:43,  3.85s/it]

[0.         0.         0.         ... 0.63282675 0.60743105 0.6499869 ] 22050


 39%|███████████████████████████████▎                                                | 117/299 [06:13<11:27,  3.78s/it]

[ 0.          0.          0.         ... -0.15600103 -0.14905778
 -0.15698275] 22050


 39%|███████████████████████████████▌                                                | 118/299 [06:16<11:01,  3.65s/it]

[ 0.          0.          0.         ... -0.1499482  -0.14536801
 -0.15866049] 22050


 40%|███████████████████████████████▊                                                | 119/299 [06:19<10:19,  3.44s/it]

[ 0.          0.          0.         ... -0.03819335 -0.03791534
 -0.04188127] 22050


 40%|████████████████████████████████                                                | 120/299 [06:22<09:55,  3.33s/it]

[ 0.          0.          0.         ... -0.06268332 -0.06022708
 -0.06461953] 22050


 40%|████████████████████████████████▎                                               | 121/299 [06:26<10:13,  3.44s/it]

[ 0.          0.          0.         ... -0.28731927 -0.2788944
 -0.3043653 ] 22050


 41%|████████████████████████████████▋                                               | 122/299 [06:30<10:42,  3.63s/it]

[ 0.          0.          0.         ... -0.12467527 -0.11601477
 -0.12351672] 22050


 41%|████████████████████████████████▉                                               | 123/299 [06:33<10:18,  3.52s/it]

[ 0.          0.          0.         ... -0.3117757  -0.30287907
 -0.32905123] 22050


 41%|█████████████████████████████████▏                                              | 124/299 [06:36<09:52,  3.39s/it]

[ 0.          0.          0.         ... -0.60128844 -0.5866989
 -0.6393383 ] 22050


 42%|█████████████████████████████████▍                                              | 125/299 [06:40<09:44,  3.36s/it]

[ 0.          0.          0.         ... -0.09460735 -0.09186393
 -0.10033422] 22050


 42%|█████████████████████████████████▋                                              | 126/299 [06:42<09:06,  3.16s/it]

[0.         0.         0.         ... 0.06824436 0.06823804 0.07497056] 22050


 42%|█████████████████████████████████▉                                              | 127/299 [06:45<09:05,  3.17s/it]

[ 0.          0.          0.         ... -0.02098945 -0.01939385
 -0.01919075] 22050


 43%|██████████████████████████████████▏                                             | 128/299 [06:48<08:39,  3.04s/it]

[0.         0.         0.         ... 0.0570341  0.05582925 0.0643122 ] 22050


 43%|██████████████████████████████████▌                                             | 129/299 [06:52<09:10,  3.24s/it]

[0.         0.         0.         ... 0.10997557 0.11245404 0.13821203] 22050


 43%|██████████████████████████████████▊                                             | 130/299 [06:56<09:50,  3.50s/it]

[ 0.          0.          0.         ... -0.27762765 -0.265448
 -0.2814702 ] 22050


 44%|███████████████████████████████████                                             | 131/299 [06:59<09:45,  3.49s/it]

[0.         0.         0.         ... 0.65125763 0.62605083 0.67070335] 22050


 44%|███████████████████████████████████▎                                            | 132/299 [07:03<09:43,  3.50s/it]

[ 0.          0.          0.         ... -0.00710362  0.01155034
  0.03047679] 22050


 44%|███████████████████████████████████▌                                            | 133/299 [07:08<10:31,  3.80s/it]

[ 0.          0.          0.         ... -0.04220781 -0.0425578
 -0.04848582] 22050


 45%|███████████████████████████████████▊                                            | 134/299 [07:10<09:25,  3.42s/it]

[ 0.          0.          0.         ... -0.01046014 -0.00814273
 -0.0058492 ] 22050


 45%|████████████████████████████████████                                            | 135/299 [07:13<08:35,  3.14s/it]

[0.         0.         0.         ... 0.06659431 0.06493407 0.07325058] 22050


 45%|████████████████████████████████████▍                                           | 136/299 [07:15<07:56,  2.93s/it]

[ 0.          0.          0.         ... -0.09697435 -0.09404793
 -0.1009122 ] 22050


 46%|████████████████████████████████████▋                                           | 137/299 [07:19<08:32,  3.17s/it]

[0.         0.         0.         ... 0.04830315 0.04316428 0.04473874] 22050


 46%|████████████████████████████████████▉                                           | 138/299 [07:22<08:29,  3.16s/it]

[0.         0.         0.         ... 0.12839343 0.12455406 0.13296343] 22050


 46%|█████████████████████████████████████▏                                          | 139/299 [07:25<08:49,  3.31s/it]

[ 0.          0.          0.         ... -0.10614821 -0.10306031
 -0.11080159] 22050


 47%|█████████████████████████████████████▍                                          | 140/299 [07:28<08:02,  3.03s/it]

[ 0.          0.          0.         ... -0.04283782 -0.04240255
 -0.0454677 ] 22050


 47%|█████████████████████████████████████▋                                          | 141/299 [07:31<07:43,  2.93s/it]

[0.         0.         0.         ... 0.08306429 0.08193642 0.09004958] 22050


 47%|█████████████████████████████████████▉                                          | 142/299 [07:33<07:16,  2.78s/it]

[0.         0.         0.         ... 0.05440215 0.05421929 0.06178407] 22050


 48%|██████████████████████████████████████▎                                         | 143/299 [07:36<07:21,  2.83s/it]

[ 0.          0.          0.         ... -0.14653698 -0.14106536
 -0.14908496] 22050


 48%|██████████████████████████████████████▌                                         | 144/299 [07:39<07:10,  2.78s/it]

[ 0.          0.          0.         ... -0.2712792  -0.2602289
 -0.27644926] 22050


 48%|██████████████████████████████████████▊                                         | 145/299 [07:43<08:05,  3.15s/it]

[0.         0.         0.         ... 0.0585855  0.05834712 0.06446683] 22050


 49%|███████████████████████████████████████                                         | 146/299 [07:46<08:02,  3.15s/it]

[0.         0.         0.         ... 0.09014577 0.08732708 0.09365366] 22050


 49%|███████████████████████████████████████▎                                        | 147/299 [07:50<08:30,  3.36s/it]

[0.         0.         0.         ... 0.1488721  0.14210069 0.15414882] 22050


 49%|███████████████████████████████████████▌                                        | 148/299 [07:54<09:05,  3.61s/it]

[ 0.          0.          0.         ... -0.01634077 -0.01284211
 -0.00887103] 22050


 50%|███████████████████████████████████████▊                                        | 149/299 [07:59<09:49,  3.93s/it]

[0.         0.         0.         ... 0.03140324 0.02938446 0.03127927] 22050


 50%|████████████████████████████████████████▏                                       | 150/299 [08:02<09:35,  3.86s/it]

[0.         0.         0.         ... 0.06877434 0.06657933 0.07092424] 22050


 51%|████████████████████████████████████████▍                                       | 151/299 [08:06<09:40,  3.92s/it]

[0.         0.         0.         ... 0.04315259 0.04266706 0.04637334] 22050


 51%|████████████████████████████████████████▋                                       | 152/299 [08:10<09:29,  3.88s/it]

[0.         0.         0.         ... 0.13846196 0.13753016 0.15601401] 22050


 51%|████████████████████████████████████████▉                                       | 153/299 [08:16<10:39,  4.38s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 52%|█████████████████████████████████████████▏                                      | 154/299 [08:19<09:38,  3.99s/it]

[ 0.          0.          0.         ... -0.853009   -0.826511
 -0.89554524] 22050


 52%|█████████████████████████████████████████▍                                      | 155/299 [08:22<08:53,  3.71s/it]

[0.         0.         0.         ... 0.7048063  0.68563855 0.7389971 ] 22050


 52%|█████████████████████████████████████████▋                                      | 156/299 [08:25<08:13,  3.45s/it]

[ 0.          0.          0.         ... -0.0597242  -0.05913943
 -0.06880321] 22050


 53%|██████████████████████████████████████████                                      | 157/299 [08:28<07:56,  3.35s/it]

[ 0.          0.          0.         ... -0.04255615 -0.03158521
 -0.034418  ] 22050


 53%|██████████████████████████████████████████▎                                     | 158/299 [08:31<07:48,  3.32s/it]

[ 0.          0.          0.         ... -0.12110092 -0.1101577
 -0.1219567 ] 22050


 53%|██████████████████████████████████████████▌                                     | 159/299 [08:34<07:45,  3.33s/it]

[0.         0.         0.         ... 0.03321154 0.03474576 0.03959534] 22050


 54%|██████████████████████████████████████████▊                                     | 160/299 [08:37<07:36,  3.28s/it]

[ 0.          0.          0.         ... -0.00967131 -0.0093653
 -0.01004385] 22050


 54%|███████████████████████████████████████████                                     | 161/299 [08:41<07:33,  3.29s/it]

[0.         0.         0.         ... 0.00452353 0.00422161 0.00407965] 22050


 54%|███████████████████████████████████████████▎                                    | 162/299 [08:44<07:33,  3.31s/it]

[0.         0.         0.         ... 0.00405493 0.0042079  0.00498438] 22050


 55%|███████████████████████████████████████████▌                                    | 163/299 [08:48<07:41,  3.39s/it]

[ 0.          0.          0.         ... -0.06538848 -0.0640373
 -0.07016253] 22050


 55%|███████████████████████████████████████████▉                                    | 164/299 [08:51<07:37,  3.39s/it]

[ 0.          0.          0.         ... -0.06714011 -0.06459182
 -0.07058822] 22050


 55%|████████████████████████████████████████████▏                                   | 165/299 [08:54<07:27,  3.34s/it]

[ 0.          0.          0.         ... -0.0976808  -0.09131095
 -0.1009459 ] 22050


 56%|████████████████████████████████████████████▍                                   | 166/299 [08:57<07:05,  3.20s/it]

[ 0.          0.          0.         ... -0.24246328 -0.23364931
 -0.2513686 ] 22050


 56%|████████████████████████████████████████████▋                                   | 167/299 [09:01<07:12,  3.28s/it]

[ 0.          0.          0.         ... -0.07716538 -0.07356218
 -0.08140326] 22050


 56%|████████████████████████████████████████████▉                                   | 168/299 [09:04<06:57,  3.19s/it]

[ 0.          0.          0.         ... -0.12482095 -0.11627863
 -0.12246422] 22050


 57%|█████████████████████████████████████████████▏                                  | 169/299 [09:07<06:56,  3.21s/it]

[ 0.          0.          0.         ... -0.01074216 -0.01034736
 -0.01125017] 22050


 57%|█████████████████████████████████████████████▍                                  | 170/299 [09:10<06:35,  3.07s/it]

[0.         0.         0.         ... 0.24655572 0.23584485 0.24982773] 22050


 57%|█████████████████████████████████████████████▊                                  | 171/299 [09:13<06:27,  3.03s/it]

[0.         0.         0.         ... 0.12076917 0.1194012  0.12977952] 22050


 58%|██████████████████████████████████████████████                                  | 172/299 [09:15<06:19,  2.99s/it]

[0.         0.         0.         ... 0.00541603 0.00534779 0.00361776] 22050


 58%|██████████████████████████████████████████████▎                                 | 173/299 [09:18<06:18,  3.00s/it]

[0.         0.         0.         ... 0.00590403 0.00539305 0.00577536] 22050


 58%|██████████████████████████████████████████████▌                                 | 174/299 [09:21<06:07,  2.94s/it]

[ 0.          0.          0.         ... -0.1507879  -0.14893688
 -0.17197357] 22050


 59%|██████████████████████████████████████████████▊                                 | 175/299 [09:24<06:07,  2.97s/it]

[0.         0.         0.         ... 0.04399489 0.04110481 0.0455402 ] 22050


 59%|███████████████████████████████████████████████                                 | 176/299 [09:28<06:28,  3.16s/it]

[ 0.          0.          0.         ... -0.03041141 -0.03024904
 -0.03383819] 22050


 59%|███████████████████████████████████████████████▎                                | 177/299 [09:32<06:57,  3.42s/it]

[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 3.49719558e-05
 1.04438295e-04 4.18424490e-04] 22050


 60%|███████████████████████████████████████████████▋                                | 178/299 [09:35<06:51,  3.40s/it]

[0.08209334 0.12027321 0.10592982 ... 0.09523189 0.09189781 0.09868933] 22050


 60%|███████████████████████████████████████████████▉                                | 179/299 [09:38<06:37,  3.31s/it]

[ 0.00025519  0.00028764  0.00014868 ... -0.00348902 -0.00338399
 -0.0036069 ] 22050


 60%|████████████████████████████████████████████████▏                               | 180/299 [09:41<06:14,  3.15s/it]

[-0.01997385 -0.02963021 -0.02664766 ... -0.02849923 -0.02836062
 -0.03160037] 22050


 61%|████████████████████████████████████████████████▍                               | 181/299 [09:44<06:02,  3.07s/it]

[ 0.          0.          0.         ... -0.5391371  -0.52193433
 -0.5663463 ] 22050


 61%|████████████████████████████████████████████████▋                               | 182/299 [09:47<05:38,  2.89s/it]

[0.         0.         0.         ... 0.03783033 0.03612902 0.03943321] 22050


 61%|████████████████████████████████████████████████▉                               | 183/299 [09:50<05:42,  2.95s/it]

[0.         0.         0.         ... 0.04257868 0.0448944  0.05588475] 22050


 62%|█████████████████████████████████████████████████▏                              | 184/299 [09:53<05:39,  2.95s/it]

[0.         0.         0.         ... 0.05401823 0.05287353 0.05755837] 22050


 62%|█████████████████████████████████████████████████▍                              | 185/299 [09:56<05:46,  3.04s/it]

[0.         0.         0.         ... 0.09213886 0.09398716 0.10088132] 22050


 62%|█████████████████████████████████████████████████▊                              | 186/299 [09:58<05:22,  2.86s/it]

[0.         0.         0.         ... 0.11685472 0.1111599  0.11944976] 22050


 63%|██████████████████████████████████████████████████                              | 187/299 [10:01<05:23,  2.89s/it]

[0.         0.         0.         ... 0.4792076  0.45526347 0.49092004] 22050


 63%|██████████████████████████████████████████████████▎                             | 188/299 [10:04<05:17,  2.86s/it]

[ 0.          0.          0.         ... -0.01120818 -0.00803506
 -0.01138652] 22050


 63%|██████████████████████████████████████████████████▌                             | 189/299 [10:07<05:26,  2.97s/it]

[ 0.          0.          0.         ... -0.05364962 -0.05210137
 -0.055831  ] 22050


 64%|██████████████████████████████████████████████████▊                             | 190/299 [10:10<05:18,  2.92s/it]

[0.         0.         0.         ... 0.87999165 0.8438236  0.9057113 ] 22050


 64%|███████████████████████████████████████████████████                             | 191/299 [10:13<05:29,  3.05s/it]

[0.         0.         0.         ... 0.22386    0.21816497 0.23659104] 22050


 64%|███████████████████████████████████████████████████▎                            | 192/299 [10:17<05:52,  3.29s/it]

[0.        0.        0.        ... 0.9459605 0.9187443 0.9850489] 22050


 65%|███████████████████████████████████████████████████▋                            | 193/299 [10:21<06:05,  3.45s/it]

[ 0.          0.          0.         ... -0.03106961 -0.02864614
 -0.03651939] 22050


 65%|███████████████████████████████████████████████████▉                            | 194/299 [10:25<06:13,  3.56s/it]

[ 0.          0.          0.         ... -0.09009068 -0.09058654
 -0.10142617] 22050


 65%|████████████████████████████████████████████████████▏                           | 195/299 [10:27<05:39,  3.26s/it]

[ 0.          0.          0.         ... -0.953986   -0.92493206
 -0.98153687] 22050


 66%|████████████████████████████████████████████████████▍                           | 196/299 [10:30<05:24,  3.15s/it]

[ 0.          0.          0.         ... -0.15020148 -0.14647253
 -0.15748379] 22050


 66%|████████████████████████████████████████████████████▋                           | 197/299 [10:33<05:16,  3.11s/it]

[ 0.          0.          0.         ... -0.12514465 -0.12138256
 -0.12777631] 22050


 66%|████████████████████████████████████████████████████▉                           | 198/299 [10:36<05:02,  3.00s/it]

[ 0.          0.          0.         ... -0.0088842  -0.00718911
 -0.00901421] 22050


 67%|█████████████████████████████████████████████████████▏                          | 199/299 [10:39<05:05,  3.06s/it]

[0.         0.         0.         ... 0.08539807 0.08473286 0.09463313] 22050


 67%|█████████████████████████████████████████████████████▌                          | 200/299 [10:42<05:07,  3.11s/it]

[0.04514384 0.06601427 0.05779665 ... 0.02462521 0.02394859 0.02566808] 22050


 67%|█████████████████████████████████████████████████████▊                          | 201/299 [10:46<05:11,  3.18s/it]

[ 0.01947135  0.02846876  0.02506434 ... -0.033544   -0.03245725
 -0.03468243] 22050


 68%|██████████████████████████████████████████████████████                          | 202/299 [10:49<05:19,  3.30s/it]

[0.12175424 0.17824209 0.15657128 ... 0.11341876 0.11023723 0.11999816] 22050


 68%|██████████████████████████████████████████████████████▎                         | 203/299 [10:53<05:11,  3.24s/it]

[0.00631607 0.00816058 0.00610981 ... 0.09044091 0.08813905 0.09586868] 22050


 68%|██████████████████████████████████████████████████████▌                         | 204/299 [10:56<05:26,  3.44s/it]

[-0.15628962 -0.22895335 -0.20168705 ... -0.03173079 -0.03226447
 -0.03650894] 22050


 69%|██████████████████████████████████████████████████████▊                         | 205/299 [11:00<05:13,  3.33s/it]

[0.1853947  0.27131873 0.23839961 ... 0.0437646  0.04377886 0.04920494] 22050


 69%|███████████████████████████████████████████████████████                         | 206/299 [11:03<05:08,  3.32s/it]

[0.18107037 0.26462144 0.23234265 ... 0.32034877 0.30916995 0.3323549 ] 22050


 69%|███████████████████████████████████████████████████████▍                        | 207/299 [11:05<04:47,  3.13s/it]

[-0.02087486 -0.03028057 -0.02663353 ...  0.0413494   0.03994204
  0.0426349 ] 22050


 70%|███████████████████████████████████████████████████████▋                        | 208/299 [11:09<04:46,  3.15s/it]

[ 0.03595075  0.04989659  0.04024421 ... -0.24192847 -0.23514697
 -0.2543003 ] 22050


 70%|███████████████████████████████████████████████████████▉                        | 209/299 [11:12<04:47,  3.19s/it]

[ 0.06172559  0.0904598   0.07956354 ... -0.1636615  -0.15869726
 -0.17139705] 22050


 70%|████████████████████████████████████████████████████████▏                       | 210/299 [11:15<04:35,  3.09s/it]

[-0.03135544 -0.04578738 -0.04026452 ...  0.04830543  0.04669622
  0.05010771] 22050


 71%|████████████████████████████████████████████████████████▍                       | 211/299 [11:18<04:27,  3.04s/it]

[-0.01032383 -0.01453805 -0.01170636 ...  0.06987031  0.06842768
  0.07429894] 22050


 71%|████████████████████████████████████████████████████████▋                       | 212/299 [11:20<04:12,  2.90s/it]

[ 0.07066288  0.10368585  0.09162885 ... -0.0461418  -0.04419601
 -0.0465932 ] 22050


 71%|████████████████████████████████████████████████████████▉                       | 213/299 [11:23<04:04,  2.84s/it]

[-0.10510142 -0.15434119 -0.13665253 ...  0.00354332  0.00412865
  0.00499887] 22050


 72%|█████████████████████████████████████████████████████████▎                      | 214/299 [11:26<04:00,  2.83s/it]

[-0.03397305 -0.04996506 -0.04397296 ...  0.03616295  0.03442479
  0.03606641] 22050


 72%|█████████████████████████████████████████████████████████▌                      | 215/299 [11:28<03:48,  2.72s/it]

[0.00048343 0.00073013 0.00074828 ... 0.04594715 0.04402352 0.0471474 ] 22050


 72%|█████████████████████████████████████████████████████████▊                      | 216/299 [11:31<03:37,  2.62s/it]

[ 0.224885    0.32932156  0.2899627  ... -0.05834039 -0.05618492
 -0.06026815] 22050


 73%|██████████████████████████████████████████████████████████                      | 217/299 [11:33<03:34,  2.62s/it]

[-0.07712042 -0.1130089  -0.09989832 ...  0.04327109  0.0418635
  0.04561923] 22050


 73%|██████████████████████████████████████████████████████████▎                     | 218/299 [11:36<03:44,  2.77s/it]

[-0.03549059 -0.05269979 -0.04721371 ... -0.13843057 -0.13402462
 -0.14437081] 22050


 73%|██████████████████████████████████████████████████████████▌                     | 219/299 [11:39<03:37,  2.72s/it]

[0.02330435 0.03429922 0.03047918 ... 0.02959513 0.02840756 0.03028148] 22050


 74%|██████████████████████████████████████████████████████████▊                     | 220/299 [11:42<03:32,  2.69s/it]

[-0.04389535 -0.0649181  -0.05787742 ...  0.15056932  0.14504048
  0.15519336] 22050


 74%|███████████████████████████████████████████████████████████▏                    | 221/299 [11:44<03:26,  2.65s/it]

[0.         0.         0.         ... 0.06869866 0.06484786 0.07572741] 22050


 74%|███████████████████████████████████████████████████████████▍                    | 222/299 [11:48<03:42,  2.89s/it]

[0.         0.         0.         ... 0.06053632 0.07971119 0.08661738] 22050


 75%|███████████████████████████████████████████████████████████▋                    | 223/299 [11:50<03:35,  2.83s/it]

[0.         0.         0.         ... 0.19320235 0.17706984 0.18313724] 22050


 75%|███████████████████████████████████████████████████████████▉                    | 224/299 [11:55<04:02,  3.24s/it]

[0.         0.         0.         ... 0.08155401 0.0827576  0.08970284] 22050


 75%|████████████████████████████████████████████████████████████▏                   | 225/299 [11:57<03:52,  3.14s/it]

[0.         0.         0.         ... 0.38486943 0.3681868  0.39275822] 22050


 76%|████████████████████████████████████████████████████████████▍                   | 226/299 [12:01<03:55,  3.22s/it]

[0.         0.         0.         ... 0.10772336 0.10574576 0.10623769] 22050


 76%|████████████████████████████████████████████████████████████▋                   | 227/299 [12:06<04:37,  3.86s/it]

[0.         0.         0.         ... 0.04214108 0.03715343 0.03800107] 22050


 76%|█████████████████████████████████████████████████████████████                   | 228/299 [12:10<04:34,  3.86s/it]

[0.         0.         0.         ... 0.15521227 0.14677481 0.15593003] 22050


 77%|█████████████████████████████████████████████████████████████▎                  | 229/299 [12:15<05:02,  4.33s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 77%|█████████████████████████████████████████████████████████████▌                  | 230/299 [12:19<04:51,  4.23s/it]

[0.         0.         0.         ... 0.08151314 0.07713719 0.09152706] 22050


 77%|█████████████████████████████████████████████████████████████▊                  | 231/299 [12:23<04:33,  4.01s/it]

[ 0.          0.          0.         ... -0.3917424  -0.37110776
 -0.3991456 ] 22050


 78%|██████████████████████████████████████████████████████████████                  | 232/299 [12:27<04:29,  4.03s/it]

[0.         0.         0.         ... 0.08050891 0.07564239 0.07922343] 22050


 78%|██████████████████████████████████████████████████████████████▎                 | 233/299 [12:32<04:39,  4.24s/it]

[ 0.          0.          0.         ... -0.5759593  -0.5520702
 -0.59178233] 22050


 78%|██████████████████████████████████████████████████████████████▌                 | 234/299 [12:36<04:30,  4.17s/it]

[0.         0.         0.         ... 0.40601084 0.39382565 0.4227301 ] 22050


 79%|██████████████████████████████████████████████████████████████▉                 | 235/299 [12:39<04:17,  4.02s/it]

[0.         0.         0.         ... 0.6122817  0.58529973 0.6405715 ] 22050


 79%|███████████████████████████████████████████████████████████████▏                | 236/299 [12:42<03:53,  3.70s/it]

[0.         0.         0.         ... 0.2661814  0.25699428 0.26891932] 22050


 79%|███████████████████████████████████████████████████████████████▍                | 237/299 [12:45<03:34,  3.47s/it]

[0.         0.         0.         ... 0.16818021 0.16085267 0.17989126] 22050


 80%|███████████████████████████████████████████████████████████████▋                | 238/299 [12:49<03:33,  3.50s/it]

[ 0.          0.          0.         ... -0.05958529 -0.05423374
 -0.05786638] 22050


 80%|███████████████████████████████████████████████████████████████▉                | 239/299 [12:53<03:42,  3.70s/it]

[0.         0.         0.         ... 0.541714   0.5261556  0.56970155] 22050


 80%|████████████████████████████████████████████████████████████████▏               | 240/299 [12:57<03:46,  3.84s/it]

[0.         0.         0.         ... 0.15760067 0.14828913 0.15459237] 22050


 81%|████████████████████████████████████████████████████████████████▍               | 241/299 [13:01<03:37,  3.74s/it]

[ 0.          0.          0.         ... -0.10551623 -0.09428532
 -0.10726903] 22050


 81%|████████████████████████████████████████████████████████████████▋               | 242/299 [13:05<03:45,  3.96s/it]

[ 0.          0.          0.         ... -0.1540732  -0.14363897
 -0.16802943] 22050


 81%|█████████████████████████████████████████████████████████████████               | 243/299 [13:10<03:52,  4.16s/it]

[0.         0.         0.         ... 0.08215027 0.07461631 0.07744326] 22050


 82%|█████████████████████████████████████████████████████████████████▎              | 244/299 [13:14<03:47,  4.14s/it]

[ 0.          0.          0.         ... -0.10069733 -0.0970569
 -0.10444666] 22050


 82%|█████████████████████████████████████████████████████████████████▌              | 245/299 [13:19<04:03,  4.51s/it]

[ 0.          0.          0.         ... -0.0056017  -0.00158101
 -0.00499161] 22050


 82%|█████████████████████████████████████████████████████████████████▊              | 246/299 [13:23<03:45,  4.26s/it]

[ 0.          0.          0.         ... -0.04706489 -0.05189802
 -0.05370488] 22050


 83%|██████████████████████████████████████████████████████████████████              | 247/299 [13:26<03:23,  3.91s/it]

[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  7.0181406e-05
 -1.1087143e-04 -3.7962562e-04] 22050


 83%|██████████████████████████████████████████████████████████████████▎             | 248/299 [13:29<03:09,  3.71s/it]

[6.0634571e-05 5.8885256e-05 4.5460369e-05 ... 1.8835057e-03 1.1092690e-03
 0.0000000e+00] 22050


 83%|██████████████████████████████████████████████████████████████████▌             | 249/299 [13:31<02:39,  3.19s/it]

[-2.4712881e-06 -5.1638103e-06 -6.9168277e-06 ... -2.6756365e-04
 -3.7583763e-05  0.0000000e+00] 22050


 84%|██████████████████████████████████████████████████████████████████▉             | 250/299 [13:33<02:20,  2.87s/it]

[3.0095798e-05 3.6245452e-05 4.1038627e-05 ... 1.8093728e-02 9.8271910e-03
 0.0000000e+00] 22050


 84%|███████████████████████████████████████████████████████████████████▏            | 251/299 [13:36<02:20,  2.92s/it]

[ 0.00052289  0.00053874  0.00046727 ... -0.01250761 -0.00773672
  0.        ] 22050


 84%|███████████████████████████████████████████████████████████████████▍            | 252/299 [13:38<02:00,  2.56s/it]

[-7.9725692e-07 -5.1435914e-06 -1.1148565e-05 ...  8.1616104e-02
  5.0180554e-02  0.0000000e+00] 22050


 85%|███████████████████████████████████████████████████████████████████▋            | 253/299 [13:40<01:43,  2.25s/it]

[-8.4280538e-07 -2.8361271e-06 -4.4394942e-06 ... -2.2870742e-03
 -1.5083579e-03 -7.5765629e-04] 22050


 85%|███████████████████████████████████████████████████████████████████▉            | 254/299 [13:42<01:43,  2.30s/it]

[0.04097231 0.06046491 0.05393831 ... 0.06758201 0.0656415  0.07101809] 22050


 85%|████████████████████████████████████████████████████████████████████▏           | 255/299 [13:46<02:06,  2.87s/it]

[0.14633565 0.21431813 0.1891213  ... 0.06799984 0.06604503 0.07172802] 22050


 86%|████████████████████████████████████████████████████████████████████▍           | 256/299 [13:49<02:02,  2.86s/it]

[-0.21283041 -0.31201988 -0.27520728 ...  0.09969999  0.09652264
  0.10397127] 22050


 86%|████████████████████████████████████████████████████████████████████▊           | 257/299 [13:52<01:59,  2.84s/it]

[ 0.24943277  0.36582845  0.32237023 ... -0.12260514 -0.11850586
 -0.12716296] 22050


 86%|█████████████████████████████████████████████████████████████████████           | 258/299 [13:55<01:54,  2.80s/it]

[ 0.00150154  0.00224524  0.00197812 ... -0.00079957 -0.0008043
 -0.00093849] 22050


 87%|█████████████████████████████████████████████████████████████████████▎          | 259/299 [13:57<01:49,  2.75s/it]

[-0.10364083 -0.15188637 -0.13410126 ... -0.00882632 -0.00849731
 -0.00917868] 22050


 87%|█████████████████████████████████████████████████████████████████████▌          | 260/299 [14:00<01:49,  2.81s/it]

[-1.4861421e-04 -1.3037902e-04  2.5037663e-05 ...  1.4510831e-03
  1.3408809e-03  1.3899795e-03] 22050


 87%|█████████████████████████████████████████████████████████████████████▊          | 261/299 [14:04<02:03,  3.24s/it]

[-0.00583808 -0.00877954 -0.00792479 ...  0.00369963  0.0036003
  0.00391275] 22050


 88%|██████████████████████████████████████████████████████████████████████          | 262/299 [14:08<02:01,  3.28s/it]

[0.00212975 0.00305085 0.00268819 ... 0.00175668 0.00171111 0.00161446] 22050


 88%|██████████████████████████████████████████████████████████████████████▎         | 263/299 [14:11<01:58,  3.28s/it]

[-2.5228692e-05 -3.4271841e-05 -7.0419483e-05 ... -2.7906429e-04
 -2.4921342e-04 -1.7429724e-04] 22050


 88%|██████████████████████████████████████████████████████████████████████▋         | 264/299 [14:14<01:46,  3.04s/it]

[-0.00123752 -0.00179152 -0.00154062 ...  0.00876638  0.00853806
  0.00904136] 22050


 89%|██████████████████████████████████████████████████████████████████████▉         | 265/299 [14:16<01:40,  2.96s/it]

[ 0.01017988  0.01540918  0.01426247 ... -0.00534863 -0.00529241
 -0.0056529 ] 22050


 89%|███████████████████████████████████████████████████████████████████████▏        | 266/299 [14:20<01:39,  3.02s/it]

[-0.00048234 -0.00067872 -0.00056381 ...  0.00065122  0.00067135
  0.00079721] 22050


 89%|███████████████████████████████████████████████████████████████████████▍        | 267/299 [14:23<01:39,  3.10s/it]

[-0.00702536 -0.01071104 -0.00976045 ...  0.00861656  0.00821532
  0.00830283] 22050


 90%|███████████████████████████████████████████████████████████████████████▋        | 268/299 [14:26<01:40,  3.26s/it]

[ 0.06949438  0.10296931  0.09133144 ... -0.10478183 -0.09335198
 -0.08779476] 22050


 90%|███████████████████████████████████████████████████████████████████████▉        | 269/299 [14:30<01:39,  3.32s/it]

[-0.00247524 -0.00338435 -0.0025635  ...  0.0046447   0.00468008
  0.00582115] 22050


 90%|████████████████████████████████████████████████████████████████████████▏       | 270/299 [14:33<01:29,  3.09s/it]

[0.         0.         0.         ... 0.05332604 0.0519298  0.05410989] 22050


 91%|████████████████████████████████████████████████████████████████████████▌       | 271/299 [14:35<01:21,  2.90s/it]

[0.         0.         0.         ... 0.02862633 0.0279766  0.02985808] 22050


 91%|████████████████████████████████████████████████████████████████████████▊       | 272/299 [14:38<01:22,  3.05s/it]

[ 0.          0.          0.         ... -0.02789779 -0.02794547
 -0.03012433] 22050


 91%|█████████████████████████████████████████████████████████████████████████       | 273/299 [14:42<01:25,  3.28s/it]

[0.         0.         0.         ... 0.38324693 0.37273288 0.40365618] 22050


 92%|█████████████████████████████████████████████████████████████████████████▎      | 274/299 [14:46<01:23,  3.33s/it]

[ 0.          0.          0.         ... -0.1491216  -0.14584248
 -0.1557944 ] 22050


 92%|█████████████████████████████████████████████████████████████████████████▌      | 275/299 [14:48<01:16,  3.18s/it]

[ 0.          0.          0.         ... -0.11750941 -0.11472095
 -0.1250209 ] 22050


 92%|█████████████████████████████████████████████████████████████████████████▊      | 276/299 [14:52<01:13,  3.21s/it]

[ 0.          0.          0.         ... -0.20403463 -0.18978325
 -0.20266981] 22050


 93%|██████████████████████████████████████████████████████████████████████████      | 277/299 [14:55<01:10,  3.22s/it]

[0.         0.         0.         ... 0.02488784 0.02398541 0.02585169] 22050


 93%|██████████████████████████████████████████████████████████████████████████▍     | 278/299 [14:58<01:08,  3.25s/it]

[ 0.          0.          0.         ... -0.04918024 -0.04727224
 -0.05079426] 22050


 93%|██████████████████████████████████████████████████████████████████████████▋     | 279/299 [15:01<01:02,  3.12s/it]

[ 0.          0.          0.         ... -0.02247576 -0.02182411
 -0.02364616] 22050


 94%|██████████████████████████████████████████████████████████████████████████▉     | 280/299 [15:04<00:56,  2.98s/it]

[ 0.          0.          0.         ... -0.00385102 -0.00356616
 -0.00438928] 22050


 94%|███████████████████████████████████████████████████████████████████████████▏    | 281/299 [15:07<00:53,  2.96s/it]

[ 0.          0.          0.         ... -0.01381473 -0.01339422
 -0.01429898] 22050


 94%|███████████████████████████████████████████████████████████████████████████▍    | 282/299 [15:10<00:49,  2.93s/it]

[0.         0.         0.         ... 0.00366578 0.003711   0.0038881 ] 22050


 95%|███████████████████████████████████████████████████████████████████████████▋    | 283/299 [15:12<00:45,  2.86s/it]

[0.         0.         0.         ... 0.05284447 0.05143116 0.05646055] 22050


 95%|███████████████████████████████████████████████████████████████████████████▉    | 284/299 [15:15<00:42,  2.84s/it]

[0.         0.         0.         ... 0.05651337 0.05371975 0.05820636] 22050


 95%|████████████████████████████████████████████████████████████████████████████▎   | 285/299 [15:18<00:39,  2.85s/it]

[0.         0.         0.         ... 0.04609819 0.04592153 0.05157307] 22050


 96%|████████████████████████████████████████████████████████████████████████████▌   | 286/299 [15:21<00:37,  2.88s/it]

[0.         0.         0.         ... 0.00381485 0.00358559 0.00379743] 22050


 96%|████████████████████████████████████████████████████████████████████████████▊   | 287/299 [15:24<00:34,  2.89s/it]

[0.         0.         0.         ... 0.01049323 0.01007894 0.0108813 ] 22050


 96%|█████████████████████████████████████████████████████████████████████████████   | 288/299 [15:27<00:33,  3.01s/it]

[ 0.          0.          0.         ... -0.04439837 -0.04435356
 -0.04795394] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▎  | 289/299 [15:30<00:30,  3.09s/it]

[0.         0.         0.         ... 0.13611339 0.1388976  0.16161406] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▌  | 290/299 [15:33<00:27,  3.09s/it]

[ 0.          0.          0.         ... -0.02621428 -0.02754864
 -0.03301692] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▊  | 291/299 [15:36<00:24,  3.07s/it]

[ 0.          0.          0.         ... -0.14282164 -0.13467892
 -0.1418872 ] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▏ | 292/299 [15:39<00:20,  2.97s/it]

[0.         0.         0.         ... 0.08933409 0.08854256 0.09726086] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▍ | 293/299 [15:42<00:16,  2.82s/it]

[0.         0.         0.         ... 0.16736001 0.16158195 0.17509419] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▋ | 294/299 [15:44<00:13,  2.78s/it]

[ 0.          0.          0.         ... -0.0342821  -0.03772558
 -0.04044783] 22050


 99%|██████████████████████████████████████████████████████████████████████████████▉ | 295/299 [15:47<00:10,  2.73s/it]

[0.         0.         0.         ... 0.09482074 0.09676798 0.11037613] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▏| 296/299 [15:50<00:08,  2.69s/it]

[0.         0.         0.         ... 0.16828157 0.17618534 0.18312804] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▍| 297/299 [15:52<00:05,  2.58s/it]

[ 0.          0.          0.         ... -0.06649059 -0.05748048
 -0.06334422] 22050


100%|███████████████████████████████████████████████████████████████████████████████▋| 298/299 [15:54<00:02,  2.52s/it]

[0.         0.         0.         ... 0.6694105  0.65764457 0.71868986] 22050


100%|████████████████████████████████████████████████████████████████████████████████| 299/299 [15:57<00:00,  2.49s/it]

[ 0.          0.          0.         ... -0.08037883 -0.07979045
 -0.08560699] 22050


done loading train mfcc


  0%|                                                                                           | 0/93 [00:00<?, ?it/s]

[ 0.          0.          0.         ... -0.03819335 -0.03791534
 -0.04188127] 22050


  2%|█▊                                                                                 | 2/93 [00:02<01:54,  1.26s/it]

[ 0.          0.          0.         ... -0.06268332 -0.06022708
 -0.06461953] 22050


  3%|██▋                                                                                | 3/93 [00:05<02:27,  1.64s/it]

[ 0.          0.          0.         ... -0.28731927 -0.2788944
 -0.3043653 ] 22050


  4%|███▌                                                                               | 4/93 [00:07<02:51,  1.93s/it]

[ 0.          0.          0.         ... -0.12467527 -0.11601477
 -0.12351672] 22050


  5%|████▍                                                                              | 5/93 [00:10<03:11,  2.18s/it]

[ 0.          0.          0.         ... -0.3117757  -0.30287907
 -0.32905123] 22050


  6%|█████▎                                                                             | 6/93 [00:12<03:19,  2.29s/it]

[ 0.          0.          0.         ... -0.60128844 -0.5866989
 -0.6393383 ] 22050


  8%|██████▏                                                                            | 7/93 [00:15<03:21,  2.34s/it]

[ 0.          0.          0.         ... -0.09460735 -0.09186393
 -0.10033422] 22050


  9%|███████▏                                                                           | 8/93 [00:18<03:28,  2.45s/it]

[0.         0.         0.         ... 0.06824436 0.06823804 0.07497056] 22050


 10%|████████                                                                           | 9/93 [00:20<03:30,  2.50s/it]

[ 0.          0.          0.         ... -0.15097117 -0.14199436
 -0.15616187] 22050


 11%|████████▊                                                                         | 10/93 [00:23<03:25,  2.47s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 12%|█████████▋                                                                        | 11/93 [00:25<03:23,  2.48s/it]

[0.         0.         0.         ... 0.11905885 0.1190711  0.13462272] 22050


 13%|██████████▌                                                                       | 12/93 [00:28<03:24,  2.52s/it]

[ 0.          0.          0.         ... -0.14376757 -0.14634912
 -0.16929877] 22050


 14%|███████████▍                                                                      | 13/93 [00:30<03:20,  2.50s/it]

[0.        0.        0.        ... 0.2842634 0.2742911 0.2978991] 22050


 15%|████████████▎                                                                     | 14/93 [00:33<03:20,  2.54s/it]

[ 0.          0.          0.         ... -1.0097158  -0.97754306
 -1.0540003 ] 22050


 16%|█████████████▏                                                                    | 15/93 [00:36<03:27,  2.66s/it]

[ 0.          0.          0.         ... -0.5240373  -0.51735884
 -0.5599158 ] 22050


 17%|██████████████                                                                    | 16/93 [00:39<03:36,  2.81s/it]

[ 0.          0.          0.         ... -0.24339022 -0.23302886
 -0.24892566] 22050


 18%|██████████████▉                                                                   | 17/93 [00:41<03:26,  2.72s/it]

[0.         0.         0.         ... 0.07006744 0.06390787 0.06843111] 22050


 19%|███████████████▊                                                                  | 18/93 [00:44<03:27,  2.77s/it]

[0.         0.         0.         ... 0.23463461 0.22792263 0.26713893] 22050


 20%|████████████████▊                                                                 | 19/93 [00:47<03:21,  2.73s/it]

[0.         0.         0.         ... 0.20498481 0.20232959 0.22086047] 22050


 22%|█████████████████▋                                                                | 20/93 [00:50<03:17,  2.71s/it]

[-0.00283933 -0.00401512 -0.00344597 ...  0.0097526   0.01072497
  0.        ] 22050


 23%|██████████████████▌                                                               | 21/93 [00:53<03:26,  2.86s/it]

[-0.02181281 -0.03193489 -0.02826805 ...  0.00575696  0.00659533
  0.        ] 22050


 24%|███████████████████▍                                                              | 22/93 [00:56<03:31,  2.98s/it]

[ 0.00773429  0.01167202  0.01085229 ... -0.00154025 -0.00176283
  0.        ] 22050


 25%|████████████████████▎                                                             | 23/93 [00:59<03:29,  2.99s/it]

[-9.4293209e-04 -1.5129785e-03 -1.3976007e-03 ...  2.1218079e-04
  7.5372486e-07  0.0000000e+00] 22050


 26%|█████████████████████▏                                                            | 24/93 [01:02<03:32,  3.08s/it]

[ 0.0016893   0.00271707  0.00256709 ... -0.00106804 -0.00115121
  0.        ] 22050


 27%|██████████████████████                                                            | 25/93 [01:06<03:30,  3.09s/it]

[-8.8425225e-04 -1.0659160e-03 -8.0528628e-04 ... -4.2387831e-04
 -5.7793855e-05  0.0000000e+00] 22050


 28%|██████████████████████▉                                                           | 26/93 [01:08<03:13,  2.89s/it]

[0.01710793 0.02544549 0.0228809  ... 0.04074765 0.03925414 0.04185763] 22050


 29%|███████████████████████▊                                                          | 27/93 [01:11<03:06,  2.83s/it]

[ 0.          0.          0.         ... -0.00365696  0.00048274
 -0.00258029] 22050


 30%|████████████████████████▋                                                         | 28/93 [01:13<03:01,  2.79s/it]

[ 0.          0.          0.         ... -0.15257472 -0.14495775
 -0.1533123 ] 22050


 31%|█████████████████████████▌                                                        | 29/93 [01:16<02:56,  2.76s/it]

[ 0.          0.          0.         ... -0.11059644 -0.1085563
 -0.12142587] 22050


 32%|██████████████████████████▍                                                       | 30/93 [01:19<02:54,  2.77s/it]

[ 0.          0.          0.         ... -0.02616313 -0.02832824
 -0.03311377] 22050


 33%|███████████████████████████▎                                                      | 31/93 [01:22<02:53,  2.80s/it]

[ 0.          0.          0.         ... -0.10821859 -0.10085784
 -0.10736299] 22050


 34%|████████████████████████████▏                                                     | 32/93 [01:25<02:54,  2.86s/it]

[0.         0.         0.         ... 0.26945388 0.2562324  0.27221316] 22050


 35%|█████████████████████████████                                                     | 33/93 [01:28<02:55,  2.92s/it]

[ 0.          0.          0.         ... -0.05926341 -0.05534621
 -0.05793385] 22050


 37%|█████████████████████████████▉                                                    | 34/93 [01:31<02:55,  2.98s/it]

[ 0.          0.          0.         ... -0.04694906 -0.05055835
 -0.06256957] 22050


 38%|██████████████████████████████▊                                                   | 35/93 [01:35<03:08,  3.25s/it]

[0.         0.         0.         ... 0.17112456 0.16861391 0.18079142] 22050


 39%|███████████████████████████████▋                                                  | 36/93 [01:39<03:25,  3.60s/it]

[0.         0.         0.         ... 0.09519187 0.0919826  0.10184121] 22050


 40%|████████████████████████████████▌                                                 | 37/93 [01:44<03:37,  3.88s/it]

[0.         0.         0.         ... 0.20328416 0.19927321 0.21701668] 22050


 41%|█████████████████████████████████▌                                                | 38/93 [01:48<03:45,  4.10s/it]

[0.         0.         0.         ... 0.1784105  0.17279524 0.18705997] 22050


 42%|██████████████████████████████████▍                                               | 39/93 [01:52<03:38,  4.05s/it]

[0.         0.         0.         ... 0.15806355 0.15504608 0.16754578] 22050


 43%|███████████████████████████████████▎                                              | 40/93 [01:57<03:38,  4.13s/it]

[0.         0.         0.         ... 0.02381264 0.02345375 0.02424698] 22050


 44%|████████████████████████████████████▏                                             | 41/93 [02:00<03:21,  3.87s/it]

[0.         0.         0.         ... 0.0633135  0.06167608 0.06543391] 22050


 45%|█████████████████████████████████████                                             | 42/93 [02:03<03:03,  3.60s/it]

[0.         0.         0.         ... 0.06957164 0.06568859 0.06777759] 22050


 46%|█████████████████████████████████████▉                                            | 43/93 [02:06<02:49,  3.40s/it]

[0.         0.         0.         ... 0.5169264  0.49420917 0.52765614] 22050


 47%|██████████████████████████████████████▊                                           | 44/93 [02:08<02:36,  3.18s/it]

[ 0.          0.          0.         ... -0.6361075  -0.61864734
 -0.67175263] 22050


 48%|███████████████████████████████████████▋                                          | 45/93 [02:11<02:30,  3.13s/it]

[0.         0.         0.         ... 0.45760438 0.44249195 0.47693253] 22050


 49%|████████████████████████████████████████▌                                         | 46/93 [02:15<02:27,  3.13s/it]

[ 0.          0.          0.         ... -0.07948826 -0.07436877
 -0.08173631] 22050


 51%|█████████████████████████████████████████▍                                        | 47/93 [02:18<02:29,  3.26s/it]

[0.         0.         0.         ... 0.09586173 0.09115418 0.0959226 ] 22050


 52%|██████████████████████████████████████████▎                                       | 48/93 [02:22<02:33,  3.40s/it]

[0.         0.         0.         ... 0.00059579 0.00040884 0.00018524] 22050


 53%|███████████████████████████████████████████▏                                      | 49/93 [02:25<02:22,  3.25s/it]

[0.         0.         0.         ... 0.00061468 0.00073731 0.0010129 ] 22050


 54%|████████████████████████████████████████████                                      | 50/93 [02:28<02:23,  3.34s/it]

[0.         0.         0.         ... 0.00469436 0.00457318 0.00489088] 22050


 55%|████████████████████████████████████████████▉                                     | 51/93 [02:31<02:15,  3.22s/it]

[ 0.          0.          0.         ... -0.03966789 -0.00456789
 -0.01253633] 22050


 56%|█████████████████████████████████████████████▊                                    | 52/93 [02:34<02:11,  3.21s/it]

[ 0.          0.          0.         ... -0.01443889 -0.0036065
  0.00768639] 22050


 57%|██████████████████████████████████████████████▋                                   | 53/93 [02:37<02:04,  3.12s/it]

[0.         0.         0.         ... 0.02293075 0.02522327 0.02491388] 22050


 58%|███████████████████████████████████████████████▌                                  | 54/93 [02:40<02:00,  3.08s/it]

[ 0.          0.          0.         ... -0.01902727 -0.01628051
 -0.00893455] 22050


 59%|████████████████████████████████████████████████▍                                 | 55/93 [02:43<01:55,  3.04s/it]

[0.         0.         0.         ... 0.0115454  0.01240722 0.01308329] 22050


 60%|█████████████████████████████████████████████████▍                                | 56/93 [02:46<01:47,  2.91s/it]

[0.         0.         0.         ... 0.01450576 0.01357326 0.01446307] 22050


 61%|██████████████████████████████████████████████████▎                               | 57/93 [02:49<01:46,  2.95s/it]

[ 0.          0.          0.         ... -0.12028453 -0.11824434
 -0.13014063] 22050


 62%|███████████████████████████████████████████████████▏                              | 58/93 [02:52<01:42,  2.92s/it]

[0.         0.         0.         ... 0.0605499  0.05868293 0.06159526] 22050


 63%|████████████████████████████████████████████████████                              | 59/93 [02:54<01:36,  2.85s/it]

[0.         0.         0.         ... 0.01557782 0.01462343 0.01515078] 22050


 65%|████████████████████████████████████████████████████▉                             | 60/93 [02:57<01:32,  2.80s/it]

[ 0.          0.          0.         ... -0.02254345 -0.02208381
 -0.02349323] 22050


 66%|█████████████████████████████████████████████████████▊                            | 61/93 [03:00<01:30,  2.81s/it]

[ 0.          0.          0.         ... -0.04213747 -0.04335009
 -0.05171286] 22050


 67%|██████████████████████████████████████████████████████▋                           | 62/93 [03:03<01:26,  2.80s/it]

[ 0.          0.          0.         ... -0.00891681 -0.00817552
 -0.00768843] 22050


 68%|███████████████████████████████████████████████████████▌                          | 63/93 [03:06<01:24,  2.80s/it]

[0.         0.         0.         ... 0.02309799 0.02317885 0.02198694] 22050


 69%|████████████████████████████████████████████████████████▍                         | 64/93 [03:08<01:18,  2.72s/it]

[0.         0.         0.         ... 0.0338887  0.03054287 0.0315167 ] 22050


 70%|█████████████████████████████████████████████████████████▎                        | 65/93 [03:11<01:16,  2.74s/it]

[0.         0.         0.         ... 0.00358016 0.0029045  0.00199023] 22050


 71%|██████████████████████████████████████████████████████████▏                       | 66/93 [03:14<01:13,  2.72s/it]

[0.         0.         0.         ... 0.04359322 0.04235546 0.04606871] 22050


 72%|███████████████████████████████████████████████████████████                       | 67/93 [03:16<01:11,  2.76s/it]

[0.         0.         0.         ... 0.07358634 0.06766799 0.07189249] 22050


 73%|███████████████████████████████████████████████████████████▉                      | 68/93 [03:19<01:08,  2.76s/it]

[ 0.          0.          0.         ... -0.06227456 -0.05999418
 -0.06597839] 22050


 74%|████████████████████████████████████████████████████████████▊                     | 69/93 [03:22<01:07,  2.82s/it]

[0.         0.         0.         ... 0.05142609 0.04925839 0.05164963] 22050


 75%|█████████████████████████████████████████████████████████████▋                    | 70/93 [03:25<01:04,  2.82s/it]

[ 0.          0.          0.         ... -0.00450196 -0.00267744
 -0.00234501] 22050


 76%|██████████████████████████████████████████████████████████████▌                   | 71/93 [03:28<01:01,  2.81s/it]

[ 0.          0.          0.         ... -0.02519566 -0.02452996
 -0.02345673] 22050


 77%|███████████████████████████████████████████████████████████████▍                  | 72/93 [03:31<01:02,  2.97s/it]

[0.         0.         0.         ... 0.08202307 0.08476666 0.09766038] 22050


 78%|████████████████████████████████████████████████████████████████▎                 | 73/93 [03:35<01:04,  3.20s/it]

[ 0.          0.          0.         ... -0.03965227 -0.04023258
 -0.04159994] 22050


 80%|█████████████████████████████████████████████████████████████████▏                | 74/93 [03:38<01:02,  3.31s/it]

[0.         0.         0.         ... 0.26817232 0.25902474 0.280427  ] 22050


 81%|██████████████████████████████████████████████████████████████████▏               | 75/93 [03:42<00:58,  3.28s/it]

[0.         0.         0.         ... 0.00342826 0.00317979 0.00364171] 22050


 82%|███████████████████████████████████████████████████████████████████               | 76/93 [03:45<00:58,  3.44s/it]

[0.         0.         0.         ... 0.07517342 0.07454691 0.07867888] 22050


 83%|███████████████████████████████████████████████████████████████████▉              | 77/93 [03:50<01:01,  3.85s/it]

[-0.07247163 -0.10745685 -0.09690773 ...  0.05467346  0.05316706
  0.05753393] 22050


 84%|████████████████████████████████████████████████████████████████████▊             | 78/93 [03:55<01:00,  4.04s/it]

[-0.05803953 -0.08320587 -0.07533526 ...  0.03917618  0.0369745
  0.04105215] 22050


 85%|█████████████████████████████████████████████████████████████████████▋            | 79/93 [03:59<00:56,  4.06s/it]

[ 0.17166029  0.250432    0.21842906 ... -0.03571897 -0.03179305
 -0.03728459] 22050


 86%|██████████████████████████████████████████████████████████████████████▌           | 80/93 [04:02<00:49,  3.80s/it]

[0.         0.         0.         ... 0.3051465  0.29893237 0.3225977 ] 22050


 87%|███████████████████████████████████████████████████████████████████████▍          | 81/93 [04:05<00:44,  3.67s/it]

[0.         0.         0.         ... 0.7375129  0.72093195 0.78232914] 22050


 88%|████████████████████████████████████████████████████████████████████████▎         | 82/93 [04:09<00:40,  3.65s/it]

[ 0.          0.          0.         ... -0.00942516 -0.00825206
 -0.00559559] 22050


 89%|█████████████████████████████████████████████████████████████████████████▏        | 83/93 [04:12<00:35,  3.53s/it]

[0.         0.         0.         ... 0.15102854 0.14400037 0.16173281] 22050


 90%|██████████████████████████████████████████████████████████████████████████        | 84/93 [04:16<00:31,  3.49s/it]

[ 0.          0.          0.         ... -0.06790091 -0.10178107
 -0.13769501] 22050


 91%|██████████████████████████████████████████████████████████████████████████▉       | 85/93 [04:18<00:25,  3.24s/it]

[0.         0.         0.         ... 0.02256879 0.02788899 0.03947941] 22050


 92%|███████████████████████████████████████████████████████████████████████████▊      | 86/93 [04:21<00:21,  3.07s/it]

[ 0.          0.          0.         ... -0.45220456 -0.43463495
 -0.45182434] 22050


 94%|████████████████████████████████████████████████████████████████████████████▋     | 87/93 [04:24<00:17,  2.97s/it]

[ 0.          0.          0.         ... -0.39158678 -0.38113743
 -0.41354823] 22050


 95%|█████████████████████████████████████████████████████████████████████████████▌    | 88/93 [04:26<00:13,  2.78s/it]

[0.         0.         0.         ... 0.06476758 0.05989117 0.0667561 ] 22050


 96%|██████████████████████████████████████████████████████████████████████████████▍   | 89/93 [04:29<00:11,  2.75s/it]

[0.        0.        0.        ... 1.0092846 0.9777773 1.0537751] 22050


 97%|███████████████████████████████████████████████████████████████████████████████▎  | 90/93 [04:31<00:08,  2.75s/it]

[0.         0.         0.         ... 0.02226742 0.02208254 0.02119073] 22050


 98%|████████████████████████████████████████████████████████████████████████████████▏ | 91/93 [04:34<00:05,  2.74s/it]

[0.         0.         0.         ... 0.02370285 0.02627874 0.028067  ] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████ | 92/93 [04:37<00:02,  2.69s/it]

[ 0.          0.          0.         ... -0.22099693 -0.21257466
 -0.23776534] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [04:39<00:00,  2.68s/it]

[ 0.          0.          0.         ... -0.05103435 -0.05238643
 -0.05545169] 22050


done loading test mfcc


In [8]:
train_data['fname'] = train['fname']
train_data['label'] = train['label']

test_data['fname'] = audio_test_files
test_data['label'] = np.zeros((len(audio_test_files)))

In [9]:
#print(train_data)
print(test_data)

             0           1          2          3          4          5  \
0  -374.568476  121.653345  68.564955  35.947216  30.422790  31.903702   
1  -397.516973   97.320405  71.506663  47.443845  33.989614  28.778871   
2  -309.153916  108.590946  49.665790  39.516736  30.495293  28.091219   
3  -270.489556  161.700804  49.739469  17.809513  13.739956  18.044573   
4  -266.609507  158.940668  69.044580  38.555959  28.130570  21.142545   
5  -286.585566  149.852568  74.347056  30.249630  16.780876  14.380454   
6  -243.604437  144.016071   9.083950  25.720157  23.012074  19.829217   
7  -333.424073  134.835047  62.990353  28.851085  28.611614  31.429581   
8  -267.313418   96.330247  20.233180  28.502039  25.393421  21.782721   
9  -222.562185  136.710127  38.600022  30.539879  30.992133  32.360694   
10 -244.793261  110.656752  43.300727  37.123352  24.064541  25.433031   
11 -251.776179  112.736151  52.861586  47.129276  28.793808  27.698803   
12 -281.348908   99.808704  44.638440 

[93 rows x 212 columns]


In [10]:
X = train_data.drop(['label', 'fname'], axis=1)
feature_names = list(X.columns)
X = X.values
labels = np.sort(np.unique(train_data.label.values))
num_class = len(labels)
c2i = {}
i2c = {}
for i, c in enumerate(labels):
    c2i[c] = i
    i2c[i] = c
y = np.array([c2i[x] for x in train_data.label.values])

#print(X)
#print(len(X)) - 99
#y는 train 데이터들이 라벨링한 것
#print(y)
#print(len(y)) - 99

In [11]:
X_test = test_data.drop(['label', 'fname'], axis=1)
X_test = X_test.values

#print(X_test)
#print(len(X_test)) - 8

In [12]:
print(X.shape)
print(X_test.shape)
#test의 라벨링은 어디서?

(299, 210)
(93, 210)


In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)
#이놈이 뭘까

In [14]:
#pca = PCA(n_components=65).fit(X_scaled)
#65땜에 오류뜸
pca = PCA(n_components=65).fit(X_scaled)
#이 값 고쳐야
X_pca = pca.transform(X_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(sum(pca.explained_variance_ratio_)) 

0.9667856951166022


In [15]:
# Fit an SVM model
X_train, X_val, y_train, y_val = train_test_split(X_pca, y, test_size = 0.2, random_state = 42, shuffle = True)
#test_size와 random_state 확인

#train 관련
#print(X_train)
#print(y_train) - train 라벨링

#train 내에서 쪼개는 것으로 추측됨 test 0.2가 100개중 20개로 맞네
#test를 따로 만드는게 아니라 train 내에서 일부를 test에 사용하여 정확도 측정
print(X_val)
print(y_val)
#print(len(X_val)) - 20
#print(len(y_val)) - 20

clf = SVC(kernel = 'rbf', probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

[[-6.0574237   5.53631483 -1.14552842 ... -0.19398018  0.50498533
  -0.38345381]
 [-2.68798566  1.18116591 -3.64737395 ... -0.05154531 -0.107796
   0.25035027]
 [ 3.6630428   6.59873133  3.17546579 ... -0.26343876 -0.23017746
  -0.42441702]
 ...
 [-1.23513999  3.80868895 -1.28549982 ... -0.53509076  0.20488332
   0.36786328]
 [-3.86487187 -7.87938391 -2.05387047 ... -0.67389615  0.05712335
  -0.3960214 ]
 [ 0.48513732 -8.87678328 -4.73662835 ...  0.63959184  0.29561464
  -0.31895134]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9833333333333333


In [16]:
C_grid = [0.001, 0.01, 0.1, 1, 10]
gamma_grid = [0.001, 0.01, 0.1, 1, 10]
param_grid = {'C': C_grid, 'gamma' : gamma_grid}

#grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
#이부분 수정해야
#데이터 갯수 확 느니까 바로먹음
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
grid.fit(X_train, y_train)

# Find the best model
print(grid.best_score_)

print(grid.best_params_)

print(grid.best_estimator_)

0.9665271966527197
{'C': 10, 'gamma': 0.01}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [18]:
clf = SVC(kernel = 'rbf', C = 10, gamma = 0.01, probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

0.9833333333333333
