In [1]:
#csv파일이랑 audio폴더 test 양만큼 개줄여서 디버그하며 할 것

import os
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import pandas as pd
import csv

import scipy
from scipy.stats import skew
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.svm import SVC

In [2]:
filename = np.array(pd.read_csv('data/SC_file_name.csv'))
answer = np.array(pd.read_csv('data/SC_answer.csv'))

audio_train_files = os.listdir('./audio_train/')
audio_test_files = os.listdir('./audio_test/')
train=pd.read_csv('./file_name.csv')

In [3]:
#print(audio_train_files)
#print(audio_test_files)

In [4]:
def get_mfcc(name, path):
    data, _ = librosa.core.load(path+name) #엑셀에 .wav까지 붙여 저장해야됨 안그러면 path+name+'.wav' 이렇게해야
    print(data,_)
    #data, _ = librosa.load(path)
    try:
        #ft1 = librosa.feature.mfcc(data, sr = SAMPLE_RATE, n_mfcc=30)
        ft1 = librosa.feature.mfcc(data, n_mfcc=30) #이게핵심 Sample_rate를 어떻게 조절하느냐
        ft2 = librosa.feature.zero_crossing_rate(data)[0] # n_mfcc 값을 어떻게 조절하느냐에 따라 Feature개수가 달리 뽑힘
        ft3 = librosa.feature.spectral_rolloff(data)[0]
        ft4 = librosa.feature.spectral_centroid(data)[0]
        ft5 = librosa.feature.spectral_contrast(data)[0]
        ft6 = librosa.feature.spectral_bandwidth(data)[0]
        ft1_trunc = np.hstack((np.mean(ft1, axis=1), np.std(ft1, axis=1), skew(ft1, axis = 1), np.max(ft1, axis = 1), np.median(ft1, axis = 1), np.min(ft1, axis = 1)))
        ft2_trunc = np.hstack((np.mean(ft2), np.std(ft2), skew(ft2), np.max(ft2), np.median(ft2), np.min(ft2)))
        ft3_trunc = np.hstack((np.mean(ft3), np.std(ft3), skew(ft3), np.max(ft3), np.median(ft3), np.min(ft3)))
        ft4_trunc = np.hstack((np.mean(ft4), np.std(ft4), skew(ft4), np.max(ft4), np.median(ft4), np.min(ft4)))
        ft5_trunc = np.hstack((np.mean(ft5), np.std(ft5), skew(ft5), np.max(ft5), np.median(ft5), np.min(ft5)))
        ft6_trunc = np.hstack((np.mean(ft6), np.std(ft6), skew(ft6), np.max(ft6), np.median(ft6), np.max(ft6)))
        return pd.Series(np.hstack((ft1_trunc, ft2_trunc, ft3_trunc, ft4_trunc, ft5_trunc, ft6_trunc)))
    except:
        print('bad file')
        return pd.Series([0]*210)

In [5]:
train_data = pd.DataFrame()
train_data['fname'] = train['fname']
test_data=pd.DataFrame()
test_data['fname']=audio_test_files

In [6]:
#print(train_data)
#print(test_data)


In [7]:
train_data=train_data['fname'].progress_apply(get_mfcc,path='./audio_train/')
print('done loading train mfcc')
test_data = test_data['fname'].progress_apply(get_mfcc, path='./audio_test/')
print('done loading test mfcc')



  0%|                                                                                          | 0/199 [00:00<?, ?it/s]

[0.06973912 0.10266001 0.09116188 ... 0.08305359 0.08018959 0.08612607] 22050


  1%|▊                                                                                 | 2/199 [00:08<13:35,  4.14s/it]

[-0.02710845 -0.03993477 -0.03530764 ... -0.04230448 -0.0414599
 -0.04527015] 22050


  2%|█▏                                                                                | 3/199 [00:11<13:00,  3.98s/it]

[ 0.00283427  0.00423394  0.0036414  ... -0.01369482 -0.01395124
 -0.01601286] 22050


  2%|█▋                                                                                | 4/199 [00:15<12:26,  3.83s/it]

[-0.2545665  -0.37054616 -0.3232944  ... -0.05147256 -0.04832996
 -0.0513258 ] 22050


  3%|██                                                                                | 5/199 [00:19<12:13,  3.78s/it]

[ 3.1871754e-05  6.1540527e-06 -3.7155998e-05 ... -1.4125325e-02
 -8.7606525e-03  0.0000000e+00] 22050


  3%|██▍                                                                               | 6/199 [00:21<10:29,  3.26s/it]

[ 0.00079253  0.00089992  0.00091092 ... -0.0049351  -0.00259066
  0.        ] 22050


  4%|██▉                                                                               | 7/199 [00:24<10:44,  3.35s/it]

[ 3.0208554e-05  3.0756044e-05  2.5381032e-05 ... -1.8259089e-02
 -1.1751885e-02 -5.7575861e-03] 22050


  4%|███▎                                                                              | 8/199 [00:26<09:42,  3.05s/it]

[-0.00064508 -0.00077814 -0.0008623  ... -0.01482992 -0.00782498
  0.        ] 22050


  5%|███▋                                                                              | 9/199 [00:28<08:25,  2.66s/it]

[ 0.00110417  0.00130484  0.00140896 ... -0.01235658 -0.00798214
 -0.00392708] 22050


  5%|████                                                                             | 10/199 [00:31<08:43,  2.77s/it]

[ 4.3292630e-07  3.4875336e-06  7.9502988e-06 ... -4.9829770e-02
 -2.8054921e-02  0.0000000e+00] 22050


  6%|████▍                                                                            | 11/199 [00:34<08:49,  2.82s/it]

[0.00072087 0.00177281 0.00336674 ... 0.03278232 0.03167795 0.0341762 ] 22050


  6%|████▉                                                                            | 12/199 [00:38<09:47,  3.14s/it]

[-0.00511142 -0.00661265 -0.00532051 ...  0.05818591  0.05825811
  0.06405238] 22050


  7%|█████▎                                                                           | 13/199 [00:42<10:05,  3.25s/it]

[ 0.13884057  0.20461525  0.18165357 ... -0.07205642 -0.07238604
 -0.08182055] 22050


  7%|█████▋                                                                           | 14/199 [00:45<10:08,  3.29s/it]

[ 0.          0.          0.         ... -0.03222465 -0.02863552
 -0.02814007] 22050


  8%|██████                                                                           | 15/199 [00:48<09:34,  3.12s/it]

[0.         0.         0.         ... 0.81409144 0.7837968  0.8404915 ] 22050


  8%|██████▌                                                                          | 16/199 [00:51<09:23,  3.08s/it]

[0.         0.         0.         ... 0.2893713  0.28139624 0.3021213 ] 22050


  9%|██████▉                                                                          | 17/199 [00:54<09:11,  3.03s/it]

[ 0.          0.          0.         ... -0.15555128 -0.14919281
 -0.1552921 ] 22050


  9%|███████▎                                                                         | 18/199 [00:56<08:34,  2.84s/it]

[0.         0.         0.         ... 0.02468135 0.02214165 0.01943384] 22050


 10%|███████▋                                                                         | 19/199 [00:59<08:28,  2.83s/it]

[ 0.          0.          0.         ... -0.34570888 -0.34052533
 -0.37189066] 22050


 10%|████████▏                                                                        | 20/199 [01:01<08:13,  2.76s/it]

[ 0.          0.          0.         ... -0.36525172 -0.35147998
 -0.3764349 ] 22050


 11%|████████▌                                                                        | 21/199 [01:05<08:37,  2.91s/it]

[0.         0.         0.         ... 0.29563662 0.29204592 0.32384074] 22050


 11%|████████▉                                                                        | 22/199 [01:08<08:33,  2.90s/it]

[ 0.          0.          0.         ... -0.87329555 -0.8426997
 -0.904122  ] 22050


 12%|█████████▎                                                                       | 23/199 [01:10<07:58,  2.72s/it]

[0.         0.         0.         ... 0.08035016 0.07610521 0.08158155] 22050


 12%|█████████▊                                                                       | 24/199 [01:13<08:18,  2.85s/it]

[0.         0.         0.         ... 0.07361161 0.07532007 0.08183191] 22050


 13%|██████████▏                                                                      | 25/199 [01:16<08:32,  2.95s/it]

[ 0.          0.          0.         ... -0.05342972 -0.0532412
 -0.06048   ] 22050


 13%|██████████▌                                                                      | 26/199 [01:19<08:17,  2.88s/it]

[0.         0.         0.         ... 0.48654523 0.47395992 0.5123876 ] 22050


 14%|██████████▉                                                                      | 27/199 [01:22<08:27,  2.95s/it]

[0.         0.         0.         ... 0.01937228 0.01565968 0.01233602] 22050


 14%|███████████▍                                                                     | 28/199 [01:25<08:42,  3.05s/it]

[0.         0.         0.         ... 0.21377535 0.19589575 0.19898888] 22050


 15%|███████████▊                                                                     | 29/199 [01:28<08:10,  2.89s/it]

[ 0.          0.          0.         ... -0.03692322 -0.04029846
 -0.03779646] 22050


 15%|████████████▏                                                                    | 30/199 [01:31<08:06,  2.88s/it]

[ 0.          0.          0.         ... -0.00111335  0.00120612
 -0.00136599] 22050


 16%|████████████▌                                                                    | 31/199 [01:34<08:04,  2.89s/it]

[ 0.          0.          0.         ... -0.27843747 -0.2646894
 -0.28205138] 22050


 16%|█████████████                                                                    | 32/199 [01:37<08:13,  2.96s/it]

[ 0.          0.          0.         ... -0.26306844 -0.2522001
 -0.26922488] 22050


 17%|█████████████▍                                                                   | 33/199 [01:40<08:15,  2.99s/it]

[0.         0.         0.         ... 0.1735332  0.17125647 0.19119985] 22050


 17%|█████████████▊                                                                   | 34/199 [01:43<08:15,  3.00s/it]

[ 0.          0.          0.         ... -0.2167718  -0.2080332
 -0.22265384] 22050


 18%|██████████████▏                                                                  | 35/199 [01:47<08:57,  3.28s/it]

[ 0.          0.          0.         ... -0.05900886 -0.06246108
 -0.06871106] 22050


 18%|██████████████▋                                                                  | 36/199 [01:51<09:42,  3.58s/it]

[0.         0.         0.         ... 0.7010785  0.68610245 0.7446819 ] 22050


 19%|███████████████                                                                  | 37/199 [01:55<09:40,  3.58s/it]

[ 0.          0.          0.         ... -0.1005215  -0.09558512
 -0.09833872] 22050


 19%|███████████████▍                                                                 | 38/199 [01:58<09:13,  3.44s/it]

[ 0.          0.          0.         ... -0.09970824 -0.10170659
 -0.11256789] 22050


 20%|███████████████▊                                                                 | 39/199 [02:01<08:49,  3.31s/it]

[ 0.          0.          0.         ... -0.09393648 -0.0905112
 -0.09887574] 22050


 20%|████████████████▎                                                                | 40/199 [02:04<08:28,  3.20s/it]

[ 0.          0.          0.         ... -0.10736632 -0.10226438
 -0.10872729] 22050


 21%|████████████████▋                                                                | 41/199 [02:07<08:33,  3.25s/it]

[ 0.          0.          0.         ... -0.3698437  -0.36839765
 -0.4094729 ] 22050


 21%|█████████████████                                                                | 42/199 [02:10<08:28,  3.24s/it]

[-0.00949201 -0.01515351 -0.01494985 ...  0.03122446  0.03000467
  0.03189378] 22050


 22%|█████████████████▌                                                               | 43/199 [02:13<08:06,  3.12s/it]

[-1.7585522e-06 -2.2429733e-06 -1.9274846e-06 ... -1.1987473e-02
 -7.4312286e-03  0.0000000e+00] 22050


 22%|█████████████████▉                                                               | 44/199 [02:15<07:24,  2.87s/it]

[-3.1364743e-05 -3.4258581e-05 -3.3931665e-05 ...  5.3538714e-04
  3.7836187e-04  0.0000000e+00] 22050


 23%|██████████████████▎                                                              | 45/199 [02:17<06:43,  2.62s/it]

[-2.9586021e-05 -3.3629472e-05 -3.4923316e-05 ... -2.4650006e-03
 -1.3031738e-03  0.0000000e+00] 22050


 23%|██████████████████▋                                                              | 46/199 [02:19<06:09,  2.42s/it]

[3.0384650e-05 3.1305051e-05 2.8012693e-05 ... 3.9614424e-02 2.4514157e-02
 0.0000000e+00] 22050


 24%|███████████████████▏                                                             | 47/199 [02:21<05:47,  2.29s/it]

[-0.00015414 -0.00019182 -0.00021949 ...  0.02211454  0.01247506
  0.        ] 22050


 24%|███████████████████▌                                                             | 48/199 [02:23<05:24,  2.15s/it]

[2.9788309e-05 3.2301657e-05 3.1995405e-05 ... 1.5126610e-03 9.7192550e-04
 4.7570144e-04] 22050


 25%|███████████████████▉                                                             | 49/199 [02:26<06:05,  2.44s/it]

[-0.30551556 -0.337594   -0.35426965 ...  0.04488467  0.02582479
  0.        ] 22050


 25%|████████████████████▎                                                            | 50/199 [02:35<10:58,  4.42s/it]

[-0.30030748 -0.3313869  -0.3471481  ... -0.10257331 -0.06606323
 -0.03239066] 22050


 26%|████████████████████▊                                                            | 51/199 [02:39<10:41,  4.33s/it]

[-0.5566892  -0.61342674 -0.6413218  ... -0.07702224 -0.0493612
 -0.02408693] 22050


 26%|█████████████████████▏                                                           | 52/199 [02:43<10:24,  4.25s/it]

[-0.87746686 -0.9691256  -1.0164407  ... -0.2245433  -0.14452285
 -0.07082193] 22050


 27%|█████████████████████▌                                                           | 53/199 [02:48<10:22,  4.27s/it]

[-0.14500825 -0.16018207 -0.16798463 ...  0.11473081  0.06627245
  0.        ] 22050


 27%|█████████████████████▉                                                           | 54/199 [02:58<14:34,  6.03s/it]

[-0.00199708 -0.00319508 -0.00331803 ... -0.00064225 -0.00038474
  0.        ] 22050


 28%|██████████████████████▍                                                          | 55/199 [03:01<12:26,  5.18s/it]

[-0.00066345 -0.00110385 -0.00104151 ...  0.00647592  0.00655071
  0.        ] 22050


 28%|██████████████████████▊                                                          | 56/199 [03:04<10:55,  4.58s/it]

[-0.2739319  -0.3025994  -0.31744638 ...  0.01044763  0.00608007
  0.        ] 22050


 29%|███████████████████████▏                                                         | 57/199 [03:12<13:09,  5.56s/it]

[-0.06291798 -0.07026124 -0.07465484 ... -0.14951584 -0.09621288
 -0.04716552] 22050


 29%|███████████████████████▌                                                         | 58/199 [03:16<11:42,  4.98s/it]

[-1.7918481e-06 -5.5685846e-06 -9.9844920e-06 ...  2.7333383e-02
  1.7636651e-02  8.6638099e-03] 22050


 30%|████████████████████████                                                         | 59/199 [03:19<10:29,  4.50s/it]

[ 8.5524260e-07 -2.3861974e-06 -7.3340552e-06 ... -1.3542055e-01
 -8.7212533e-02 -4.2756353e-02] 22050


 30%|████████████████████████▍                                                        | 60/199 [03:22<09:27,  4.08s/it]

[-0.00027686 -0.00032779 -0.00035314 ... -0.03754111 -0.02402511
 -0.01169831] 22050


 31%|████████████████████████▊                                                        | 61/199 [03:25<08:23,  3.65s/it]

[-1.7565626e-06 -1.2353955e-06  5.4582960e-09 ... -2.6573552e-02
 -1.6467988e-02  0.0000000e+00] 22050


 31%|█████████████████████████▏                                                       | 62/199 [03:27<07:07,  3.12s/it]

[0.000215   0.00023683 0.00023057 ... 0.0034874  0.00196025 0.        ] 22050


 32%|█████████████████████████▋                                                       | 63/199 [03:28<05:50,  2.57s/it]

[-3.0497395e-07  1.2244502e-06  3.1903026e-06 ... -9.8866746e-03
 -5.5146376e-03  0.0000000e+00] 22050


 32%|██████████████████████████                                                       | 64/199 [03:30<05:41,  2.53s/it]

[6.2300285e-05 7.5929711e-05 8.4309846e-05 ... 9.5062396e-03 5.8767227e-03
 0.0000000e+00] 22050


 33%|██████████████████████████▍                                                      | 65/199 [03:32<04:51,  2.18s/it]

[2.0636191e-06 5.3742210e-06 7.9173615e-06 ... 8.8258702e-03 5.2438602e-03
 0.0000000e+00] 22050


 33%|██████████████████████████▊                                                      | 66/199 [03:33<04:25,  1.99s/it]

[-1.5476845e-06 -1.4929913e-06  7.7756016e-07 ...  1.0041645e-03
  6.2980881e-04  0.0000000e+00] 22050


 34%|███████████████████████████▎                                                     | 67/199 [03:36<04:44,  2.15s/it]

[ 0.          0.          0.         ... -0.12468348 -0.1273278
 -0.14731203] 22050


 34%|███████████████████████████▋                                                     | 68/199 [03:39<05:04,  2.32s/it]

[ 0.          0.          0.         ... -0.02251784 -0.02150127
 -0.02269199] 22050


 35%|████████████████████████████                                                     | 69/199 [03:42<05:25,  2.50s/it]

[ 0.          0.          0.         ... -0.01567137 -0.01457954
 -0.0151326 ] 22050


 35%|████████████████████████████▍                                                    | 70/199 [03:45<05:45,  2.68s/it]

[0.         0.         0.         ... 0.06823757 0.06161449 0.0576618 ] 22050


 36%|████████████████████████████▉                                                    | 71/199 [03:47<05:39,  2.66s/it]

[ 0.          0.          0.         ... -0.0593754  -0.06029727
 -0.06811669] 22050


 36%|█████████████████████████████▎                                                   | 72/199 [03:50<05:36,  2.65s/it]

[ 0.15286843  0.22476168  0.19892806 ... -0.01032892 -0.01059519
 -0.01229354] 22050


 37%|█████████████████████████████▋                                                   | 73/199 [03:53<05:53,  2.80s/it]

[0.01386719 0.02011131 0.01776993 ... 0.00524451 0.00579907 0.        ] 22050


 37%|██████████████████████████████                                                   | 74/199 [03:56<05:54,  2.83s/it]

[-0.00679656 -0.01003796 -0.00873371 ... -0.02517475 -0.03054456
  0.        ] 22050


 38%|██████████████████████████████▌                                                  | 75/199 [03:59<05:45,  2.79s/it]

[ 0.00579983  0.00852321  0.00752403 ... -0.00082801 -0.00068914
 -0.00070964] 22050


 38%|██████████████████████████████▉                                                  | 76/199 [04:02<06:05,  2.97s/it]

[-0.00053421 -0.00082033 -0.00076593 ... -0.00522986 -0.00525398
 -0.00585139] 22050


 39%|███████████████████████████████▎                                                 | 77/199 [04:05<06:09,  3.03s/it]

[-2.8764509e-05 -3.0061437e-05 -2.9183469e-05 ... -1.0795601e-03
 -5.5044401e-04  0.0000000e+00] 22050


 39%|███████████████████████████████▋                                                 | 78/199 [04:07<05:33,  2.76s/it]

[-7.8413684e-08  9.5552173e-07  1.9807621e-06 ... -3.6296784e-03
 -2.0876050e-03  0.0000000e+00] 22050


 40%|████████████████████████████████▏                                                | 79/199 [04:10<05:13,  2.61s/it]

[1.8421345e-06 3.9703418e-06 4.0728492e-06 ... 1.1935446e-03 6.8373588e-04
 0.0000000e+00] 22050


 40%|████████████████████████████████▌                                                | 80/199 [04:11<04:45,  2.40s/it]

[-2.2084580e-06 -5.9585232e-06 -8.7529661e-06 ... -3.4101740e-02
 -2.1929748e-02 -1.0731890e-02] 22050


 41%|████████████████████████████████▉                                                | 81/199 [04:13<04:23,  2.23s/it]

[-5.8840362e-07  2.2181875e-06  5.4235775e-06 ...  3.1400897e-02
  1.6541665e-02  0.0000000e+00] 22050


 41%|█████████████████████████████████▍                                               | 82/199 [04:14<03:42,  1.90s/it]

[ 5.9769508e-07  8.8926954e-06  2.1092692e-05 ... -1.6348783e-02
 -8.8511044e-03  0.0000000e+00] 22050


 42%|█████████████████████████████████▊                                               | 83/199 [04:16<03:38,  1.88s/it]

[ 0.00772112  0.01154974  0.01025985 ... -0.00331298 -0.00319685
 -0.0037348 ] 22050


 42%|██████████████████████████████████▏                                              | 84/199 [04:19<03:55,  2.05s/it]

[0.28596535 0.3158219  0.33115914 ... 0.08994886 0.05179574 0.        ] 22050


 43%|██████████████████████████████████▌                                              | 85/199 [04:26<06:49,  3.59s/it]

[-0.27563092 -0.30399603 -0.31818    ...  0.00215952  0.00126481
  0.        ] 22050


 43%|███████████████████████████████████                                              | 86/199 [04:34<09:01,  4.79s/it]

[0.03946353 0.04340422 0.04541007 ... 0.4538223  0.29210246 0.14312147] 22050


 44%|███████████████████████████████████▍                                             | 87/199 [04:43<11:38,  6.24s/it]

[-0.3726952  -0.41175988 -0.43205068 ... -0.15957749 -0.10276388
 -0.05036703] 22050


 44%|███████████████████████████████████▊                                             | 88/199 [04:53<13:29,  7.29s/it]

[-0.2810858  -0.31157294 -0.32829928 ... -0.1266794  -0.08168591
 -0.04014152] 22050


 45%|████████████████████████████████████▏                                            | 89/199 [05:01<14:04,  7.68s/it]

[-0.07494406 -0.10856454 -0.09363515 ...  0.01878147  0.01818044
  0.01986458] 22050


 45%|████████████████████████████████████▋                                            | 90/199 [05:04<11:18,  6.23s/it]

[ 0.03124345  0.04578807  0.04021889 ... -0.01389698 -0.01351108
 -0.01445538] 22050


 46%|█████████████████████████████████████                                            | 91/199 [05:09<10:08,  5.63s/it]

[-0.02912769 -0.04266582 -0.03835926 ... -0.07225096 -0.07003564
 -0.07565343] 22050


 46%|█████████████████████████████████████▍                                           | 92/199 [05:12<08:58,  5.03s/it]

[ 0.00182807  0.00246826  0.00192033 ... -0.00439787 -0.00413904
 -0.00436127] 22050


 47%|█████████████████████████████████████▊                                           | 93/199 [05:15<07:53,  4.46s/it]

[-0.06445651 -0.09444108 -0.08404209 ... -0.01689324 -0.01542289
 -0.01585781] 22050


 47%|██████████████████████████████████████▎                                          | 94/199 [05:18<06:56,  3.96s/it]

[0.06414742 0.09454045 0.08388222 ... 0.24822964 0.24023329 0.2587387 ] 22050


 48%|██████████████████████████████████████▋                                          | 95/199 [05:21<06:18,  3.64s/it]

[ 0.08259647  0.12127037  0.1070242  ... -0.02367939 -0.02266011
 -0.0243049 ] 22050


 48%|███████████████████████████████████████                                          | 96/199 [05:24<06:04,  3.54s/it]

[-0.0151329  -0.02294918 -0.0202172  ... -0.04157927 -0.04070212
 -0.04374132] 22050


 49%|███████████████████████████████████████▍                                         | 97/199 [05:27<05:42,  3.36s/it]

[-0.00485999 -0.00679087 -0.00545568 ...  0.01482467  0.0137242
  0.01388321] 22050


 49%|███████████████████████████████████████▉                                         | 98/199 [05:30<05:17,  3.15s/it]

[0.13323113 0.19474407 0.17157386 ... 0.08486681 0.08216646 0.08880045] 22050


 50%|████████████████████████████████████████▎                                        | 99/199 [05:33<04:59,  3.00s/it]

[0.02923446 0.04403316 0.04038239 ... 0.07650845 0.07465485 0.08051185] 22050


 50%|████████████████████████████████████████▏                                       | 100/199 [05:35<04:41,  2.84s/it]

[ 0.03005545  0.04300415  0.03662321 ... -0.0114797  -0.01104879
 -0.01202029] 22050


 51%|████████████████████████████████████████▌                                       | 101/199 [05:38<04:44,  2.90s/it]

[6.0555729e-05 7.3114075e-05 8.1377519e-05 ... 8.7227272e-03 4.8832153e-03
 0.0000000e+00] 22050


 51%|█████████████████████████████████████████                                       | 102/199 [05:39<03:46,  2.33s/it]

[ 1.3562662e-06  9.4506561e-07 -8.5865324e-09 ...  3.3021986e-02
  1.8553611e-02  0.0000000e+00] 22050


 52%|█████████████████████████████████████████▍                                      | 103/199 [05:40<03:00,  1.88s/it]

[6.1053885e-05 7.3011215e-05 8.0253209e-05 ... 5.3349137e-03 2.8286560e-03
 0.0000000e+00] 22050


 52%|█████████████████████████████████████████▊                                      | 104/199 [05:42<03:01,  1.91s/it]

[ 6.7988680e-07 -5.5855821e-06 -1.5208361e-05 ...  1.3006850e-02
  6.8495930e-03  0.0000000e+00] 22050


 53%|██████████████████████████████████████████▏                                     | 105/199 [05:43<02:42,  1.72s/it]

[-8.7546437e-07 -1.6883479e-06 -2.0232412e-06 ...  8.1363264e-03
  4.2472398e-03  0.0000000e+00] 22050


 53%|██████████████████████████████████████████▌                                     | 106/199 [05:44<02:16,  1.47s/it]

[-2.2965232e-06  1.4332079e-05  3.7568196e-05 ... -5.9282253e-03
 -3.7157908e-03  0.0000000e+00] 22050


 54%|███████████████████████████████████████████                                     | 107/199 [05:45<01:53,  1.23s/it]

[-0.05889978 -0.08439805 -0.07164766 ... -0.03685347 -0.03530446
 -0.03779959] 22050


 54%|███████████████████████████████████████████▍                                    | 108/199 [05:47<02:31,  1.66s/it]

[-0.00703423 -0.01040334 -0.00912582 ...  0.08334509  0.08262308
  0.08995433] 22050


 55%|███████████████████████████████████████████▊                                    | 109/199 [05:50<02:59,  1.99s/it]

[0.00841071 0.0121377  0.01047836 ... 0.01875647 0.01999779 0.        ] 22050


 55%|████████████████████████████████████████████▏                                   | 110/199 [05:53<03:13,  2.17s/it]

[-0.00168595 -0.00258133 -0.00231386 ...  0.00077115  0.0006065
  0.00061912] 22050


 56%|████████████████████████████████████████████▌                                   | 111/199 [05:56<03:28,  2.37s/it]

[ 0.00833424  0.01223366  0.01093073 ... -0.02901728 -0.02817109
 -0.03024289] 22050


 56%|█████████████████████████████████████████████                                   | 112/199 [05:58<03:29,  2.41s/it]

[ 0.          0.          0.         ... -0.09031238 -0.08735766
 -0.09306031] 22050


 57%|█████████████████████████████████████████████▍                                  | 113/199 [06:01<03:41,  2.58s/it]

[0.         0.         0.         ... 0.00044038 0.00028749 0.00024897] 22050


 57%|█████████████████████████████████████████████▊                                  | 114/199 [06:04<03:47,  2.68s/it]

[0.         0.         0.         ... 0.25428715 0.24422075 0.26595703] 22050


 58%|██████████████████████████████████████████████▏                                 | 115/199 [06:06<03:39,  2.61s/it]

[ 0.          0.          0.         ... -0.18821347 -0.18663183
 -0.2047519 ] 22050


 58%|██████████████████████████████████████████████▋                                 | 116/199 [06:09<03:40,  2.66s/it]

[0.         0.         0.         ... 0.63282675 0.60743105 0.6499869 ] 22050


 59%|███████████████████████████████████████████████                                 | 117/199 [06:13<03:57,  2.89s/it]

[ 0.          0.          0.         ... -0.15600103 -0.14905778
 -0.15698275] 22050


 59%|███████████████████████████████████████████████▍                                | 118/199 [06:16<04:01,  2.99s/it]

[ 0.          0.          0.         ... -0.1499482  -0.14536801
 -0.15866049] 22050


 60%|███████████████████████████████████████████████▊                                | 119/199 [06:19<04:05,  3.07s/it]

[ 0.          0.          0.         ... -0.03819335 -0.03791534
 -0.04188127] 22050


 60%|████████████████████████████████████████████████▏                               | 120/199 [06:24<04:35,  3.49s/it]

[ 0.          0.          0.         ... -0.06268332 -0.06022708
 -0.06461953] 22050


 61%|████████████████████████████████████████████████▋                               | 121/199 [06:27<04:27,  3.43s/it]

[ 0.          0.          0.         ... -0.28731927 -0.2788944
 -0.3043653 ] 22050


 61%|█████████████████████████████████████████████████                               | 122/199 [06:30<04:24,  3.43s/it]

[ 0.          0.          0.         ... -0.12467527 -0.11601477
 -0.12351672] 22050


 62%|█████████████████████████████████████████████████▍                              | 123/199 [06:34<04:34,  3.61s/it]

[ 0.          0.          0.         ... -0.3117757  -0.30287907
 -0.32905123] 22050


 62%|█████████████████████████████████████████████████▊                              | 124/199 [06:38<04:26,  3.55s/it]

[ 0.          0.          0.         ... -0.60128844 -0.5866989
 -0.6393383 ] 22050


 63%|██████████████████████████████████████████████████▎                             | 125/199 [06:41<04:10,  3.38s/it]

[ 0.          0.          0.         ... -0.09460735 -0.09186393
 -0.10033422] 22050


 63%|██████████████████████████████████████████████████▋                             | 126/199 [06:43<03:46,  3.10s/it]

[0.         0.         0.         ... 0.06824436 0.06823804 0.07497056] 22050


 64%|███████████████████████████████████████████████████                             | 127/199 [06:46<03:45,  3.14s/it]

[ 0.          0.          0.         ... -0.02098945 -0.01939385
 -0.01919075] 22050


 64%|███████████████████████████████████████████████████▍                            | 128/199 [06:50<03:50,  3.24s/it]

[0.         0.         0.         ... 0.0570341  0.05582925 0.0643122 ] 22050


 65%|███████████████████████████████████████████████████▊                            | 129/199 [06:52<03:32,  3.03s/it]

[0.         0.         0.         ... 0.10997557 0.11245404 0.13821203] 22050


 65%|████████████████████████████████████████████████████▎                           | 130/199 [06:57<03:57,  3.44s/it]

[ 0.          0.          0.         ... -0.27762765 -0.265448
 -0.2814702 ] 22050


 66%|████████████████████████████████████████████████████▋                           | 131/199 [07:01<04:13,  3.73s/it]

[0.         0.         0.         ... 0.65125763 0.62605083 0.67070335] 22050


 66%|█████████████████████████████████████████████████████                           | 132/199 [07:05<04:12,  3.77s/it]

[ 0.          0.          0.         ... -0.00710362  0.01155034
  0.03047679] 22050


 67%|█████████████████████████████████████████████████████▍                          | 133/199 [07:09<04:05,  3.73s/it]

[ 0.          0.          0.         ... -0.04220781 -0.0425578
 -0.04848582] 22050


 67%|█████████████████████████████████████████████████████▊                          | 134/199 [07:13<04:05,  3.78s/it]

[ 0.          0.          0.         ... -0.01046014 -0.00814273
 -0.0058492 ] 22050


 68%|██████████████████████████████████████████████████████▎                         | 135/199 [07:15<03:41,  3.47s/it]

[0.         0.         0.         ... 0.06659431 0.06493407 0.07325058] 22050


 68%|██████████████████████████████████████████████████████▋                         | 136/199 [07:19<03:40,  3.50s/it]

[ 0.          0.          0.         ... -0.09697435 -0.09404793
 -0.1009122 ] 22050


 69%|███████████████████████████████████████████████████████                         | 137/199 [07:22<03:35,  3.47s/it]

[0.         0.         0.         ... 0.04830315 0.04316428 0.04473874] 22050


 69%|███████████████████████████████████████████████████████▍                        | 138/199 [07:27<03:55,  3.86s/it]

[0.         0.         0.         ... 0.12839343 0.12455406 0.13296343] 22050


 70%|███████████████████████████████████████████████████████▉                        | 139/199 [07:32<04:06,  4.11s/it]

[ 0.          0.          0.         ... -0.10614821 -0.10306031
 -0.11080159] 22050


 70%|████████████████████████████████████████████████████████▎                       | 140/199 [07:36<04:08,  4.21s/it]

[ 0.          0.          0.         ... -0.04283782 -0.04240255
 -0.0454677 ] 22050


 71%|████████████████████████████████████████████████████████▋                       | 141/199 [07:40<03:57,  4.10s/it]

[0.         0.         0.         ... 0.08306429 0.08193642 0.09004958] 22050


 71%|█████████████████████████████████████████████████████████                       | 142/199 [07:43<03:37,  3.82s/it]

[0.         0.         0.         ... 0.05440215 0.05421929 0.06178407] 22050


 72%|█████████████████████████████████████████████████████████▍                      | 143/199 [07:46<03:17,  3.52s/it]

[ 0.          0.          0.         ... -0.14653698 -0.14106536
 -0.14908496] 22050


 72%|█████████████████████████████████████████████████████████▉                      | 144/199 [07:49<03:06,  3.38s/it]

[ 0.          0.          0.         ... -0.2712792  -0.2602289
 -0.27644926] 22050


 73%|██████████████████████████████████████████████████████████▎                     | 145/199 [07:52<02:59,  3.32s/it]

[0.         0.         0.         ... 0.0585855  0.05834712 0.06446683] 22050


 73%|██████████████████████████████████████████████████████████▋                     | 146/199 [07:55<02:40,  3.04s/it]

[0.         0.         0.         ... 0.09014577 0.08732708 0.09365366] 22050


 74%|███████████████████████████████████████████████████████████                     | 147/199 [07:58<02:39,  3.06s/it]

[0.         0.         0.         ... 0.1488721  0.14210069 0.15414882] 22050


 74%|███████████████████████████████████████████████████████████▍                    | 148/199 [08:00<02:29,  2.94s/it]

[ 0.          0.          0.         ... -0.01634077 -0.01284211
 -0.00887103] 22050


 75%|███████████████████████████████████████████████████████████▉                    | 149/199 [08:03<02:23,  2.87s/it]

[0.         0.         0.         ... 0.03140324 0.02938446 0.03127927] 22050


 75%|████████████████████████████████████████████████████████████▎                   | 150/199 [08:06<02:22,  2.90s/it]

[0.         0.         0.         ... 0.06877434 0.06657933 0.07092424] 22050


 76%|████████████████████████████████████████████████████████████▋                   | 151/199 [08:08<02:08,  2.69s/it]

[0.         0.         0.         ... 0.04315259 0.04266706 0.04637334] 22050


 76%|█████████████████████████████████████████████████████████████                   | 152/199 [08:11<02:09,  2.75s/it]

[0.         0.         0.         ... 0.13846196 0.13753016 0.15601401] 22050


 77%|█████████████████████████████████████████████████████████████▌                  | 153/199 [08:14<02:03,  2.67s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 77%|█████████████████████████████████████████████████████████████▉                  | 154/199 [08:16<02:00,  2.68s/it]

[ 0.          0.          0.         ... -0.853009   -0.826511
 -0.89554524] 22050


 78%|██████████████████████████████████████████████████████████████▎                 | 155/199 [08:19<02:02,  2.79s/it]

[0.         0.         0.         ... 0.7048063  0.68563855 0.7389971 ] 22050


 78%|██████████████████████████████████████████████████████████████▋                 | 156/199 [08:22<01:56,  2.71s/it]

[ 0.          0.          0.         ... -0.0597242  -0.05913943
 -0.06880321] 22050


 79%|███████████████████████████████████████████████████████████████                 | 157/199 [08:25<01:58,  2.81s/it]

[ 0.          0.          0.         ... -0.04255615 -0.03158521
 -0.034418  ] 22050


 79%|███████████████████████████████████████████████████████████████▌                | 158/199 [08:28<01:56,  2.84s/it]

[ 0.          0.          0.         ... -0.12110092 -0.1101577
 -0.1219567 ] 22050


 80%|███████████████████████████████████████████████████████████████▉                | 159/199 [08:31<01:50,  2.77s/it]

[0.         0.         0.         ... 0.03321154 0.03474576 0.03959534] 22050


 80%|████████████████████████████████████████████████████████████████▎               | 160/199 [08:33<01:49,  2.80s/it]

[ 0.          0.          0.         ... -0.00967131 -0.0093653
 -0.01004385] 22050


 81%|████████████████████████████████████████████████████████████████▋               | 161/199 [08:36<01:41,  2.68s/it]

[0.         0.         0.         ... 0.00452353 0.00422161 0.00407965] 22050


 81%|█████████████████████████████████████████████████████████████████▏              | 162/199 [08:39<01:43,  2.79s/it]

[0.         0.         0.         ... 0.00405493 0.0042079  0.00498438] 22050


 82%|█████████████████████████████████████████████████████████████████▌              | 163/199 [08:42<01:41,  2.82s/it]

[ 0.          0.          0.         ... -0.06538848 -0.0640373
 -0.07016253] 22050


 82%|█████████████████████████████████████████████████████████████████▉              | 164/199 [08:44<01:37,  2.79s/it]

[ 0.          0.          0.         ... -0.06714011 -0.06459182
 -0.07058822] 22050


 83%|██████████████████████████████████████████████████████████████████▎             | 165/199 [08:47<01:34,  2.79s/it]

[ 0.          0.          0.         ... -0.0976808  -0.09131095
 -0.1009459 ] 22050


 83%|██████████████████████████████████████████████████████████████████▋             | 166/199 [08:50<01:32,  2.81s/it]

[ 0.          0.          0.         ... -0.24246328 -0.23364931
 -0.2513686 ] 22050


 84%|███████████████████████████████████████████████████████████████████▏            | 167/199 [08:53<01:26,  2.72s/it]

[ 0.          0.          0.         ... -0.07716538 -0.07356218
 -0.08140326] 22050


 84%|███████████████████████████████████████████████████████████████████▌            | 168/199 [08:55<01:23,  2.70s/it]

[ 0.          0.          0.         ... -0.12482095 -0.11627863
 -0.12246422] 22050


 85%|███████████████████████████████████████████████████████████████████▉            | 169/199 [08:58<01:19,  2.65s/it]

[ 0.          0.          0.         ... -0.01074216 -0.01034736
 -0.01125017] 22050


 85%|████████████████████████████████████████████████████████████████████▎           | 170/199 [09:01<01:17,  2.68s/it]

[0.         0.         0.         ... 0.24655572 0.23584485 0.24982773] 22050


 86%|████████████████████████████████████████████████████████████████████▋           | 171/199 [09:03<01:12,  2.60s/it]

[0.         0.         0.         ... 0.12076917 0.1194012  0.12977952] 22050


 86%|█████████████████████████████████████████████████████████████████████▏          | 172/199 [09:06<01:10,  2.63s/it]

[0.         0.         0.         ... 0.00541603 0.00534779 0.00361776] 22050


 87%|█████████████████████████████████████████████████████████████████████▌          | 173/199 [09:08<01:08,  2.65s/it]

[0.         0.         0.         ... 0.00590403 0.00539305 0.00577536] 22050


 87%|█████████████████████████████████████████████████████████████████████▉          | 174/199 [09:12<01:12,  2.90s/it]

[ 0.          0.          0.         ... -0.1507879  -0.14893688
 -0.17197357] 22050


 88%|██████████████████████████████████████████████████████████████████████▎         | 175/199 [09:15<01:13,  3.07s/it]

[0.         0.         0.         ... 0.04399489 0.04110481 0.0455402 ] 22050


 88%|██████████████████████████████████████████████████████████████████████▊         | 176/199 [09:19<01:12,  3.15s/it]

[ 0.          0.          0.         ... -0.03041141 -0.03024904
 -0.03383819] 22050


 89%|███████████████████████████████████████████████████████████████████████▏        | 177/199 [09:22<01:07,  3.08s/it]

[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 3.49719558e-05
 1.04438295e-04 4.18424490e-04] 22050


 89%|███████████████████████████████████████████████████████████████████████▌        | 178/199 [09:25<01:03,  3.05s/it]

[0.08209334 0.12027321 0.10592982 ... 0.09523189 0.09189781 0.09868933] 22050


 90%|███████████████████████████████████████████████████████████████████████▉        | 179/199 [09:28<01:03,  3.17s/it]

[ 0.00025519  0.00028764  0.00014868 ... -0.00348902 -0.00338399
 -0.0036069 ] 22050


 90%|████████████████████████████████████████████████████████████████████████▎       | 180/199 [09:31<01:02,  3.27s/it]

[-0.01997385 -0.02963021 -0.02664766 ... -0.02849923 -0.02836062
 -0.03160037] 22050


 91%|████████████████████████████████████████████████████████████████████████▊       | 181/199 [09:35<00:59,  3.33s/it]

[ 0.          0.          0.         ... -0.5391371  -0.52193433
 -0.5663463 ] 22050


 91%|█████████████████████████████████████████████████████████████████████████▏      | 182/199 [09:38<00:54,  3.23s/it]

[0.         0.         0.         ... 0.03783033 0.03612902 0.03943321] 22050


 92%|█████████████████████████████████████████████████████████████████████████▌      | 183/199 [09:41<00:52,  3.27s/it]

[0.         0.         0.         ... 0.04257868 0.0448944  0.05588475] 22050


 92%|█████████████████████████████████████████████████████████████████████████▉      | 184/199 [09:45<00:50,  3.40s/it]

[0.         0.         0.         ... 0.05401823 0.05287353 0.05755837] 22050


 93%|██████████████████████████████████████████████████████████████████████████▎     | 185/199 [09:48<00:45,  3.27s/it]

[0.         0.         0.         ... 0.09213886 0.09398716 0.10088132] 22050


 93%|██████████████████████████████████████████████████████████████████████████▊     | 186/199 [09:52<00:44,  3.42s/it]

[0.         0.         0.         ... 0.11685472 0.1111599  0.11944976] 22050


 94%|███████████████████████████████████████████████████████████████████████████▏    | 187/199 [09:55<00:42,  3.50s/it]

[0.         0.         0.         ... 0.4792076  0.45526347 0.49092004] 22050


 94%|███████████████████████████████████████████████████████████████████████████▌    | 188/199 [09:59<00:39,  3.55s/it]

[ 0.          0.          0.         ... -0.01120818 -0.00803506
 -0.01138652] 22050


 95%|███████████████████████████████████████████████████████████████████████████▉    | 189/199 [10:02<00:34,  3.41s/it]

[ 0.          0.          0.         ... -0.05364962 -0.05210137
 -0.055831  ] 22050


 95%|████████████████████████████████████████████████████████████████████████████▍   | 190/199 [10:06<00:30,  3.42s/it]

[0.         0.         0.         ... 0.87999165 0.8438236  0.9057113 ] 22050


 96%|████████████████████████████████████████████████████████████████████████████▊   | 191/199 [10:09<00:27,  3.43s/it]

[0.         0.         0.         ... 0.22386    0.21816497 0.23659104] 22050


 96%|█████████████████████████████████████████████████████████████████████████████▏  | 192/199 [10:12<00:23,  3.40s/it]

[0.        0.        0.        ... 0.9459605 0.9187443 0.9850489] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▌  | 193/199 [10:15<00:19,  3.20s/it]

[ 0.          0.          0.         ... -0.03106961 -0.02864614
 -0.03651939] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▉  | 194/199 [10:18<00:15,  3.19s/it]

[ 0.          0.          0.         ... -0.09009068 -0.09058654
 -0.10142617] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▍ | 195/199 [10:21<00:12,  3.07s/it]

[ 0.          0.          0.         ... -0.953986   -0.92493206
 -0.98153687] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▊ | 196/199 [10:23<00:08,  2.81s/it]

[ 0.          0.          0.         ... -0.15020148 -0.14647253
 -0.15748379] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▏| 197/199 [10:26<00:05,  2.90s/it]

[ 0.          0.          0.         ... -0.12514465 -0.12138256
 -0.12777631] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▌| 198/199 [10:30<00:02,  2.97s/it]

[ 0.          0.          0.         ... -0.0088842  -0.00718911
 -0.00901421] 22050


100%|████████████████████████████████████████████████████████████████████████████████| 199/199 [10:32<00:00,  2.84s/it]

[0.         0.         0.         ... 0.08539807 0.08473286 0.09463313] 22050


done loading train mfcc


  0%|                                                                                           | 0/85 [00:00<?, ?it/s]

[ 0.          0.          0.         ... -0.15097117 -0.14199436
 -0.15616187] 22050


  2%|█▉                                                                                 | 2/85 [00:03<02:22,  1.71s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


  4%|██▉                                                                                | 3/85 [00:06<02:58,  2.18s/it]

[0.         0.         0.         ... 0.11905885 0.1190711  0.13462272] 22050


  5%|███▉                                                                               | 4/85 [00:10<03:38,  2.70s/it]

[ 0.          0.          0.         ... -0.14376757 -0.14634912
 -0.16929877] 22050


  6%|████▉                                                                              | 5/85 [00:13<03:52,  2.91s/it]

[0.        0.        0.        ... 0.2842634 0.2742911 0.2978991] 22050


  7%|█████▊                                                                             | 6/85 [00:17<04:07,  3.14s/it]

[ 0.          0.          0.         ... -1.0097158  -0.97754306
 -1.0540003 ] 22050


  8%|██████▊                                                                            | 7/85 [00:20<04:05,  3.14s/it]

[ 0.          0.          0.         ... -0.5240373  -0.51735884
 -0.5599158 ] 22050


  9%|███████▊                                                                           | 8/85 [00:23<03:58,  3.10s/it]

[ 0.          0.          0.         ... -0.24339022 -0.23302886
 -0.24892566] 22050


 11%|████████▊                                                                          | 9/85 [00:27<04:03,  3.21s/it]

[0.         0.         0.         ... 0.07006744 0.06390787 0.06843111] 22050


 12%|█████████▋                                                                        | 10/85 [00:30<04:03,  3.25s/it]

[0.         0.         0.         ... 0.23463461 0.22792263 0.26713893] 22050


 13%|██████████▌                                                                       | 11/85 [00:33<03:44,  3.04s/it]

[0.         0.         0.         ... 0.20498481 0.20232959 0.22086047] 22050


 14%|███████████▌                                                                      | 12/85 [00:36<03:41,  3.03s/it]

[-0.00283933 -0.00401512 -0.00344597 ...  0.0097526   0.01072497
  0.        ] 22050


 15%|████████████▌                                                                     | 13/85 [00:39<03:42,  3.09s/it]

[-0.02181281 -0.03193489 -0.02826805 ...  0.00575696  0.00659533
  0.        ] 22050


 16%|█████████████▌                                                                    | 14/85 [00:42<03:28,  2.94s/it]

[ 0.00773429  0.01167202  0.01085229 ... -0.00154025 -0.00176283
  0.        ] 22050


 18%|██████████████▍                                                                   | 15/85 [00:45<03:32,  3.04s/it]

[-9.4293209e-04 -1.5129785e-03 -1.3976007e-03 ...  2.1218079e-04
  7.5372486e-07  0.0000000e+00] 22050


 19%|███████████████▍                                                                  | 16/85 [00:48<03:33,  3.09s/it]

[ 0.0016893   0.00271707  0.00256709 ... -0.00106804 -0.00115121
  0.        ] 22050


 20%|████████████████▍                                                                 | 17/85 [00:51<03:28,  3.06s/it]

[-8.8425225e-04 -1.0659160e-03 -8.0528628e-04 ... -4.2387831e-04
 -5.7793855e-05  0.0000000e+00] 22050


 21%|█████████████████▎                                                                | 18/85 [00:54<03:29,  3.13s/it]

[0.01710793 0.02544549 0.0228809  ... 0.04074765 0.03925414 0.04185763] 22050


 22%|██████████████████▎                                                               | 19/85 [00:58<03:31,  3.21s/it]

[ 0.          0.          0.         ... -0.00365696  0.00048274
 -0.00258029] 22050


 24%|███████████████████▎                                                              | 20/85 [01:00<03:21,  3.09s/it]

[ 0.          0.          0.         ... -0.15257472 -0.14495775
 -0.1533123 ] 22050


 25%|████████████████████▎                                                             | 21/85 [01:04<03:26,  3.23s/it]

[ 0.          0.          0.         ... -0.11059644 -0.1085563
 -0.12142587] 22050


 26%|█████████████████████▏                                                            | 22/85 [01:07<03:26,  3.27s/it]

[ 0.          0.          0.         ... -0.02616313 -0.02832824
 -0.03311377] 22050


 27%|██████████████████████▏                                                           | 23/85 [01:11<03:34,  3.46s/it]

[ 0.          0.          0.         ... -0.10821859 -0.10085784
 -0.10736299] 22050


 28%|███████████████████████▏                                                          | 24/85 [01:15<03:31,  3.47s/it]

[0.         0.         0.         ... 0.26945388 0.2562324  0.27221316] 22050


 29%|████████████████████████                                                          | 25/85 [01:18<03:24,  3.40s/it]

[ 0.          0.          0.         ... -0.05926341 -0.05534621
 -0.05793385] 22050


 31%|█████████████████████████                                                         | 26/85 [01:22<03:29,  3.54s/it]

[ 0.          0.          0.         ... -0.04694906 -0.05055835
 -0.06256957] 22050


 32%|██████████████████████████                                                        | 27/85 [01:27<03:44,  3.87s/it]

[0.         0.         0.         ... 0.17112456 0.16861391 0.18079142] 22050


 33%|███████████████████████████                                                       | 28/85 [01:33<04:20,  4.58s/it]

[0.         0.         0.         ... 0.09519187 0.0919826  0.10184121] 22050


 34%|███████████████████████████▉                                                      | 29/85 [01:38<04:34,  4.91s/it]

[0.         0.         0.         ... 0.20328416 0.19927321 0.21701668] 22050


 35%|████████████████████████████▉                                                     | 30/85 [01:43<04:23,  4.79s/it]

[0.         0.         0.         ... 0.1784105  0.17279524 0.18705997] 22050


 36%|█████████████████████████████▉                                                    | 31/85 [01:46<03:54,  4.34s/it]

[0.         0.         0.         ... 0.15806355 0.15504608 0.16754578] 22050


 38%|██████████████████████████████▊                                                   | 32/85 [01:50<03:47,  4.29s/it]

[0.         0.         0.         ... 0.02381264 0.02345375 0.02424698] 22050


 39%|███████████████████████████████▊                                                  | 33/85 [01:54<03:37,  4.19s/it]

[0.         0.         0.         ... 0.0633135  0.06167608 0.06543391] 22050


 40%|████████████████████████████████▊                                                 | 34/85 [01:58<03:29,  4.12s/it]

[0.         0.         0.         ... 0.06957164 0.06568859 0.06777759] 22050


 41%|█████████████████████████████████▊                                                | 35/85 [02:02<03:26,  4.12s/it]

[0.         0.         0.         ... 0.5169264  0.49420917 0.52765614] 22050


 42%|██████████████████████████████████▋                                               | 36/85 [02:05<03:04,  3.77s/it]

[ 0.          0.          0.         ... -0.6361075  -0.61864734
 -0.67175263] 22050


 44%|███████████████████████████████████▋                                              | 37/85 [02:08<02:46,  3.48s/it]

[0.         0.         0.         ... 0.45760438 0.44249195 0.47693253] 22050


 45%|████████████████████████████████████▋                                             | 38/85 [02:11<02:28,  3.16s/it]

[ 0.          0.          0.         ... -0.07948826 -0.07436877
 -0.08173631] 22050


 46%|█████████████████████████████████████▌                                            | 39/85 [02:13<02:20,  3.06s/it]

[0.         0.         0.         ... 0.09586173 0.09115418 0.0959226 ] 22050


 47%|██████████████████████████████████████▌                                           | 40/85 [02:16<02:08,  2.86s/it]

[0.         0.         0.         ... 0.00059579 0.00040884 0.00018524] 22050


 48%|███████████████████████████████████████▌                                          | 41/85 [02:19<02:04,  2.84s/it]

[0.         0.         0.         ... 0.00061468 0.00073731 0.0010129 ] 22050


 49%|████████████████████████████████████████▌                                         | 42/85 [02:21<01:59,  2.77s/it]

[0.         0.         0.         ... 0.00469436 0.00457318 0.00489088] 22050


 51%|█████████████████████████████████████████▍                                        | 43/85 [02:25<02:03,  2.94s/it]

[ 0.          0.          0.         ... -0.03966789 -0.00456789
 -0.01253633] 22050


 52%|██████████████████████████████████████████▍                                       | 44/85 [02:28<02:09,  3.16s/it]

[ 0.          0.          0.         ... -0.01443889 -0.0036065
  0.00768639] 22050


 53%|███████████████████████████████████████████▍                                      | 45/85 [02:31<02:05,  3.14s/it]

[0.         0.         0.         ... 0.02293075 0.02522327 0.02491388] 22050


 54%|████████████████████████████████████████████▍                                     | 46/85 [02:34<01:57,  3.02s/it]

[ 0.          0.          0.         ... -0.01902727 -0.01628051
 -0.00893455] 22050


 55%|█████████████████████████████████████████████▎                                    | 47/85 [02:37<01:53,  2.98s/it]

[0.         0.         0.         ... 0.0115454  0.01240722 0.01308329] 22050


 56%|██████████████████████████████████████████████▎                                   | 48/85 [02:40<01:54,  3.10s/it]

[0.         0.         0.         ... 0.01450576 0.01357326 0.01446307] 22050


 58%|███████████████████████████████████████████████▎                                  | 49/85 [02:43<01:50,  3.08s/it]

[ 0.          0.          0.         ... -0.12028453 -0.11824434
 -0.13014063] 22050


 59%|████████████████████████████████████████████████▏                                 | 50/85 [02:47<01:53,  3.25s/it]

[0.         0.         0.         ... 0.0605499  0.05868293 0.06159526] 22050


 60%|█████████████████████████████████████████████████▏                                | 51/85 [02:51<01:59,  3.52s/it]

[0.         0.         0.         ... 0.01557782 0.01462343 0.01515078] 22050


 61%|██████████████████████████████████████████████████▏                               | 52/85 [02:54<01:51,  3.36s/it]

[ 0.          0.          0.         ... -0.02254345 -0.02208381
 -0.02349323] 22050


 62%|███████████████████████████████████████████████████▏                              | 53/85 [02:59<02:04,  3.91s/it]

[ 0.          0.          0.         ... -0.04213747 -0.04335009
 -0.05171286] 22050


 64%|████████████████████████████████████████████████████                              | 54/85 [03:03<01:56,  3.75s/it]

[ 0.          0.          0.         ... -0.00891681 -0.00817552
 -0.00768843] 22050


 65%|█████████████████████████████████████████████████████                             | 55/85 [03:05<01:42,  3.42s/it]

[0.         0.         0.         ... 0.02309799 0.02317885 0.02198694] 22050


 66%|██████████████████████████████████████████████████████                            | 56/85 [03:08<01:35,  3.30s/it]

[0.         0.         0.         ... 0.0338887  0.03054287 0.0315167 ] 22050


 67%|██████████████████████████████████████████████████████▉                           | 57/85 [03:11<01:28,  3.16s/it]

[0.         0.         0.         ... 0.00358016 0.0029045  0.00199023] 22050


 68%|███████████████████████████████████████████████████████▉                          | 58/85 [03:14<01:24,  3.14s/it]

[0.         0.         0.         ... 0.04359322 0.04235546 0.04606871] 22050


 69%|████████████████████████████████████████████████████████▉                         | 59/85 [03:18<01:25,  3.27s/it]

[0.         0.         0.         ... 0.07358634 0.06766799 0.07189249] 22050


 71%|█████████████████████████████████████████████████████████▉                        | 60/85 [03:21<01:22,  3.30s/it]

[ 0.          0.          0.         ... -0.06227456 -0.05999418
 -0.06597839] 22050


 72%|██████████████████████████████████████████████████████████▊                       | 61/85 [03:24<01:15,  3.14s/it]

[0.         0.         0.         ... 0.05142609 0.04925839 0.05164963] 22050


 73%|███████████████████████████████████████████████████████████▊                      | 62/85 [03:28<01:14,  3.25s/it]

[ 0.          0.          0.         ... -0.00450196 -0.00267744
 -0.00234501] 22050


 74%|████████████████████████████████████████████████████████████▊                     | 63/85 [03:31<01:12,  3.29s/it]

[ 0.          0.          0.         ... -0.02519566 -0.02452996
 -0.02345673] 22050


 75%|█████████████████████████████████████████████████████████████▋                    | 64/85 [03:35<01:11,  3.42s/it]

[0.         0.         0.         ... 0.08202307 0.08476666 0.09766038] 22050


 76%|██████████████████████████████████████████████████████████████▋                   | 65/85 [03:38<01:08,  3.41s/it]

[ 0.          0.          0.         ... -0.03965227 -0.04023258
 -0.04159994] 22050


 78%|███████████████████████████████████████████████████████████████▋                  | 66/85 [03:41<01:04,  3.38s/it]

[0.         0.         0.         ... 0.26817232 0.25902474 0.280427  ] 22050


 79%|████████████████████████████████████████████████████████████████▋                 | 67/85 [03:46<01:06,  3.71s/it]

[0.         0.         0.         ... 0.00342826 0.00317979 0.00364171] 22050


 80%|█████████████████████████████████████████████████████████████████▌                | 68/85 [03:50<01:07,  3.98s/it]

[0.         0.         0.         ... 0.07517342 0.07454691 0.07867888] 22050


 81%|██████████████████████████████████████████████████████████████████▌               | 69/85 [03:55<01:04,  4.03s/it]

[-0.07247163 -0.10745685 -0.09690773 ...  0.05467346  0.05316706
  0.05753393] 22050


 82%|███████████████████████████████████████████████████████████████████▌              | 70/85 [03:59<01:01,  4.08s/it]

[-0.05803953 -0.08320587 -0.07533526 ...  0.03917618  0.0369745
  0.04105215] 22050


 84%|████████████████████████████████████████████████████████████████████▍             | 71/85 [04:03<00:56,  4.03s/it]

[ 0.17166029  0.250432    0.21842906 ... -0.03571897 -0.03179305
 -0.03728459] 22050


 85%|█████████████████████████████████████████████████████████████████████▍            | 72/85 [04:06<00:50,  3.90s/it]

[0.         0.         0.         ... 0.3051465  0.29893237 0.3225977 ] 22050


 86%|██████████████████████████████████████████████████████████████████████▍           | 73/85 [04:09<00:43,  3.66s/it]

[0.         0.         0.         ... 0.7375129  0.72093195 0.78232914] 22050


 87%|███████████████████████████████████████████████████████████████████████▍          | 74/85 [04:14<00:41,  3.80s/it]

[ 0.          0.          0.         ... -0.00942516 -0.00825206
 -0.00559559] 22050


 88%|████████████████████████████████████████████████████████████████████████▎         | 75/85 [04:18<00:39,  3.99s/it]

[0.         0.         0.         ... 0.15102854 0.14400037 0.16173281] 22050


 89%|█████████████████████████████████████████████████████████████████████████▎        | 76/85 [04:21<00:33,  3.74s/it]

[ 0.          0.          0.         ... -0.06790091 -0.10178107
 -0.13769501] 22050


 91%|██████████████████████████████████████████████████████████████████████████▎       | 77/85 [04:24<00:27,  3.46s/it]

[0.         0.         0.         ... 0.02256879 0.02788899 0.03947941] 22050


 92%|███████████████████████████████████████████████████████████████████████████▏      | 78/85 [04:26<00:21,  3.12s/it]

[ 0.          0.          0.         ... -0.45220456 -0.43463495
 -0.45182434] 22050


 93%|████████████████████████████████████████████████████████████████████████████▏     | 79/85 [04:29<00:18,  3.03s/it]

[ 0.          0.          0.         ... -0.39158678 -0.38113743
 -0.41354823] 22050


 94%|█████████████████████████████████████████████████████████████████████████████▏    | 80/85 [04:32<00:14,  2.88s/it]

[0.         0.         0.         ... 0.06476758 0.05989117 0.0667561 ] 22050


 95%|██████████████████████████████████████████████████████████████████████████████▏   | 81/85 [04:34<00:11,  2.80s/it]

[0.        0.        0.        ... 1.0092846 0.9777773 1.0537751] 22050


 96%|███████████████████████████████████████████████████████████████████████████████   | 82/85 [04:37<00:08,  2.76s/it]

[0.         0.         0.         ... 0.02226742 0.02208254 0.02119073] 22050


 98%|████████████████████████████████████████████████████████████████████████████████  | 83/85 [04:39<00:05,  2.70s/it]

[0.         0.         0.         ... 0.02370285 0.02627874 0.028067  ] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████ | 84/85 [04:42<00:02,  2.66s/it]

[ 0.          0.          0.         ... -0.22099693 -0.21257466
 -0.23776534] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 85/85 [04:44<00:00,  2.56s/it]

[ 0.          0.          0.         ... -0.05103435 -0.05238643
 -0.05545169] 22050


done loading test mfcc


In [8]:
train_data['fname'] = train['fname']
train_data['label'] = train['label']

test_data['fname'] = audio_test_files
test_data['label'] = np.zeros((len(audio_test_files)))

In [9]:
#print(train_data)
#print(test_data)

In [10]:
X = train_data.drop(['label', 'fname'], axis=1)
feature_names = list(X.columns)
X = X.values
labels = np.sort(np.unique(train_data.label.values))
num_class = len(labels)
c2i = {}
i2c = {}
for i, c in enumerate(labels):
    c2i[c] = i
    i2c[i] = c
y = np.array([c2i[x] for x in train_data.label.values])

#print(X)
#y는 train 데이터들이 라벨링한 것
print(y)

[0 0 1 2 3 3 3 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 5 5 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 5 5
 3 3 3 3 3 3 3 3 0 3 3 3 3 3 1 1 6 6 6 6 6 6 6 6 6 1 3 3 3 3 3 3 1 1 1 3 0
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [11]:
X_test = test_data.drop(['label', 'fname'], axis=1)
X_test = X_test.values

In [12]:
print(X.shape)
print(X_test.shape)
#test의 라벨링은 어디서?

(199, 210)
(85, 210)


In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)
#이놈이 뭘까

In [14]:
#pca = PCA(n_components=65).fit(X_scaled)
#65땜에 오류뜸
pca = PCA(n_components=65).fit(X_scaled)
#이 값 고쳐야
X_pca = pca.transform(X_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(sum(pca.explained_variance_ratio_)) 

0.9754405556213618


In [15]:
# Fit an SVM model
X_train, X_val, y_train, y_val = train_test_split(X_pca, y, test_size = 0.2, random_state = 42, shuffle = True)
#test_size와 random_state 확인

#train 관련
#print(X_train)
#print(y_train) - train 라벨링

#train 내에서 쪼개는 것으로 추측됨 test 0.2가 100개중 20개로 맞네
#test를 따로 만드는게 아니라 train 내에서 일부를 test에 사용하여 정확도 측정
print(X_val)
print(y_val)

clf = SVC(kernel = 'rbf', probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

[[-4.56048964e+00 -2.27337087e+00  4.82385643e+00 ...  9.41561200e-02
  -1.18696968e-01  7.07935519e-01]
 [-4.19896702e+00  4.40502969e+00 -1.73559845e+00 ...  1.00444888e-01
  -3.24883693e-01 -7.78573379e-01]
 [-1.75684578e+00  3.06983651e+00 -3.29299337e+00 ...  2.28964175e-01
  -6.58183838e-01 -3.94364585e-01]
 ...
 [ 5.76241744e-03 -1.60612140e-01  8.40171855e-01 ... -3.40128612e-01
   5.41638942e-01  2.99980706e-01]
 [ 2.06119709e+00 -7.80037088e-01  2.86100263e+00 ... -4.44094524e-01
  -4.12873900e-01  7.12752455e-01]
 [ 9.57576077e+00 -2.29926649e+00 -5.72150494e+00 ...  9.31714517e-01
   1.84511927e-02  1.04255703e-02]]
[0 3 3 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 3 3 3 6 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.95


In [16]:
C_grid = [0.001, 0.01, 0.1, 1, 10]
gamma_grid = [0.001, 0.01, 0.1, 1, 10]
param_grid = {'C': C_grid, 'gamma' : gamma_grid}

#grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
#이부분 수정해야
#데이터 갯수 확 느니까 바로먹음
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
grid.fit(X_train, y_train)

# Find the best model
print(grid.best_score_)

print(grid.best_params_)

print(grid.best_estimator_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.9245283018867925
{'C': 10, 'gamma': 0.001}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [19]:
clf = SVC(kernel = 'rbf', C = 10, gamma = 0.001, probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

0.95


In [18]:
# Fit the entire training sets
clf.fit(X_pca, y)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)