In [1]:
#csv파일이랑 audio폴더 test 양만큼 개줄여서 디버그하며 할 것

import os
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import pandas as pd
import csv

import scipy
from scipy.stats import skew
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.svm import SVC

In [2]:
filename = np.array(pd.read_csv('data/SC_file_name.csv'))
answer = np.array(pd.read_csv('data/SC_answer.csv'))

audio_train_files = os.listdir('./audio_train/')
audio_test_files = os.listdir('./audio_test/')
train=pd.read_csv('./file_name.csv')

In [3]:
#print(audio_train_files)
#print(audio_test_files)

In [4]:
def get_mfcc(name, path):
    data, _ = librosa.core.load(path+name) #엑셀에 .wav까지 붙여 저장해야됨 안그러면 path+name+'.wav' 이렇게해야
    print(data,_)
    #data, _ = librosa.load(path)
    try:
        #ft1 = librosa.feature.mfcc(data, sr = SAMPLE_RATE, n_mfcc=30)
        ft1 = librosa.feature.mfcc(data, n_mfcc=30) #이게핵심 Sample_rate를 어떻게 조절하느냐
        ft2 = librosa.feature.zero_crossing_rate(data)[0] # n_mfcc 값을 어떻게 조절하느냐에 따라 Feature개수가 달리 뽑힘
        ft3 = librosa.feature.spectral_rolloff(data)[0]
        ft4 = librosa.feature.spectral_centroid(data)[0]
        ft5 = librosa.feature.spectral_contrast(data)[0]
        ft6 = librosa.feature.spectral_bandwidth(data)[0]
        ft1_trunc = np.hstack((np.mean(ft1, axis=1), np.std(ft1, axis=1), skew(ft1, axis = 1), np.max(ft1, axis = 1), np.median(ft1, axis = 1), np.min(ft1, axis = 1)))
        ft2_trunc = np.hstack((np.mean(ft2), np.std(ft2), skew(ft2), np.max(ft2), np.median(ft2), np.min(ft2)))
        ft3_trunc = np.hstack((np.mean(ft3), np.std(ft3), skew(ft3), np.max(ft3), np.median(ft3), np.min(ft3)))
        ft4_trunc = np.hstack((np.mean(ft4), np.std(ft4), skew(ft4), np.max(ft4), np.median(ft4), np.min(ft4)))
        ft5_trunc = np.hstack((np.mean(ft5), np.std(ft5), skew(ft5), np.max(ft5), np.median(ft5), np.min(ft5)))
        ft6_trunc = np.hstack((np.mean(ft6), np.std(ft6), skew(ft6), np.max(ft6), np.median(ft6), np.max(ft6)))
        return pd.Series(np.hstack((ft1_trunc, ft2_trunc, ft3_trunc, ft4_trunc, ft5_trunc, ft6_trunc)))
    except:
        print('bad file')
        return pd.Series([0]*210)

In [5]:
train_data = pd.DataFrame()
train_data['fname'] = train['fname']
test_data=pd.DataFrame()
test_data['fname']=audio_test_files

In [6]:
#print(train_data)
#print(test_data)


In [7]:
train_data=train_data['fname'].progress_apply(get_mfcc,path='./audio_train/')
print('done loading train mfcc')
test_data = test_data['fname'].progress_apply(get_mfcc, path='./audio_test/')
print('done loading test mfcc')



  0%|                                                                                          | 0/299 [00:00<?, ?it/s]

[0.06973912 0.10266001 0.09116188 ... 0.08305359 0.08018959 0.08612607] 22050


  1%|▌                                                                                 | 2/299 [00:07<18:20,  3.71s/it]

[-0.02710845 -0.03993477 -0.03530764 ... -0.04230448 -0.0414599
 -0.04527015] 22050


  1%|▊                                                                                 | 3/299 [00:10<17:39,  3.58s/it]

[ 0.00283427  0.00423394  0.0036414  ... -0.01369482 -0.01395124
 -0.01601286] 22050


  1%|█                                                                                 | 4/299 [00:14<17:14,  3.51s/it]

[-0.2545665  -0.37054616 -0.3232944  ... -0.05147256 -0.04832996
 -0.0513258 ] 22050


  2%|█▎                                                                                | 5/299 [00:17<17:02,  3.48s/it]

[ 3.1871754e-05  6.1540527e-06 -3.7155998e-05 ... -1.4125325e-02
 -8.7606525e-03  0.0000000e+00] 22050


  2%|█▋                                                                                | 6/299 [00:19<14:19,  2.93s/it]

[ 0.00079253  0.00089992  0.00091092 ... -0.0049351  -0.00259066
  0.        ] 22050


  2%|█▉                                                                                | 7/299 [00:22<15:32,  3.19s/it]

[ 3.0208554e-05  3.0756044e-05  2.5381032e-05 ... -1.8259089e-02
 -1.1751885e-02 -5.7575861e-03] 22050


  3%|██▏                                                                               | 8/299 [00:25<14:38,  3.02s/it]

[-0.00064508 -0.00077814 -0.0008623  ... -0.01482992 -0.00782498
  0.        ] 22050


  3%|██▍                                                                               | 9/299 [00:27<13:34,  2.81s/it]

[ 0.00110417  0.00130484  0.00140896 ... -0.01235658 -0.00798214
 -0.00392708] 22050


  3%|██▋                                                                              | 10/299 [00:31<14:39,  3.04s/it]

[ 4.3292630e-07  3.4875336e-06  7.9502988e-06 ... -4.9829770e-02
 -2.8054921e-02  0.0000000e+00] 22050


  4%|██▉                                                                              | 11/299 [00:35<16:07,  3.36s/it]

[0.00072087 0.00177281 0.00336674 ... 0.03278232 0.03167795 0.0341762 ] 22050


  4%|███▎                                                                             | 12/299 [00:39<17:32,  3.67s/it]

[-0.00511142 -0.00661265 -0.00532051 ...  0.05818591  0.05825811
  0.06405238] 22050


  4%|███▌                                                                             | 13/299 [00:43<18:02,  3.78s/it]

[ 0.13884057  0.20461525  0.18165357 ... -0.07205642 -0.07238604
 -0.08182055] 22050


  5%|███▊                                                                             | 14/299 [00:47<17:38,  3.72s/it]

[ 0.          0.          0.         ... -0.03222465 -0.02863552
 -0.02814007] 22050


  5%|████                                                                             | 15/299 [00:50<17:11,  3.63s/it]

[0.         0.         0.         ... 0.81409144 0.7837968  0.8404915 ] 22050


  5%|████▎                                                                            | 16/299 [00:54<17:10,  3.64s/it]

[0.         0.         0.         ... 0.2893713  0.28139624 0.3021213 ] 22050


  6%|████▌                                                                            | 17/299 [00:58<17:05,  3.64s/it]

[ 0.          0.          0.         ... -0.15555128 -0.14919281
 -0.1552921 ] 22050


  6%|████▉                                                                            | 18/299 [01:01<16:37,  3.55s/it]

[0.         0.         0.         ... 0.02468135 0.02214165 0.01943384] 22050


  6%|█████▏                                                                           | 19/299 [01:04<15:46,  3.38s/it]

[ 0.          0.          0.         ... -0.34570888 -0.34052533
 -0.37189066] 22050


  7%|█████▍                                                                           | 20/299 [01:08<15:56,  3.43s/it]

[ 0.          0.          0.         ... -0.36525172 -0.35147998
 -0.3764349 ] 22050


  7%|█████▋                                                                           | 21/299 [01:11<15:34,  3.36s/it]

[0.         0.         0.         ... 0.29563662 0.29204592 0.32384074] 22050


  7%|█████▉                                                                           | 22/299 [01:14<14:42,  3.19s/it]

[ 0.          0.          0.         ... -0.87329555 -0.8426997
 -0.904122  ] 22050


  8%|██████▏                                                                          | 23/299 [01:17<14:29,  3.15s/it]

[0.         0.         0.         ... 0.08035016 0.07610521 0.08158155] 22050


  8%|██████▌                                                                          | 24/299 [01:19<13:23,  2.92s/it]

[0.         0.         0.         ... 0.07361161 0.07532007 0.08183191] 22050


  8%|██████▊                                                                          | 25/299 [01:23<14:36,  3.20s/it]

[ 0.          0.          0.         ... -0.05342972 -0.0532412
 -0.06048   ] 22050


  9%|███████                                                                          | 26/299 [01:26<14:09,  3.11s/it]

[0.         0.         0.         ... 0.48654523 0.47395992 0.5123876 ] 22050


  9%|███████▎                                                                         | 27/299 [01:28<13:17,  2.93s/it]

[0.         0.         0.         ... 0.01937228 0.01565968 0.01233602] 22050


  9%|███████▌                                                                         | 28/299 [01:31<13:00,  2.88s/it]

[0.         0.         0.         ... 0.21377535 0.19589575 0.19898888] 22050


 10%|███████▊                                                                         | 29/299 [01:35<14:17,  3.18s/it]

[ 0.          0.          0.         ... -0.03692322 -0.04029846
 -0.03779646] 22050


 10%|████████▏                                                                        | 30/299 [01:38<14:27,  3.22s/it]

[ 0.          0.          0.         ... -0.00111335  0.00120612
 -0.00136599] 22050


 10%|████████▍                                                                        | 31/299 [01:41<13:45,  3.08s/it]

[ 0.          0.          0.         ... -0.27843747 -0.2646894
 -0.28205138] 22050


 11%|████████▋                                                                        | 32/299 [01:44<14:03,  3.16s/it]

[ 0.          0.          0.         ... -0.26306844 -0.2522001
 -0.26922488] 22050


 11%|████████▉                                                                        | 33/299 [01:49<15:17,  3.45s/it]

[0.         0.         0.         ... 0.1735332  0.17125647 0.19119985] 22050


 11%|█████████▏                                                                       | 34/299 [01:52<15:57,  3.61s/it]

[ 0.          0.          0.         ... -0.2167718  -0.2080332
 -0.22265384] 22050


 12%|█████████▍                                                                       | 35/299 [01:57<17:04,  3.88s/it]

[ 0.          0.          0.         ... -0.05900886 -0.06246108
 -0.06871106] 22050


 12%|█████████▊                                                                       | 36/299 [02:00<15:51,  3.62s/it]

[0.         0.         0.         ... 0.7010785  0.68610245 0.7446819 ] 22050


 12%|██████████                                                                       | 37/299 [02:03<14:43,  3.37s/it]

[ 0.          0.          0.         ... -0.1005215  -0.09558512
 -0.09833872] 22050


 13%|██████████▎                                                                      | 38/299 [02:07<16:06,  3.70s/it]

[ 0.          0.          0.         ... -0.09970824 -0.10170659
 -0.11256789] 22050


 13%|██████████▌                                                                      | 39/299 [02:13<18:49,  4.34s/it]

[ 0.          0.          0.         ... -0.09393648 -0.0905112
 -0.09887574] 22050


 13%|██████████▊                                                                      | 40/299 [02:17<18:15,  4.23s/it]

[ 0.          0.          0.         ... -0.10736632 -0.10226438
 -0.10872729] 22050


 14%|███████████                                                                      | 41/299 [02:20<16:42,  3.89s/it]

[ 0.          0.          0.         ... -0.3698437  -0.36839765
 -0.4094729 ] 22050


 14%|███████████▍                                                                     | 42/299 [02:23<15:49,  3.69s/it]

[-0.00949201 -0.01515351 -0.01494985 ...  0.03122446  0.03000467
  0.03189378] 22050


 14%|███████████▋                                                                     | 43/299 [02:27<16:14,  3.81s/it]

[-1.7585522e-06 -2.2429733e-06 -1.9274846e-06 ... -1.1987473e-02
 -7.4312286e-03  0.0000000e+00] 22050


 15%|███████████▉                                                                     | 44/299 [02:31<16:07,  3.79s/it]

[-3.1364743e-05 -3.4258581e-05 -3.3931665e-05 ...  5.3538714e-04
  3.7836187e-04  0.0000000e+00] 22050


 15%|████████████▏                                                                    | 45/299 [02:34<15:04,  3.56s/it]

[-2.9586021e-05 -3.3629472e-05 -3.4923316e-05 ... -2.4650006e-03
 -1.3031738e-03  0.0000000e+00] 22050


 15%|████████████▍                                                                    | 46/299 [02:37<13:36,  3.23s/it]

[3.0384650e-05 3.1305051e-05 2.8012693e-05 ... 3.9614424e-02 2.4514157e-02
 0.0000000e+00] 22050


 16%|████████████▋                                                                    | 47/299 [02:39<12:26,  2.96s/it]

[-0.00015414 -0.00019182 -0.00021949 ...  0.02211454  0.01247506
  0.        ] 22050


 16%|█████████████                                                                    | 48/299 [02:42<12:07,  2.90s/it]

[2.9788309e-05 3.2301657e-05 3.1995405e-05 ... 1.5126610e-03 9.7192550e-04
 4.7570144e-04] 22050


 16%|█████████████▎                                                                   | 49/299 [02:45<12:31,  3.01s/it]

[-0.30551556 -0.337594   -0.35426965 ...  0.04488467  0.02582479
  0.        ] 22050


 17%|█████████████▌                                                                   | 50/299 [02:54<20:21,  4.91s/it]

[-0.30030748 -0.3313869  -0.3471481  ... -0.10257331 -0.06606323
 -0.03239066] 22050


 17%|█████████████▊                                                                   | 51/299 [02:58<18:13,  4.41s/it]

[-0.5566892  -0.61342674 -0.6413218  ... -0.07702224 -0.0493612
 -0.02408693] 22050


 17%|██████████████                                                                   | 52/299 [03:02<17:39,  4.29s/it]

[-0.87746686 -0.9691256  -1.0164407  ... -0.2245433  -0.14452285
 -0.07082193] 22050


 18%|██████████████▎                                                                  | 53/299 [03:06<17:18,  4.22s/it]

[-0.14500825 -0.16018207 -0.16798463 ...  0.11473081  0.06627245
  0.        ] 22050


 18%|██████████████▋                                                                  | 54/299 [03:17<25:38,  6.28s/it]

[-0.00199708 -0.00319508 -0.00331803 ... -0.00064225 -0.00038474
  0.        ] 22050


 18%|██████████████▉                                                                  | 55/299 [03:20<21:42,  5.34s/it]

[-0.00066345 -0.00110385 -0.00104151 ...  0.00647592  0.00655071
  0.        ] 22050


 19%|███████████████▏                                                                 | 56/299 [03:23<19:25,  4.80s/it]

[-0.2739319  -0.3025994  -0.31744638 ...  0.01044763  0.00608007
  0.        ] 22050


 19%|███████████████▍                                                                 | 57/299 [03:33<25:25,  6.31s/it]

[-0.06291798 -0.07026124 -0.07465484 ... -0.14951584 -0.09621288
 -0.04716552] 22050


 19%|███████████████▋                                                                 | 58/299 [03:38<22:52,  5.69s/it]

[-1.7918481e-06 -5.5685846e-06 -9.9844920e-06 ...  2.7333383e-02
  1.7636651e-02  8.6638099e-03] 22050


 20%|███████████████▉                                                                 | 59/299 [03:41<20:32,  5.14s/it]

[ 8.5524260e-07 -2.3861974e-06 -7.3340552e-06 ... -1.3542055e-01
 -8.7212533e-02 -4.2756353e-02] 22050


 20%|████████████████▎                                                                | 60/299 [03:46<19:29,  4.89s/it]

[-0.00027686 -0.00032779 -0.00035314 ... -0.03754111 -0.02402511
 -0.01169831] 22050


 20%|████████████████▌                                                                | 61/299 [03:49<17:29,  4.41s/it]

[-1.7565626e-06 -1.2353955e-06  5.4582960e-09 ... -2.6573552e-02
 -1.6467988e-02  0.0000000e+00] 22050


 21%|████████████████▊                                                                | 62/299 [03:51<14:15,  3.61s/it]

[0.000215   0.00023683 0.00023057 ... 0.0034874  0.00196025 0.        ] 22050


 21%|█████████████████                                                                | 63/299 [03:53<12:19,  3.14s/it]

[-3.0497395e-07  1.2244502e-06  3.1903026e-06 ... -9.8866746e-03
 -5.5146376e-03  0.0000000e+00] 22050


 21%|█████████████████▎                                                               | 64/299 [03:55<11:32,  2.95s/it]

[6.2300285e-05 7.5929711e-05 8.4309846e-05 ... 9.5062396e-03 5.8767227e-03
 0.0000000e+00] 22050


 22%|█████████████████▌                                                               | 65/299 [03:57<10:25,  2.67s/it]

[2.0636191e-06 5.3742210e-06 7.9173615e-06 ... 8.8258702e-03 5.2438602e-03
 0.0000000e+00] 22050


 22%|█████████████████▉                                                               | 66/299 [04:00<10:50,  2.79s/it]

[-1.5476845e-06 -1.4929913e-06  7.7756016e-07 ...  1.0041645e-03
  6.2980881e-04  0.0000000e+00] 22050


 22%|██████████████████▏                                                              | 67/299 [04:04<11:09,  2.88s/it]

[ 0.          0.          0.         ... -0.12468348 -0.1273278
 -0.14731203] 22050


 23%|██████████████████▍                                                              | 68/299 [04:07<11:50,  3.08s/it]

[ 0.          0.          0.         ... -0.02251784 -0.02150127
 -0.02269199] 22050


 23%|██████████████████▋                                                              | 69/299 [04:09<10:51,  2.83s/it]

[ 0.          0.          0.         ... -0.01567137 -0.01457954
 -0.0151326 ] 22050


 23%|██████████████████▉                                                              | 70/299 [04:14<12:55,  3.39s/it]

[0.         0.         0.         ... 0.06823757 0.06161449 0.0576618 ] 22050


 24%|███████████████████▏                                                             | 71/299 [04:17<12:46,  3.36s/it]

[ 0.          0.          0.         ... -0.0593754  -0.06029727
 -0.06811669] 22050


 24%|███████████████████▌                                                             | 72/299 [04:21<12:57,  3.43s/it]

[ 0.15286843  0.22476168  0.19892806 ... -0.01032892 -0.01059519
 -0.01229354] 22050


 24%|███████████████████▊                                                             | 73/299 [04:25<13:12,  3.50s/it]

[0.01386719 0.02011131 0.01776993 ... 0.00524451 0.00579907 0.        ] 22050


 25%|████████████████████                                                             | 74/299 [04:28<12:42,  3.39s/it]

[-0.00679656 -0.01003796 -0.00873371 ... -0.02517475 -0.03054456
  0.        ] 22050


 25%|████████████████████▎                                                            | 75/299 [04:31<12:39,  3.39s/it]

[ 0.00579983  0.00852321  0.00752403 ... -0.00082801 -0.00068914
 -0.00070964] 22050


 25%|████████████████████▌                                                            | 76/299 [04:34<12:37,  3.40s/it]

[-0.00053421 -0.00082033 -0.00076593 ... -0.00522986 -0.00525398
 -0.00585139] 22050


 26%|████████████████████▊                                                            | 77/299 [04:39<13:21,  3.61s/it]

[-2.8764509e-05 -3.0061437e-05 -2.9183469e-05 ... -1.0795601e-03
 -5.5044401e-04  0.0000000e+00] 22050


 26%|█████████████████████▏                                                           | 78/299 [04:41<12:06,  3.29s/it]

[-7.8413684e-08  9.5552173e-07  1.9807621e-06 ... -3.6296784e-03
 -2.0876050e-03  0.0000000e+00] 22050


 26%|█████████████████████▍                                                           | 79/299 [04:45<12:32,  3.42s/it]

[1.8421345e-06 3.9703418e-06 4.0728492e-06 ... 1.1935446e-03 6.8373588e-04
 0.0000000e+00] 22050


 27%|█████████████████████▋                                                           | 80/299 [04:47<10:56,  3.00s/it]

[-2.2084580e-06 -5.9585232e-06 -8.7529661e-06 ... -3.4101740e-02
 -2.1929748e-02 -1.0731890e-02] 22050


 27%|█████████████████████▉                                                           | 81/299 [04:50<10:46,  2.96s/it]

[-5.8840362e-07  2.2181875e-06  5.4235775e-06 ...  3.1400897e-02
  1.6541665e-02  0.0000000e+00] 22050


 27%|██████████████████████▏                                                          | 82/299 [04:52<09:42,  2.68s/it]

[ 5.9769508e-07  8.8926954e-06  2.1092692e-05 ... -1.6348783e-02
 -8.8511044e-03  0.0000000e+00] 22050


 28%|██████████████████████▍                                                          | 83/299 [04:53<08:08,  2.26s/it]

[ 0.00772112  0.01154974  0.01025985 ... -0.00331298 -0.00319685
 -0.0037348 ] 22050


 28%|██████████████████████▊                                                          | 84/299 [04:56<09:15,  2.58s/it]

[0.28596535 0.3158219  0.33115914 ... 0.08994886 0.05179574 0.        ] 22050


 28%|███████████████████████                                                          | 85/299 [05:07<17:23,  4.88s/it]

[-0.27563092 -0.30399603 -0.31818    ...  0.00215952  0.00126481
  0.        ] 22050


 29%|███████████████████████▎                                                         | 86/299 [05:17<23:32,  6.63s/it]

[0.03946353 0.04340422 0.04541007 ... 0.4538223  0.29210246 0.14312147] 22050


 29%|███████████████████████▌                                                         | 87/299 [05:29<28:43,  8.13s/it]

[-0.3726952  -0.41175988 -0.43205068 ... -0.15957749 -0.10276388
 -0.05036703] 22050


 29%|███████████████████████▊                                                         | 88/299 [05:39<30:44,  8.74s/it]

[-0.2810858  -0.31157294 -0.32829928 ... -0.1266794  -0.08168591
 -0.04014152] 22050


 30%|████████████████████████                                                         | 89/299 [05:49<31:46,  9.08s/it]

[-0.07494406 -0.10856454 -0.09363515 ...  0.01878147  0.01818044
  0.01986458] 22050


 30%|████████████████████████▍                                                        | 90/299 [05:53<26:22,  7.57s/it]

[ 0.03124345  0.04578807  0.04021889 ... -0.01389698 -0.01351108
 -0.01445538] 22050


 30%|████████████████████████▋                                                        | 91/299 [05:57<22:21,  6.45s/it]

[-0.02912769 -0.04266582 -0.03835926 ... -0.07225096 -0.07003564
 -0.07565343] 22050


 31%|████████████████████████▉                                                        | 92/299 [06:01<19:41,  5.71s/it]

[ 0.00182807  0.00246826  0.00192033 ... -0.00439787 -0.00413904
 -0.00436127] 22050


 31%|█████████████████████████▏                                                       | 93/299 [06:05<18:01,  5.25s/it]

[-0.06445651 -0.09444108 -0.08404209 ... -0.01689324 -0.01542289
 -0.01585781] 22050


 31%|█████████████████████████▍                                                       | 94/299 [06:09<16:12,  4.74s/it]

[0.06414742 0.09454045 0.08388222 ... 0.24822964 0.24023329 0.2587387 ] 22050


 32%|█████████████████████████▋                                                       | 95/299 [06:12<14:49,  4.36s/it]

[ 0.08259647  0.12127037  0.1070242  ... -0.02367939 -0.02266011
 -0.0243049 ] 22050


 32%|██████████████████████████                                                       | 96/299 [06:15<13:22,  3.95s/it]

[-0.0151329  -0.02294918 -0.0202172  ... -0.04157927 -0.04070212
 -0.04374132] 22050


 32%|██████████████████████████▎                                                      | 97/299 [06:19<12:46,  3.79s/it]

[-0.00485999 -0.00679087 -0.00545568 ...  0.01482467  0.0137242
  0.01388321] 22050


 33%|██████████████████████████▌                                                      | 98/299 [06:22<12:22,  3.69s/it]

[0.13323113 0.19474407 0.17157386 ... 0.08486681 0.08216646 0.08880045] 22050


 33%|██████████████████████████▊                                                      | 99/299 [06:25<11:44,  3.52s/it]

[0.02923446 0.04403316 0.04038239 ... 0.07650845 0.07465485 0.08051185] 22050


 33%|██████████████████████████▊                                                     | 100/299 [06:29<11:35,  3.49s/it]

[ 0.03005545  0.04300415  0.03662321 ... -0.0114797  -0.01104879
 -0.01202029] 22050


 34%|███████████████████████████                                                     | 101/299 [06:32<11:28,  3.48s/it]

[6.0555729e-05 7.3114075e-05 8.1377519e-05 ... 8.7227272e-03 4.8832153e-03
 0.0000000e+00] 22050


 34%|███████████████████████████▎                                                    | 102/299 [06:33<09:17,  2.83s/it]

[ 1.3562662e-06  9.4506561e-07 -8.5865324e-09 ...  3.3021986e-02
  1.8553611e-02  0.0000000e+00] 22050


 34%|███████████████████████████▌                                                    | 103/299 [06:35<08:04,  2.47s/it]

[6.1053885e-05 7.3011215e-05 8.0253209e-05 ... 5.3349137e-03 2.8286560e-03
 0.0000000e+00] 22050


 35%|███████████████████████████▊                                                    | 104/299 [06:37<07:33,  2.33s/it]

[ 6.7988680e-07 -5.5855821e-06 -1.5208361e-05 ...  1.3006850e-02
  6.8495930e-03  0.0000000e+00] 22050


 35%|████████████████████████████                                                    | 105/299 [06:39<07:05,  2.19s/it]

[-8.7546437e-07 -1.6883479e-06 -2.0232412e-06 ...  8.1363264e-03
  4.2472398e-03  0.0000000e+00] 22050


 35%|████████████████████████████▎                                                   | 106/299 [06:40<06:03,  1.88s/it]

[-2.2965232e-06  1.4332079e-05  3.7568196e-05 ... -5.9282253e-03
 -3.7157908e-03  0.0000000e+00] 22050


 36%|████████████████████████████▋                                                   | 107/299 [06:41<05:17,  1.65s/it]

[-0.05889978 -0.08439805 -0.07164766 ... -0.03685347 -0.03530446
 -0.03779959] 22050


 36%|████████████████████████████▉                                                   | 108/299 [06:44<06:50,  2.15s/it]

[-0.00703423 -0.01040334 -0.00912582 ...  0.08334509  0.08262308
  0.08995433] 22050


 36%|█████████████████████████████▏                                                  | 109/299 [06:47<07:32,  2.38s/it]

[0.00841071 0.0121377  0.01047836 ... 0.01875647 0.01999779 0.        ] 22050


 37%|█████████████████████████████▍                                                  | 110/299 [06:51<08:29,  2.69s/it]

[-0.00168595 -0.00258133 -0.00231386 ...  0.00077115  0.0006065
  0.00061912] 22050


 37%|█████████████████████████████▋                                                  | 111/299 [06:54<09:01,  2.88s/it]

[ 0.00833424  0.01223366  0.01093073 ... -0.02901728 -0.02817109
 -0.03024289] 22050


 37%|█████████████████████████████▉                                                  | 112/299 [06:57<09:29,  3.04s/it]

[ 0.          0.          0.         ... -0.09031238 -0.08735766
 -0.09306031] 22050


 38%|██████████████████████████████▏                                                 | 113/299 [07:01<09:32,  3.08s/it]

[0.         0.         0.         ... 0.00044038 0.00028749 0.00024897] 22050


 38%|██████████████████████████████▌                                                 | 114/299 [07:04<09:55,  3.22s/it]

[0.         0.         0.         ... 0.25428715 0.24422075 0.26595703] 22050


 38%|██████████████████████████████▊                                                 | 115/299 [07:08<10:06,  3.30s/it]

[ 0.          0.          0.         ... -0.18821347 -0.18663183
 -0.2047519 ] 22050


 39%|███████████████████████████████                                                 | 116/299 [07:11<10:23,  3.41s/it]

[0.         0.         0.         ... 0.63282675 0.60743105 0.6499869 ] 22050


 39%|███████████████████████████████▎                                                | 117/299 [07:15<10:18,  3.40s/it]

[ 0.          0.          0.         ... -0.15600103 -0.14905778
 -0.15698275] 22050


 39%|███████████████████████████████▌                                                | 118/299 [07:18<10:19,  3.42s/it]

[ 0.          0.          0.         ... -0.1499482  -0.14536801
 -0.15866049] 22050


 40%|███████████████████████████████▊                                                | 119/299 [07:22<10:11,  3.40s/it]

[ 0.          0.          0.         ... -0.03819335 -0.03791534
 -0.04188127] 22050


 40%|████████████████████████████████                                                | 120/299 [07:25<10:23,  3.48s/it]

[ 0.          0.          0.         ... -0.06268332 -0.06022708
 -0.06461953] 22050


 40%|████████████████████████████████▎                                               | 121/299 [07:29<10:13,  3.45s/it]

[ 0.          0.          0.         ... -0.28731927 -0.2788944
 -0.3043653 ] 22050


 41%|████████████████████████████████▋                                               | 122/299 [07:32<10:07,  3.43s/it]

[ 0.          0.          0.         ... -0.12467527 -0.11601477
 -0.12351672] 22050


 41%|████████████████████████████████▉                                               | 123/299 [07:37<11:20,  3.87s/it]

[ 0.          0.          0.         ... -0.3117757  -0.30287907
 -0.32905123] 22050


 41%|█████████████████████████████████▏                                              | 124/299 [07:42<12:34,  4.31s/it]

[ 0.          0.          0.         ... -0.60128844 -0.5866989
 -0.6393383 ] 22050


 42%|█████████████████████████████████▍                                              | 125/299 [07:47<12:41,  4.38s/it]

[ 0.          0.          0.         ... -0.09460735 -0.09186393
 -0.10033422] 22050


 42%|█████████████████████████████████▋                                              | 126/299 [07:51<12:17,  4.26s/it]

[0.         0.         0.         ... 0.06824436 0.06823804 0.07497056] 22050


 42%|█████████████████████████████████▉                                              | 127/299 [07:55<11:59,  4.18s/it]

[ 0.          0.          0.         ... -0.02098945 -0.01939385
 -0.01919075] 22050


 43%|██████████████████████████████████▏                                             | 128/299 [07:59<12:01,  4.22s/it]

[0.         0.         0.         ... 0.0570341  0.05582925 0.0643122 ] 22050


 43%|██████████████████████████████████▌                                             | 129/299 [08:04<12:18,  4.34s/it]

[0.         0.         0.         ... 0.10997557 0.11245404 0.13821203] 22050


 43%|██████████████████████████████████▊                                             | 130/299 [08:10<13:48,  4.90s/it]

[ 0.          0.          0.         ... -0.27762765 -0.265448
 -0.2814702 ] 22050


 44%|███████████████████████████████████                                             | 131/299 [08:16<14:45,  5.27s/it]

[0.         0.         0.         ... 0.65125763 0.62605083 0.67070335] 22050


 44%|███████████████████████████████████▎                                            | 132/299 [08:21<14:29,  5.21s/it]

[ 0.          0.          0.         ... -0.00710362  0.01155034
  0.03047679] 22050


 44%|███████████████████████████████████▌                                            | 133/299 [08:26<14:16,  5.16s/it]

[ 0.          0.          0.         ... -0.04220781 -0.0425578
 -0.04848582] 22050


 45%|███████████████████████████████████▊                                            | 134/299 [08:32<14:29,  5.27s/it]

[ 0.          0.          0.         ... -0.01046014 -0.00814273
 -0.0058492 ] 22050


 45%|████████████████████████████████████                                            | 135/299 [08:36<13:41,  5.01s/it]

[0.         0.         0.         ... 0.06659431 0.06493407 0.07325058] 22050


 45%|████████████████████████████████████▍                                           | 136/299 [08:39<12:20,  4.54s/it]

[ 0.          0.          0.         ... -0.09697435 -0.09404793
 -0.1009122 ] 22050


 46%|████████████████████████████████████▋                                           | 137/299 [08:43<11:50,  4.38s/it]

[0.         0.         0.         ... 0.04830315 0.04316428 0.04473874] 22050


 46%|████████████████████████████████████▉                                           | 138/299 [08:47<10:56,  4.08s/it]

[0.         0.         0.         ... 0.12839343 0.12455406 0.13296343] 22050


 46%|█████████████████████████████████████▏                                          | 139/299 [08:50<10:05,  3.78s/it]

[ 0.          0.          0.         ... -0.10614821 -0.10306031
 -0.11080159] 22050


 47%|█████████████████████████████████████▍                                          | 140/299 [08:53<09:44,  3.68s/it]

[ 0.          0.          0.         ... -0.04283782 -0.04240255
 -0.0454677 ] 22050


 47%|█████████████████████████████████████▋                                          | 141/299 [08:57<09:19,  3.54s/it]

[0.         0.         0.         ... 0.08306429 0.08193642 0.09004958] 22050


 47%|█████████████████████████████████████▉                                          | 142/299 [09:00<09:03,  3.46s/it]

[0.         0.         0.         ... 0.05440215 0.05421929 0.06178407] 22050


 48%|██████████████████████████████████████▎                                         | 143/299 [09:03<09:05,  3.49s/it]

[ 0.          0.          0.         ... -0.14653698 -0.14106536
 -0.14908496] 22050


 48%|██████████████████████████████████████▌                                         | 144/299 [09:08<09:30,  3.68s/it]

[ 0.          0.          0.         ... -0.2712792  -0.2602289
 -0.27644926] 22050


 48%|██████████████████████████████████████▊                                         | 145/299 [09:12<10:02,  3.91s/it]

[0.         0.         0.         ... 0.0585855  0.05834712 0.06446683] 22050


 49%|███████████████████████████████████████                                         | 146/299 [09:16<09:50,  3.86s/it]

[0.         0.         0.         ... 0.09014577 0.08732708 0.09365366] 22050


 49%|███████████████████████████████████████▎                                        | 147/299 [09:19<09:18,  3.68s/it]

[0.         0.         0.         ... 0.1488721  0.14210069 0.15414882] 22050


 49%|███████████████████████████████████████▌                                        | 148/299 [09:22<08:52,  3.52s/it]

[ 0.          0.          0.         ... -0.01634077 -0.01284211
 -0.00887103] 22050


 50%|███████████████████████████████████████▊                                        | 149/299 [09:26<08:55,  3.57s/it]

[0.         0.         0.         ... 0.03140324 0.02938446 0.03127927] 22050


 50%|████████████████████████████████████████▏                                       | 150/299 [09:30<09:37,  3.88s/it]

[0.         0.         0.         ... 0.06877434 0.06657933 0.07092424] 22050


 51%|████████████████████████████████████████▍                                       | 151/299 [09:34<09:17,  3.76s/it]

[0.         0.         0.         ... 0.04315259 0.04266706 0.04637334] 22050


 51%|████████████████████████████████████████▋                                       | 152/299 [09:38<09:12,  3.76s/it]

[0.         0.         0.         ... 0.13846196 0.13753016 0.15601401] 22050


 51%|████████████████████████████████████████▉                                       | 153/299 [09:42<09:19,  3.84s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 52%|█████████████████████████████████████████▏                                      | 154/299 [09:46<09:25,  3.90s/it]

[ 0.          0.          0.         ... -0.853009   -0.826511
 -0.89554524] 22050


 52%|█████████████████████████████████████████▍                                      | 155/299 [09:50<09:22,  3.90s/it]

[0.         0.         0.         ... 0.7048063  0.68563855 0.7389971 ] 22050


 52%|█████████████████████████████████████████▋                                      | 156/299 [09:55<10:14,  4.29s/it]

[ 0.          0.          0.         ... -0.0597242  -0.05913943
 -0.06880321] 22050


 53%|██████████████████████████████████████████                                      | 157/299 [10:00<10:35,  4.47s/it]

[ 0.          0.          0.         ... -0.04255615 -0.03158521
 -0.034418  ] 22050


 53%|██████████████████████████████████████████▎                                     | 158/299 [10:04<10:26,  4.44s/it]

[ 0.          0.          0.         ... -0.12110092 -0.1101577
 -0.1219567 ] 22050


 53%|██████████████████████████████████████████▌                                     | 159/299 [10:09<10:40,  4.57s/it]

[0.         0.         0.         ... 0.03321154 0.03474576 0.03959534] 22050


 54%|██████████████████████████████████████████▊                                     | 160/299 [10:14<10:40,  4.61s/it]

[ 0.          0.          0.         ... -0.00967131 -0.0093653
 -0.01004385] 22050


 54%|███████████████████████████████████████████                                     | 161/299 [10:18<10:13,  4.45s/it]

[0.         0.         0.         ... 0.00452353 0.00422161 0.00407965] 22050


 54%|███████████████████████████████████████████▎                                    | 162/299 [10:22<09:52,  4.32s/it]

[0.         0.         0.         ... 0.00405493 0.0042079  0.00498438] 22050


 55%|███████████████████████████████████████████▌                                    | 163/299 [10:26<09:59,  4.41s/it]

[ 0.          0.          0.         ... -0.06538848 -0.0640373
 -0.07016253] 22050


 55%|███████████████████████████████████████████▉                                    | 164/299 [10:32<10:24,  4.62s/it]

[ 0.          0.          0.         ... -0.06714011 -0.06459182
 -0.07058822] 22050


 55%|████████████████████████████████████████████▏                                   | 165/299 [10:36<10:32,  4.72s/it]

[ 0.          0.          0.         ... -0.0976808  -0.09131095
 -0.1009459 ] 22050


 56%|████████████████████████████████████████████▍                                   | 166/299 [10:43<11:36,  5.24s/it]

[ 0.          0.          0.         ... -0.24246328 -0.23364931
 -0.2513686 ] 22050


 56%|████████████████████████████████████████████▋                                   | 167/299 [10:48<11:23,  5.18s/it]

[ 0.          0.          0.         ... -0.07716538 -0.07356218
 -0.08140326] 22050


 56%|████████████████████████████████████████████▉                                   | 168/299 [10:53<10:56,  5.01s/it]

[ 0.          0.          0.         ... -0.12482095 -0.11627863
 -0.12246422] 22050


 57%|█████████████████████████████████████████████▏                                  | 169/299 [10:56<09:56,  4.59s/it]

[ 0.          0.          0.         ... -0.01074216 -0.01034736
 -0.01125017] 22050


 57%|█████████████████████████████████████████████▍                                  | 170/299 [11:00<09:41,  4.50s/it]

[0.         0.         0.         ... 0.24655572 0.23584485 0.24982773] 22050


 57%|█████████████████████████████████████████████▊                                  | 171/299 [11:04<09:16,  4.35s/it]

[0.         0.         0.         ... 0.12076917 0.1194012  0.12977952] 22050


 58%|██████████████████████████████████████████████                                  | 172/299 [11:09<09:03,  4.28s/it]

[0.         0.         0.         ... 0.00541603 0.00534779 0.00361776] 22050


 58%|██████████████████████████████████████████████▎                                 | 173/299 [11:13<08:53,  4.23s/it]

[0.         0.         0.         ... 0.00590403 0.00539305 0.00577536] 22050


 58%|██████████████████████████████████████████████▌                                 | 174/299 [11:16<08:18,  3.99s/it]

[ 0.          0.          0.         ... -0.1507879  -0.14893688
 -0.17197357] 22050


 59%|██████████████████████████████████████████████▊                                 | 175/299 [11:20<07:55,  3.84s/it]

[0.         0.         0.         ... 0.04399489 0.04110481 0.0455402 ] 22050


 59%|███████████████████████████████████████████████                                 | 176/299 [11:23<07:46,  3.79s/it]

[ 0.          0.          0.         ... -0.03041141 -0.03024904
 -0.03383819] 22050


 59%|███████████████████████████████████████████████▎                                | 177/299 [11:27<07:30,  3.70s/it]

[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 3.49719558e-05
 1.04438295e-04 4.18424490e-04] 22050


 60%|███████████████████████████████████████████████▋                                | 178/299 [11:31<08:00,  3.97s/it]

[0.08209334 0.12027321 0.10592982 ... 0.09523189 0.09189781 0.09868933] 22050


 60%|███████████████████████████████████████████████▉                                | 179/299 [11:35<07:47,  3.90s/it]

[ 0.00025519  0.00028764  0.00014868 ... -0.00348902 -0.00338399
 -0.0036069 ] 22050


 60%|████████████████████████████████████████████████▏                               | 180/299 [11:39<07:36,  3.83s/it]

[-0.01997385 -0.02963021 -0.02664766 ... -0.02849923 -0.02836062
 -0.03160037] 22050


 61%|████████████████████████████████████████████████▍                               | 181/299 [11:43<07:29,  3.81s/it]

[ 0.          0.          0.         ... -0.5391371  -0.52193433
 -0.5663463 ] 22050


 61%|████████████████████████████████████████████████▋                               | 182/299 [11:46<07:16,  3.73s/it]

[0.         0.         0.         ... 0.03783033 0.03612902 0.03943321] 22050


 61%|████████████████████████████████████████████████▉                               | 183/299 [11:49<07:00,  3.63s/it]

[0.         0.         0.         ... 0.04257868 0.0448944  0.05588475] 22050


 62%|█████████████████████████████████████████████████▏                              | 184/299 [11:54<07:18,  3.82s/it]

[0.         0.         0.         ... 0.05401823 0.05287353 0.05755837] 22050


 62%|█████████████████████████████████████████████████▍                              | 185/299 [11:58<07:21,  3.88s/it]

[0.         0.         0.         ... 0.09213886 0.09398716 0.10088132] 22050


 62%|█████████████████████████████████████████████████▊                              | 186/299 [12:02<07:20,  3.90s/it]

[0.         0.         0.         ... 0.11685472 0.1111599  0.11944976] 22050


 63%|██████████████████████████████████████████████████                              | 187/299 [12:06<07:15,  3.89s/it]

[0.         0.         0.         ... 0.4792076  0.45526347 0.49092004] 22050


 63%|██████████████████████████████████████████████████▎                             | 188/299 [12:10<07:16,  3.93s/it]

[ 0.          0.          0.         ... -0.01120818 -0.00803506
 -0.01138652] 22050


 63%|██████████████████████████████████████████████████▌                             | 189/299 [12:14<07:19,  4.00s/it]

[ 0.          0.          0.         ... -0.05364962 -0.05210137
 -0.055831  ] 22050


 64%|██████████████████████████████████████████████████▊                             | 190/299 [12:18<07:31,  4.14s/it]

[0.         0.         0.         ... 0.87999165 0.8438236  0.9057113 ] 22050


 64%|███████████████████████████████████████████████████                             | 191/299 [12:22<07:24,  4.12s/it]

[0.         0.         0.         ... 0.22386    0.21816497 0.23659104] 22050


 64%|███████████████████████████████████████████████████▎                            | 192/299 [12:26<07:18,  4.10s/it]

[0.        0.        0.        ... 0.9459605 0.9187443 0.9850489] 22050


 65%|███████████████████████████████████████████████████▋                            | 193/299 [12:31<07:31,  4.26s/it]

[ 0.          0.          0.         ... -0.03106961 -0.02864614
 -0.03651939] 22050


 65%|███████████████████████████████████████████████████▉                            | 194/299 [12:36<07:37,  4.36s/it]

[ 0.          0.          0.         ... -0.09009068 -0.09058654
 -0.10142617] 22050


 65%|████████████████████████████████████████████████████▏                           | 195/299 [12:40<07:25,  4.28s/it]

[ 0.          0.          0.         ... -0.953986   -0.92493206
 -0.98153687] 22050


 66%|████████████████████████████████████████████████████▍                           | 196/299 [12:46<08:12,  4.79s/it]

[ 0.          0.          0.         ... -0.15020148 -0.14647253
 -0.15748379] 22050


 66%|████████████████████████████████████████████████████▋                           | 197/299 [12:50<08:04,  4.75s/it]

[ 0.          0.          0.         ... -0.12514465 -0.12138256
 -0.12777631] 22050


 66%|████████████████████████████████████████████████████▉                           | 198/299 [12:55<07:45,  4.61s/it]

[ 0.          0.          0.         ... -0.0088842  -0.00718911
 -0.00901421] 22050


 67%|█████████████████████████████████████████████████████▏                          | 199/299 [13:00<08:02,  4.83s/it]

[0.         0.         0.         ... 0.08539807 0.08473286 0.09463313] 22050


 67%|█████████████████████████████████████████████████████▌                          | 200/299 [13:05<08:08,  4.93s/it]

[0.04514384 0.06601427 0.05779665 ... 0.02462521 0.02394859 0.02566808] 22050


 67%|█████████████████████████████████████████████████████▊                          | 201/299 [13:11<08:42,  5.33s/it]

[ 0.01947135  0.02846876  0.02506434 ... -0.033544   -0.03245725
 -0.03468243] 22050


 68%|██████████████████████████████████████████████████████                          | 202/299 [13:16<08:11,  5.06s/it]

[0.12175424 0.17824209 0.15657128 ... 0.11341876 0.11023723 0.11999816] 22050


 68%|██████████████████████████████████████████████████████▎                         | 203/299 [13:20<07:55,  4.95s/it]

[0.00631607 0.00816058 0.00610981 ... 0.09044091 0.08813905 0.09586868] 22050


 68%|██████████████████████████████████████████████████████▌                         | 204/299 [13:25<07:30,  4.74s/it]

[-0.15628962 -0.22895335 -0.20168705 ... -0.03173079 -0.03226447
 -0.03650894] 22050


 69%|██████████████████████████████████████████████████████▊                         | 205/299 [13:29<07:14,  4.63s/it]

[0.1853947  0.27131873 0.23839961 ... 0.0437646  0.04377886 0.04920494] 22050


 69%|███████████████████████████████████████████████████████                         | 206/299 [13:33<06:44,  4.34s/it]

[0.18107037 0.26462144 0.23234265 ... 0.32034877 0.30916995 0.3323549 ] 22050


 69%|███████████████████████████████████████████████████████▍                        | 207/299 [13:37<06:30,  4.24s/it]

[-0.02087486 -0.03028057 -0.02663353 ...  0.0413494   0.03994204
  0.0426349 ] 22050


 70%|███████████████████████████████████████████████████████▋                        | 208/299 [13:40<05:59,  3.95s/it]

[ 0.03595075  0.04989659  0.04024421 ... -0.24192847 -0.23514697
 -0.2543003 ] 22050


 70%|███████████████████████████████████████████████████████▉                        | 209/299 [13:44<05:56,  3.96s/it]

[ 0.06172559  0.0904598   0.07956354 ... -0.1636615  -0.15869726
 -0.17139705] 22050


 70%|████████████████████████████████████████████████████████▏                       | 210/299 [13:48<05:48,  3.92s/it]

[-0.03135544 -0.04578738 -0.04026452 ...  0.04830543  0.04669622
  0.05010771] 22050


 71%|████████████████████████████████████████████████████████▍                       | 211/299 [13:52<05:48,  3.96s/it]

[-0.01032383 -0.01453805 -0.01170636 ...  0.06987031  0.06842768
  0.07429894] 22050


 71%|████████████████████████████████████████████████████████▋                       | 212/299 [13:56<05:38,  3.89s/it]

[ 0.07066288  0.10368585  0.09162885 ... -0.0461418  -0.04419601
 -0.0465932 ] 22050


 71%|████████████████████████████████████████████████████████▉                       | 213/299 [14:00<05:57,  4.16s/it]

[-0.10510142 -0.15434119 -0.13665253 ...  0.00354332  0.00412865
  0.00499887] 22050


 72%|█████████████████████████████████████████████████████████▎                      | 214/299 [14:04<05:28,  3.86s/it]

[-0.03397305 -0.04996506 -0.04397296 ...  0.03616295  0.03442479
  0.03606641] 22050


 72%|█████████████████████████████████████████████████████████▌                      | 215/299 [14:07<05:23,  3.85s/it]

[0.00048343 0.00073013 0.00074828 ... 0.04594715 0.04402352 0.0471474 ] 22050


 72%|█████████████████████████████████████████████████████████▊                      | 216/299 [14:11<05:04,  3.67s/it]

[ 0.224885    0.32932156  0.2899627  ... -0.05834039 -0.05618492
 -0.06026815] 22050


 73%|██████████████████████████████████████████████████████████                      | 217/299 [14:15<05:19,  3.89s/it]

[-0.07712042 -0.1130089  -0.09989832 ...  0.04327109  0.0418635
  0.04561923] 22050


 73%|██████████████████████████████████████████████████████████▎                     | 218/299 [14:19<05:26,  4.03s/it]

[-0.03549059 -0.05269979 -0.04721371 ... -0.13843057 -0.13402462
 -0.14437081] 22050


 73%|██████████████████████████████████████████████████████████▌                     | 219/299 [14:23<05:15,  3.94s/it]

[0.02330435 0.03429922 0.03047918 ... 0.02959513 0.02840756 0.03028148] 22050


 74%|██████████████████████████████████████████████████████████▊                     | 220/299 [14:26<04:50,  3.68s/it]

[-0.04389535 -0.0649181  -0.05787742 ...  0.15056932  0.14504048
  0.15519336] 22050


 74%|███████████████████████████████████████████████████████████▏                    | 221/299 [14:31<05:04,  3.91s/it]

[0.         0.         0.         ... 0.06869866 0.06484786 0.07572741] 22050


 74%|███████████████████████████████████████████████████████████▍                    | 222/299 [14:34<04:56,  3.86s/it]

[0.         0.         0.         ... 0.06053632 0.07971119 0.08661738] 22050


 75%|███████████████████████████████████████████████████████████▋                    | 223/299 [14:39<05:02,  3.98s/it]

[0.         0.         0.         ... 0.19320235 0.17706984 0.18313724] 22050


 75%|███████████████████████████████████████████████████████████▉                    | 224/299 [14:43<05:01,  4.01s/it]

[0.         0.         0.         ... 0.08155401 0.0827576  0.08970284] 22050


 75%|████████████████████████████████████████████████████████████▏                   | 225/299 [14:47<04:57,  4.02s/it]

[0.         0.         0.         ... 0.38486943 0.3681868  0.39275822] 22050


 76%|████████████████████████████████████████████████████████████▍                   | 226/299 [14:51<04:47,  3.94s/it]

[0.         0.         0.         ... 0.10772336 0.10574576 0.10623769] 22050


 76%|████████████████████████████████████████████████████████████▋                   | 227/299 [14:55<04:50,  4.04s/it]

[0.         0.         0.         ... 0.04214108 0.03715343 0.03800107] 22050


 76%|█████████████████████████████████████████████████████████████                   | 228/299 [14:59<04:48,  4.06s/it]

[0.         0.         0.         ... 0.15521227 0.14677481 0.15593003] 22050


 77%|█████████████████████████████████████████████████████████████▎                  | 229/299 [15:04<05:14,  4.49s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


 77%|█████████████████████████████████████████████████████████████▌                  | 230/299 [15:10<05:23,  4.69s/it]

[0.         0.         0.         ... 0.08151314 0.07713719 0.09152706] 22050


 77%|█████████████████████████████████████████████████████████████▊                  | 231/299 [15:14<05:14,  4.62s/it]

[ 0.          0.          0.         ... -0.3917424  -0.37110776
 -0.3991456 ] 22050


 78%|██████████████████████████████████████████████████████████████                  | 232/299 [15:18<05:05,  4.56s/it]

[0.         0.         0.         ... 0.08050891 0.07564239 0.07922343] 22050


 78%|██████████████████████████████████████████████████████████████▎                 | 233/299 [15:24<05:12,  4.73s/it]

[ 0.          0.          0.         ... -0.5759593  -0.5520702
 -0.59178233] 22050


 78%|██████████████████████████████████████████████████████████████▌                 | 234/299 [15:28<04:58,  4.59s/it]

[0.         0.         0.         ... 0.40601084 0.39382565 0.4227301 ] 22050


 79%|██████████████████████████████████████████████████████████████▉                 | 235/299 [15:33<05:04,  4.76s/it]

[0.         0.         0.         ... 0.6122817  0.58529973 0.6405715 ] 22050


 79%|███████████████████████████████████████████████████████████████▏                | 236/299 [15:37<04:46,  4.56s/it]

[0.         0.         0.         ... 0.2661814  0.25699428 0.26891932] 22050


 79%|███████████████████████████████████████████████████████████████▍                | 237/299 [15:42<04:41,  4.54s/it]

[0.         0.         0.         ... 0.16818021 0.16085267 0.17989126] 22050


 80%|███████████████████████████████████████████████████████████████▋                | 238/299 [15:45<04:25,  4.35s/it]

[ 0.          0.          0.         ... -0.05958529 -0.05423374
 -0.05786638] 22050


 80%|███████████████████████████████████████████████████████████████▉                | 239/299 [15:50<04:16,  4.27s/it]

[0.         0.         0.         ... 0.541714   0.5261556  0.56970155] 22050


 80%|████████████████████████████████████████████████████████████████▏               | 240/299 [15:53<03:57,  4.02s/it]

[0.         0.         0.         ... 0.15760067 0.14828913 0.15459237] 22050


 81%|████████████████████████████████████████████████████████████████▍               | 241/299 [15:58<04:05,  4.23s/it]

[ 0.          0.          0.         ... -0.10551623 -0.09428532
 -0.10726903] 22050


 81%|████████████████████████████████████████████████████████████████▋               | 242/299 [16:01<03:50,  4.04s/it]

[ 0.          0.          0.         ... -0.1540732  -0.14363897
 -0.16802943] 22050


 81%|█████████████████████████████████████████████████████████████████               | 243/299 [16:05<03:37,  3.89s/it]

[0.         0.         0.         ... 0.08215027 0.07461631 0.07744326] 22050


 82%|█████████████████████████████████████████████████████████████████▎              | 244/299 [16:08<03:21,  3.67s/it]

[ 0.          0.          0.         ... -0.10069733 -0.0970569
 -0.10444666] 22050


 82%|█████████████████████████████████████████████████████████████████▌              | 245/299 [16:12<03:20,  3.72s/it]

[ 0.          0.          0.         ... -0.0056017  -0.00158101
 -0.00499161] 22050


 82%|█████████████████████████████████████████████████████████████████▊              | 246/299 [16:16<03:17,  3.73s/it]

[ 0.          0.          0.         ... -0.04706489 -0.05189802
 -0.05370488] 22050


 83%|██████████████████████████████████████████████████████████████████              | 247/299 [16:19<03:12,  3.70s/it]

[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  7.0181406e-05
 -1.1087143e-04 -3.7962562e-04] 22050


 83%|██████████████████████████████████████████████████████████████████▎             | 248/299 [16:22<02:59,  3.52s/it]

[6.0634571e-05 5.8885256e-05 4.5460369e-05 ... 1.8835057e-03 1.1092690e-03
 0.0000000e+00] 22050


 83%|██████████████████████████████████████████████████████████████████▌             | 249/299 [16:25<02:46,  3.34s/it]

[-2.4712881e-06 -5.1638103e-06 -6.9168277e-06 ... -2.6756365e-04
 -3.7583763e-05  0.0000000e+00] 22050


 84%|██████████████████████████████████████████████████████████████████▉             | 250/299 [16:28<02:29,  3.05s/it]

[3.0095798e-05 3.6245452e-05 4.1038627e-05 ... 1.8093728e-02 9.8271910e-03
 0.0000000e+00] 22050


 84%|███████████████████████████████████████████████████████████████████▏            | 251/299 [16:31<02:26,  3.05s/it]

[ 0.00052289  0.00053874  0.00046727 ... -0.01250761 -0.00773672
  0.        ] 22050


 84%|███████████████████████████████████████████████████████████████████▍            | 252/299 [16:32<02:01,  2.58s/it]

[-7.9725692e-07 -5.1435914e-06 -1.1148565e-05 ...  8.1616104e-02
  5.0180554e-02  0.0000000e+00] 22050


 85%|███████████████████████████████████████████████████████████████████▋            | 253/299 [16:34<01:52,  2.44s/it]

[-8.4280538e-07 -2.8361271e-06 -4.4394942e-06 ... -2.2870742e-03
 -1.5083579e-03 -7.5765629e-04] 22050


 85%|███████████████████████████████████████████████████████████████████▉            | 254/299 [16:36<01:45,  2.35s/it]

[0.04097231 0.06046491 0.05393831 ... 0.06758201 0.0656415  0.07101809] 22050


 85%|████████████████████████████████████████████████████████████████████▏           | 255/299 [16:40<02:02,  2.79s/it]

[0.14633565 0.21431813 0.1891213  ... 0.06799984 0.06604503 0.07172802] 22050


 86%|████████████████████████████████████████████████████████████████████▍           | 256/299 [16:44<02:11,  3.06s/it]

[-0.21283041 -0.31201988 -0.27520728 ...  0.09969999  0.09652264
  0.10397127] 22050


 86%|████████████████████████████████████████████████████████████████████▊           | 257/299 [16:48<02:17,  3.28s/it]

[ 0.24943277  0.36582845  0.32237023 ... -0.12260514 -0.11850586
 -0.12716296] 22050


 86%|█████████████████████████████████████████████████████████████████████           | 258/299 [16:52<02:21,  3.46s/it]

[ 0.00150154  0.00224524  0.00197812 ... -0.00079957 -0.0008043
 -0.00093849] 22050


 87%|█████████████████████████████████████████████████████████████████████▎          | 259/299 [16:56<02:32,  3.81s/it]

[-0.10364083 -0.15188637 -0.13410126 ... -0.00882632 -0.00849731
 -0.00917868] 22050


 87%|█████████████████████████████████████████████████████████████████████▌          | 260/299 [17:00<02:25,  3.73s/it]

[-1.4861421e-04 -1.3037902e-04  2.5037663e-05 ...  1.4510831e-03
  1.3408809e-03  1.3899795e-03] 22050


 87%|█████████████████████████████████████████████████████████████████████▊          | 261/299 [17:04<02:23,  3.77s/it]

[-0.00583808 -0.00877954 -0.00792479 ...  0.00369963  0.0036003
  0.00391275] 22050


 88%|██████████████████████████████████████████████████████████████████████          | 262/299 [17:07<02:18,  3.74s/it]

[0.00212975 0.00305085 0.00268819 ... 0.00175668 0.00171111 0.00161446] 22050


 88%|██████████████████████████████████████████████████████████████████████▎         | 263/299 [17:11<02:16,  3.78s/it]

[-2.5228692e-05 -3.4271841e-05 -7.0419483e-05 ... -2.7906429e-04
 -2.4921342e-04 -1.7429724e-04] 22050


 88%|██████████████████████████████████████████████████████████████████████▋         | 264/299 [17:15<02:14,  3.83s/it]

[-0.00123752 -0.00179152 -0.00154062 ...  0.00876638  0.00853806
  0.00904136] 22050


 89%|██████████████████████████████████████████████████████████████████████▉         | 265/299 [17:19<02:14,  3.95s/it]

[ 0.01017988  0.01540918  0.01426247 ... -0.00534863 -0.00529241
 -0.0056529 ] 22050


 89%|███████████████████████████████████████████████████████████████████████▏        | 266/299 [17:23<02:06,  3.84s/it]

[-0.00048234 -0.00067872 -0.00056381 ...  0.00065122  0.00067135
  0.00079721] 22050


 89%|███████████████████████████████████████████████████████████████████████▍        | 267/299 [17:27<02:09,  4.04s/it]

[-0.00702536 -0.01071104 -0.00976045 ...  0.00861656  0.00821532
  0.00830283] 22050


 90%|███████████████████████████████████████████████████████████████████████▋        | 268/299 [17:31<02:03,  3.98s/it]

[ 0.06949438  0.10296931  0.09133144 ... -0.10478183 -0.09335198
 -0.08779476] 22050


 90%|███████████████████████████████████████████████████████████████████████▉        | 269/299 [17:36<02:07,  4.26s/it]

[-0.00247524 -0.00338435 -0.0025635  ...  0.0046447   0.00468008
  0.00582115] 22050


 90%|████████████████████████████████████████████████████████████████████████▏       | 270/299 [17:40<02:02,  4.21s/it]

[0.         0.         0.         ... 0.05332604 0.0519298  0.05410989] 22050


 91%|████████████████████████████████████████████████████████████████████████▌       | 271/299 [17:45<02:03,  4.43s/it]

[0.         0.         0.         ... 0.02862633 0.0279766  0.02985808] 22050


 91%|████████████████████████████████████████████████████████████████████████▊       | 272/299 [17:50<02:01,  4.50s/it]

[ 0.          0.          0.         ... -0.02789779 -0.02794547
 -0.03012433] 22050


 91%|█████████████████████████████████████████████████████████████████████████       | 273/299 [17:54<01:57,  4.53s/it]

[0.         0.         0.         ... 0.38324693 0.37273288 0.40365618] 22050


 92%|█████████████████████████████████████████████████████████████████████████▎      | 274/299 [17:59<01:53,  4.53s/it]

[ 0.          0.          0.         ... -0.1491216  -0.14584248
 -0.1557944 ] 22050


 92%|█████████████████████████████████████████████████████████████████████████▌      | 275/299 [18:05<01:55,  4.82s/it]

[ 0.          0.          0.         ... -0.11750941 -0.11472095
 -0.1250209 ] 22050


 92%|█████████████████████████████████████████████████████████████████████████▊      | 276/299 [18:08<01:41,  4.41s/it]

[ 0.          0.          0.         ... -0.20403463 -0.18978325
 -0.20266981] 22050


 93%|██████████████████████████████████████████████████████████████████████████      | 277/299 [18:11<01:31,  4.14s/it]

[0.         0.         0.         ... 0.02488784 0.02398541 0.02585169] 22050


 93%|██████████████████████████████████████████████████████████████████████████▍     | 278/299 [18:14<01:19,  3.78s/it]

[ 0.          0.          0.         ... -0.04918024 -0.04727224
 -0.05079426] 22050


 93%|██████████████████████████████████████████████████████████████████████████▋     | 279/299 [18:18<01:15,  3.79s/it]

[ 0.          0.          0.         ... -0.02247576 -0.02182411
 -0.02364616] 22050


 94%|██████████████████████████████████████████████████████████████████████████▉     | 280/299 [18:23<01:15,  3.97s/it]

[ 0.          0.          0.         ... -0.00385102 -0.00356616
 -0.00438928] 22050


 94%|███████████████████████████████████████████████████████████████████████████▏    | 281/299 [18:26<01:06,  3.72s/it]

[ 0.          0.          0.         ... -0.01381473 -0.01339422
 -0.01429898] 22050


 94%|███████████████████████████████████████████████████████████████████████████▍    | 282/299 [18:28<00:56,  3.35s/it]

[0.         0.         0.         ... 0.00366578 0.003711   0.0038881 ] 22050


 95%|███████████████████████████████████████████████████████████████████████████▋    | 283/299 [18:32<00:54,  3.43s/it]

[0.         0.         0.         ... 0.05284447 0.05143116 0.05646055] 22050


 95%|███████████████████████████████████████████████████████████████████████████▉    | 284/299 [18:35<00:48,  3.21s/it]

[0.         0.         0.         ... 0.05651337 0.05371975 0.05820636] 22050


 95%|████████████████████████████████████████████████████████████████████████████▎   | 285/299 [18:38<00:46,  3.29s/it]

[0.         0.         0.         ... 0.04609819 0.04592153 0.05157307] 22050


 96%|████████████████████████████████████████████████████████████████████████████▌   | 286/299 [18:42<00:44,  3.42s/it]

[0.         0.         0.         ... 0.00381485 0.00358559 0.00379743] 22050


 96%|████████████████████████████████████████████████████████████████████████████▊   | 287/299 [18:46<00:44,  3.72s/it]

[0.         0.         0.         ... 0.01049323 0.01007894 0.0108813 ] 22050


 96%|█████████████████████████████████████████████████████████████████████████████   | 288/299 [18:49<00:38,  3.49s/it]

[ 0.          0.          0.         ... -0.04439837 -0.04435356
 -0.04795394] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▎  | 289/299 [18:52<00:34,  3.41s/it]

[0.         0.         0.         ... 0.13611339 0.1388976  0.16161406] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▌  | 290/299 [18:55<00:28,  3.20s/it]

[ 0.          0.          0.         ... -0.02621428 -0.02754864
 -0.03301692] 22050


 97%|█████████████████████████████████████████████████████████████████████████████▊  | 291/299 [18:59<00:27,  3.39s/it]

[ 0.          0.          0.         ... -0.14282164 -0.13467892
 -0.1418872 ] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▏ | 292/299 [19:02<00:23,  3.29s/it]

[0.         0.         0.         ... 0.08933409 0.08854256 0.09726086] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▍ | 293/299 [19:05<00:18,  3.14s/it]

[0.         0.         0.         ... 0.16736001 0.16158195 0.17509419] 22050


 98%|██████████████████████████████████████████████████████████████████████████████▋ | 294/299 [19:08<00:15,  3.11s/it]

[ 0.          0.          0.         ... -0.0342821  -0.03772558
 -0.04044783] 22050


 99%|██████████████████████████████████████████████████████████████████████████████▉ | 295/299 [19:12<00:13,  3.34s/it]

[0.         0.         0.         ... 0.09482074 0.09676798 0.11037613] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▏| 296/299 [19:14<00:09,  3.16s/it]

[0.         0.         0.         ... 0.16828157 0.17618534 0.18312804] 22050


 99%|███████████████████████████████████████████████████████████████████████████████▍| 297/299 [19:18<00:06,  3.35s/it]

[ 0.          0.          0.         ... -0.06649059 -0.05748048
 -0.06334422] 22050


100%|███████████████████████████████████████████████████████████████████████████████▋| 298/299 [19:21<00:03,  3.20s/it]

[0.         0.         0.         ... 0.6694105  0.65764457 0.71868986] 22050


100%|████████████████████████████████████████████████████████████████████████████████| 299/299 [19:24<00:00,  3.09s/it]

[ 0.          0.          0.         ... -0.08037883 -0.07979045
 -0.08560699] 22050


done loading train mfcc


  0%|                                                                                           | 0/85 [00:00<?, ?it/s]

[ 0.          0.          0.         ... -0.15097117 -0.14199436
 -0.15616187] 22050


  2%|█▉                                                                                 | 2/85 [00:03<02:12,  1.59s/it]

[ 0.         0.         0.        ... -1.0097102 -0.9775502 -1.0539925] 22050


  4%|██▉                                                                                | 3/85 [00:06<02:58,  2.18s/it]

[0.         0.         0.         ... 0.11905885 0.1190711  0.13462272] 22050


  5%|███▉                                                                               | 4/85 [00:09<03:20,  2.47s/it]

[ 0.          0.          0.         ... -0.14376757 -0.14634912
 -0.16929877] 22050


  6%|████▉                                                                              | 5/85 [00:13<03:40,  2.75s/it]

[0.        0.        0.        ... 0.2842634 0.2742911 0.2978991] 22050


  7%|█████▊                                                                             | 6/85 [00:16<03:58,  3.02s/it]

[ 0.          0.          0.         ... -1.0097158  -0.97754306
 -1.0540003 ] 22050


  8%|██████▊                                                                            | 7/85 [00:20<04:03,  3.13s/it]

[ 0.          0.          0.         ... -0.5240373  -0.51735884
 -0.5599158 ] 22050


  9%|███████▊                                                                           | 8/85 [00:23<04:02,  3.15s/it]

[ 0.          0.          0.         ... -0.24339022 -0.23302886
 -0.24892566] 22050


 11%|████████▊                                                                          | 9/85 [00:27<04:16,  3.38s/it]

[0.         0.         0.         ... 0.07006744 0.06390787 0.06843111] 22050


 12%|█████████▋                                                                        | 10/85 [00:31<04:30,  3.60s/it]

[0.         0.         0.         ... 0.23463461 0.22792263 0.26713893] 22050


 13%|██████████▌                                                                       | 11/85 [00:36<04:46,  3.87s/it]

[0.         0.         0.         ... 0.20498481 0.20232959 0.22086047] 22050


 14%|███████████▌                                                                      | 12/85 [00:40<04:56,  4.07s/it]

[-0.00283933 -0.00401512 -0.00344597 ...  0.0097526   0.01072497
  0.        ] 22050


 15%|████████████▌                                                                     | 13/85 [00:46<05:23,  4.50s/it]

[-0.02181281 -0.03193489 -0.02826805 ...  0.00575696  0.00659533
  0.        ] 22050


 16%|█████████████▌                                                                    | 14/85 [00:51<05:44,  4.85s/it]

[ 0.00773429  0.01167202  0.01085229 ... -0.00154025 -0.00176283
  0.        ] 22050


 18%|██████████████▍                                                                   | 15/85 [00:56<05:32,  4.75s/it]

[-9.4293209e-04 -1.5129785e-03 -1.3976007e-03 ...  2.1218079e-04
  7.5372486e-07  0.0000000e+00] 22050


 19%|███████████████▍                                                                  | 16/85 [01:01<05:30,  4.79s/it]

[ 0.0016893   0.00271707  0.00256709 ... -0.00106804 -0.00115121
  0.        ] 22050


 20%|████████████████▍                                                                 | 17/85 [01:06<05:29,  4.84s/it]

[-8.8425225e-04 -1.0659160e-03 -8.0528628e-04 ... -4.2387831e-04
 -5.7793855e-05  0.0000000e+00] 22050


 21%|█████████████████▎                                                                | 18/85 [01:10<05:15,  4.70s/it]

[0.01710793 0.02544549 0.0228809  ... 0.04074765 0.03925414 0.04185763] 22050


 22%|██████████████████▎                                                               | 19/85 [01:14<04:58,  4.53s/it]

[ 0.          0.          0.         ... -0.00365696  0.00048274
 -0.00258029] 22050


 24%|███████████████████▎                                                              | 20/85 [01:19<05:03,  4.66s/it]

[ 0.          0.          0.         ... -0.15257472 -0.14495775
 -0.1533123 ] 22050


 25%|████████████████████▎                                                             | 21/85 [01:23<04:40,  4.38s/it]

[ 0.          0.          0.         ... -0.11059644 -0.1085563
 -0.12142587] 22050


 26%|█████████████████████▏                                                            | 22/85 [01:26<04:10,  3.98s/it]

[ 0.          0.          0.         ... -0.02616313 -0.02832824
 -0.03311377] 22050


 27%|██████████████████████▏                                                           | 23/85 [01:29<03:51,  3.74s/it]

[ 0.          0.          0.         ... -0.10821859 -0.10085784
 -0.10736299] 22050


 28%|███████████████████████▏                                                          | 24/85 [01:32<03:34,  3.52s/it]

[0.         0.         0.         ... 0.26945388 0.2562324  0.27221316] 22050


 29%|████████████████████████                                                          | 25/85 [01:34<03:09,  3.16s/it]

[ 0.          0.          0.         ... -0.05926341 -0.05534621
 -0.05793385] 22050


 31%|█████████████████████████                                                         | 26/85 [01:37<03:04,  3.13s/it]

[ 0.          0.          0.         ... -0.04694906 -0.05055835
 -0.06256957] 22050


 32%|██████████████████████████                                                        | 27/85 [01:42<03:33,  3.68s/it]

[0.         0.         0.         ... 0.17112456 0.16861391 0.18079142] 22050


 33%|███████████████████████████                                                       | 28/85 [01:46<03:32,  3.73s/it]

[0.         0.         0.         ... 0.09519187 0.0919826  0.10184121] 22050


 34%|███████████████████████████▉                                                      | 29/85 [01:50<03:28,  3.73s/it]

[0.         0.         0.         ... 0.20328416 0.19927321 0.21701668] 22050


 35%|████████████████████████████▉                                                     | 30/85 [01:53<03:18,  3.60s/it]

[0.         0.         0.         ... 0.1784105  0.17279524 0.18705997] 22050


 36%|█████████████████████████████▉                                                    | 31/85 [01:57<03:10,  3.53s/it]

[0.         0.         0.         ... 0.15806355 0.15504608 0.16754578] 22050


 38%|██████████████████████████████▊                                                   | 32/85 [02:00<03:08,  3.56s/it]

[0.         0.         0.         ... 0.02381264 0.02345375 0.02424698] 22050


 39%|███████████████████████████████▊                                                  | 33/85 [02:04<03:14,  3.75s/it]

[0.         0.         0.         ... 0.0633135  0.06167608 0.06543391] 22050


 40%|████████████████████████████████▊                                                 | 34/85 [02:09<03:24,  4.01s/it]

[0.         0.         0.         ... 0.06957164 0.06568859 0.06777759] 22050


 41%|█████████████████████████████████▊                                                | 35/85 [02:13<03:19,  4.00s/it]

[0.         0.         0.         ... 0.5169264  0.49420917 0.52765614] 22050


 42%|██████████████████████████████████▋                                               | 36/85 [02:17<03:20,  4.10s/it]

[ 0.          0.          0.         ... -0.6361075  -0.61864734
 -0.67175263] 22050


 44%|███████████████████████████████████▋                                              | 37/85 [02:21<03:13,  4.04s/it]

[0.         0.         0.         ... 0.45760438 0.44249195 0.47693253] 22050


 45%|████████████████████████████████████▋                                             | 38/85 [02:26<03:15,  4.17s/it]

[ 0.          0.          0.         ... -0.07948826 -0.07436877
 -0.08173631] 22050


 46%|█████████████████████████████████████▌                                            | 39/85 [02:28<02:52,  3.75s/it]

[0.         0.         0.         ... 0.09586173 0.09115418 0.0959226 ] 22050


 47%|██████████████████████████████████████▌                                           | 40/85 [02:32<02:43,  3.63s/it]

[0.         0.         0.         ... 0.00059579 0.00040884 0.00018524] 22050


 48%|███████████████████████████████████████▌                                          | 41/85 [02:35<02:32,  3.46s/it]

[0.         0.         0.         ... 0.00061468 0.00073731 0.0010129 ] 22050


 49%|████████████████████████████████████████▌                                         | 42/85 [02:39<02:34,  3.58s/it]

[0.         0.         0.         ... 0.00469436 0.00457318 0.00489088] 22050


 51%|█████████████████████████████████████████▍                                        | 43/85 [02:44<02:48,  4.01s/it]

[ 0.          0.          0.         ... -0.03966789 -0.00456789
 -0.01253633] 22050


 52%|██████████████████████████████████████████▍                                       | 44/85 [02:47<02:31,  3.69s/it]

[ 0.          0.          0.         ... -0.01443889 -0.0036065
  0.00768639] 22050


 53%|███████████████████████████████████████████▍                                      | 45/85 [02:51<02:28,  3.71s/it]

[0.         0.         0.         ... 0.02293075 0.02522327 0.02491388] 22050


 54%|████████████████████████████████████████████▍                                     | 46/85 [02:55<02:38,  4.06s/it]

[ 0.          0.          0.         ... -0.01902727 -0.01628051
 -0.00893455] 22050


 55%|█████████████████████████████████████████████▎                                    | 47/85 [02:59<02:33,  4.04s/it]

[0.         0.         0.         ... 0.0115454  0.01240722 0.01308329] 22050


 56%|██████████████████████████████████████████████▎                                   | 48/85 [03:03<02:30,  4.06s/it]

[0.         0.         0.         ... 0.01450576 0.01357326 0.01446307] 22050


 58%|███████████████████████████████████████████████▎                                  | 49/85 [03:07<02:19,  3.87s/it]

[ 0.          0.          0.         ... -0.12028453 -0.11824434
 -0.13014063] 22050


 59%|████████████████████████████████████████████████▏                                 | 50/85 [03:10<02:08,  3.68s/it]

[0.         0.         0.         ... 0.0605499  0.05868293 0.06159526] 22050


 60%|█████████████████████████████████████████████████▏                                | 51/85 [03:14<02:03,  3.64s/it]

[0.         0.         0.         ... 0.01557782 0.01462343 0.01515078] 22050


 61%|██████████████████████████████████████████████████▏                               | 52/85 [03:17<01:57,  3.56s/it]

[ 0.          0.          0.         ... -0.02254345 -0.02208381
 -0.02349323] 22050


 62%|███████████████████████████████████████████████████▏                              | 53/85 [03:20<01:52,  3.50s/it]

[ 0.          0.          0.         ... -0.04213747 -0.04335009
 -0.05171286] 22050


 64%|████████████████████████████████████████████████████                              | 54/85 [03:23<01:43,  3.35s/it]

[ 0.          0.          0.         ... -0.00891681 -0.00817552
 -0.00768843] 22050


 65%|█████████████████████████████████████████████████████                             | 55/85 [03:27<01:41,  3.37s/it]

[0.         0.         0.         ... 0.02309799 0.02317885 0.02198694] 22050


 66%|██████████████████████████████████████████████████████                            | 56/85 [03:30<01:38,  3.40s/it]

[0.         0.         0.         ... 0.0338887  0.03054287 0.0315167 ] 22050


 67%|██████████████████████████████████████████████████████▉                           | 57/85 [03:34<01:35,  3.40s/it]

[0.         0.         0.         ... 0.00358016 0.0029045  0.00199023] 22050


 68%|███████████████████████████████████████████████████████▉                          | 58/85 [03:37<01:29,  3.30s/it]

[0.         0.         0.         ... 0.04359322 0.04235546 0.04606871] 22050


 69%|████████████████████████████████████████████████████████▉                         | 59/85 [03:41<01:36,  3.69s/it]

[0.         0.         0.         ... 0.07358634 0.06766799 0.07189249] 22050


 71%|█████████████████████████████████████████████████████████▉                        | 60/85 [03:46<01:41,  4.06s/it]

[ 0.          0.          0.         ... -0.06227456 -0.05999418
 -0.06597839] 22050


 72%|██████████████████████████████████████████████████████████▊                       | 61/85 [03:49<01:30,  3.77s/it]

[0.         0.         0.         ... 0.05142609 0.04925839 0.05164963] 22050


 73%|███████████████████████████████████████████████████████████▊                      | 62/85 [03:53<01:28,  3.84s/it]

[ 0.          0.          0.         ... -0.00450196 -0.00267744
 -0.00234501] 22050


 74%|████████████████████████████████████████████████████████████▊                     | 63/85 [03:57<01:21,  3.72s/it]

[ 0.          0.          0.         ... -0.02519566 -0.02452996
 -0.02345673] 22050


 75%|█████████████████████████████████████████████████████████████▋                    | 64/85 [04:01<01:20,  3.84s/it]

[0.         0.         0.         ... 0.08202307 0.08476666 0.09766038] 22050


 76%|██████████████████████████████████████████████████████████████▋                   | 65/85 [04:05<01:19,  3.97s/it]

[ 0.          0.          0.         ... -0.03965227 -0.04023258
 -0.04159994] 22050


 78%|███████████████████████████████████████████████████████████████▋                  | 66/85 [04:09<01:11,  3.78s/it]

[0.         0.         0.         ... 0.26817232 0.25902474 0.280427  ] 22050


 79%|████████████████████████████████████████████████████████████████▋                 | 67/85 [04:12<01:08,  3.82s/it]

[0.         0.         0.         ... 0.00342826 0.00317979 0.00364171] 22050


 80%|█████████████████████████████████████████████████████████████████▌                | 68/85 [04:16<01:01,  3.61s/it]

[0.         0.         0.         ... 0.07517342 0.07454691 0.07867888] 22050


 81%|██████████████████████████████████████████████████████████████████▌               | 69/85 [04:19<00:56,  3.51s/it]

[-0.07247163 -0.10745685 -0.09690773 ...  0.05467346  0.05316706
  0.05753393] 22050


 82%|███████████████████████████████████████████████████████████████████▌              | 70/85 [04:22<00:50,  3.37s/it]

[-0.05803953 -0.08320587 -0.07533526 ...  0.03917618  0.0369745
  0.04105215] 22050


 84%|████████████████████████████████████████████████████████████████████▍             | 71/85 [04:25<00:47,  3.39s/it]

[ 0.17166029  0.250432    0.21842906 ... -0.03571897 -0.03179305
 -0.03728459] 22050


 85%|█████████████████████████████████████████████████████████████████████▍            | 72/85 [04:29<00:44,  3.45s/it]

[0.         0.         0.         ... 0.3051465  0.29893237 0.3225977 ] 22050


 86%|██████████████████████████████████████████████████████████████████████▍           | 73/85 [04:33<00:43,  3.59s/it]

[0.         0.         0.         ... 0.7375129  0.72093195 0.78232914] 22050


 87%|███████████████████████████████████████████████████████████████████████▍          | 74/85 [04:37<00:40,  3.71s/it]

[ 0.          0.          0.         ... -0.00942516 -0.00825206
 -0.00559559] 22050


 88%|████████████████████████████████████████████████████████████████████████▎         | 75/85 [04:41<00:37,  3.73s/it]

[0.         0.         0.         ... 0.15102854 0.14400037 0.16173281] 22050


 89%|█████████████████████████████████████████████████████████████████████████▎        | 76/85 [04:44<00:31,  3.50s/it]

[ 0.          0.          0.         ... -0.06790091 -0.10178107
 -0.13769501] 22050


 91%|██████████████████████████████████████████████████████████████████████████▎       | 77/85 [04:47<00:27,  3.47s/it]

[0.         0.         0.         ... 0.02256879 0.02788899 0.03947941] 22050


 92%|███████████████████████████████████████████████████████████████████████████▏      | 78/85 [04:50<00:23,  3.40s/it]

[ 0.          0.          0.         ... -0.45220456 -0.43463495
 -0.45182434] 22050


 93%|████████████████████████████████████████████████████████████████████████████▏     | 79/85 [04:53<00:19,  3.32s/it]

[ 0.          0.          0.         ... -0.39158678 -0.38113743
 -0.41354823] 22050


 94%|█████████████████████████████████████████████████████████████████████████████▏    | 80/85 [04:58<00:18,  3.65s/it]

[0.         0.         0.         ... 0.06476758 0.05989117 0.0667561 ] 22050


 95%|██████████████████████████████████████████████████████████████████████████████▏   | 81/85 [05:01<00:14,  3.62s/it]

[0.        0.        0.        ... 1.0092846 0.9777773 1.0537751] 22050


 96%|███████████████████████████████████████████████████████████████████████████████   | 82/85 [05:06<00:11,  3.95s/it]

[0.         0.         0.         ... 0.02226742 0.02208254 0.02119073] 22050


 98%|████████████████████████████████████████████████████████████████████████████████  | 83/85 [05:10<00:07,  3.89s/it]

[0.         0.         0.         ... 0.02370285 0.02627874 0.028067  ] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████ | 84/85 [05:14<00:03,  3.94s/it]

[ 0.          0.          0.         ... -0.22099693 -0.21257466
 -0.23776534] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 85/85 [05:18<00:00,  3.95s/it]

[ 0.          0.          0.         ... -0.05103435 -0.05238643
 -0.05545169] 22050


done loading test mfcc


In [8]:
train_data['fname'] = train['fname']
train_data['label'] = train['label']

test_data['fname'] = audio_test_files
test_data['label'] = np.zeros((len(audio_test_files)))

In [9]:
#print(train_data)
#print(test_data)

In [10]:
X = train_data.drop(['label', 'fname'], axis=1)
feature_names = list(X.columns)
X = X.values
labels = np.sort(np.unique(train_data.label.values))
num_class = len(labels)
c2i = {}
i2c = {}
for i, c in enumerate(labels):
    c2i[c] = i
    i2c[i] = c
y = np.array([c2i[x] for x in train_data.label.values])

#print(X)
#y는 train 데이터들이 라벨링한 것
print(y)

[0 0 1 2 3 3 3 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 5 5 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 5 5
 3 3 3 3 3 3 3 3 0 3 3 3 3 3 1 1 6 6 6 6 6 6 6 6 6 1 3 3 3 3 3 3 1 1 1 3 0
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 6 6 6 6 6 6 6 6 6 6 6 6 1 0 0 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 6 6 6 3 3
 3 3 3 3 3 3 3 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3]


In [11]:
X_test = test_data.drop(['label', 'fname'], axis=1)
X_test = X_test.values

In [12]:
print(X.shape)
print(X_test.shape)
#test의 라벨링은 어디서?

(299, 210)
(85, 210)


In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)
#이놈이 뭘까

In [14]:
#pca = PCA(n_components=65).fit(X_scaled)
#65땜에 오류뜸
pca = PCA(n_components=65).fit(X_scaled)
#이 값 고쳐야
X_pca = pca.transform(X_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(sum(pca.explained_variance_ratio_)) 

0.9667856951166022


In [15]:
# Fit an SVM model
X_train, X_val, y_train, y_val = train_test_split(X_pca, y, test_size = 0.2, random_state = 42, shuffle = True)
#test_size와 random_state 확인

#train 관련
#print(X_train)
#print(y_train) - train 라벨링

#train 내에서 쪼개는 것으로 추측됨 test 0.2가 100개중 20개로 맞네
#test를 따로 만드는게 아니라 train 내에서 일부를 test에 사용하여 정확도 측정
print(X_val)
print(y_val)

clf = SVC(kernel = 'rbf', probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

[[-6.0574237   5.53631483 -1.14552842 ... -0.19398018  0.50498533
  -0.38345381]
 [-2.68798566  1.18116591 -3.64737395 ... -0.05154531 -0.107796
   0.25035027]
 [ 3.6630428   6.59873133  3.17546579 ... -0.26343876 -0.23017746
  -0.42441702]
 ...
 [-1.23513999  3.80868895 -1.28549982 ... -0.53509076  0.20488332
   0.36786328]
 [-3.86487187 -7.87938391 -2.05387047 ... -0.67389615  0.05712335
  -0.3960214 ]
 [ 0.48513732 -8.87678328 -4.73662835 ...  0.63959184  0.29561464
  -0.31895134]]
[3 3 3 3 3 3 6 3 3 3 6 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 6 3 3 3 3 3 3 3 3
 3 3 6 3 0 3 3 3 3 6 3 0 3 3 3 3 3 3 5 3 3 6 3]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9166666666666666


In [16]:
C_grid = [0.001, 0.01, 0.1, 1, 10]
gamma_grid = [0.001, 0.01, 0.1, 1, 10]
param_grid = {'C': C_grid, 'gamma' : gamma_grid}

#grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
#이부분 수정해야
#데이터 갯수 확 느니까 바로먹음
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
grid.fit(X_train, y_train)

# Find the best model
print(grid.best_score_)

print(grid.best_params_)

print(grid.best_estimator_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.9037656903765691
{'C': 10, 'gamma': 0.001}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [17]:
clf = SVC(kernel = 'rbf', C = 10, gamma = 0.001, probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

0.95


In [18]:
# Fit the entire training sets
clf.fit(X_pca, y)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)