In [1]:
#csv파일이랑 audio폴더 test 양만큼 개줄여서 디버그하며 할 것

import os
import librosa
import librosa.display
import IPython.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import pandas as pd
import csv

import scipy
from scipy.stats import skew
from tqdm import tqdm, tqdm_pandas

tqdm.pandas()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.svm import SVC

In [2]:
filename = np.array(pd.read_csv('data/SC_file_name.csv'))
answer = np.array(pd.read_csv('data/SC_answer.csv'))

audio_train_files = os.listdir('./audio_train/')
audio_test_files = os.listdir('./audio_test/')
train=pd.read_csv('./file_name.csv')

In [3]:
#print(audio_train_files)
#print(audio_test_files)

In [4]:
def get_mfcc(name, path):
    data, _ = librosa.core.load(path+name) #엑셀에 .wav까지 붙여 저장해야됨 안그러면 path+name+'.wav' 이렇게해야
    print(data,_)
    #data, _ = librosa.load(path)
    try:
        #ft1 = librosa.feature.mfcc(data, sr = SAMPLE_RATE, n_mfcc=30)
        ft1 = librosa.feature.mfcc(data, n_mfcc=30) #이게핵심 Sample_rate를 어떻게 조절하느냐
        ft2 = librosa.feature.zero_crossing_rate(data)[0] # n_mfcc 값을 어떻게 조절하느냐에 따라 Feature개수가 달리 뽑힘
        ft3 = librosa.feature.spectral_rolloff(data)[0]
        ft4 = librosa.feature.spectral_centroid(data)[0]
        ft5 = librosa.feature.spectral_contrast(data)[0]
        ft6 = librosa.feature.spectral_bandwidth(data)[0]
        ft1_trunc = np.hstack((np.mean(ft1, axis=1), np.std(ft1, axis=1), skew(ft1, axis = 1), np.max(ft1, axis = 1), np.median(ft1, axis = 1), np.min(ft1, axis = 1)))
        ft2_trunc = np.hstack((np.mean(ft2), np.std(ft2), skew(ft2), np.max(ft2), np.median(ft2), np.min(ft2)))
        ft3_trunc = np.hstack((np.mean(ft3), np.std(ft3), skew(ft3), np.max(ft3), np.median(ft3), np.min(ft3)))
        ft4_trunc = np.hstack((np.mean(ft4), np.std(ft4), skew(ft4), np.max(ft4), np.median(ft4), np.min(ft4)))
        ft5_trunc = np.hstack((np.mean(ft5), np.std(ft5), skew(ft5), np.max(ft5), np.median(ft5), np.min(ft5)))
        ft6_trunc = np.hstack((np.mean(ft6), np.std(ft6), skew(ft6), np.max(ft6), np.median(ft6), np.max(ft6)))
        return pd.Series(np.hstack((ft1_trunc, ft2_trunc, ft3_trunc, ft4_trunc, ft5_trunc, ft6_trunc)))
    except:
        print('bad file')
        return pd.Series([0]*210)

In [5]:
train_data = pd.DataFrame()
train_data['fname'] = train['fname']
test_data=pd.DataFrame()
test_data['fname']=audio_test_files

In [6]:
#print(train_data)
print(test_data)


                        fname
0  130_1p3_Al_mc_AKGC417L.wav
1  130_1p3_Ar_mc_AKGC417L.wav
2  130_1p3_Ll_mc_AKGC417L.wav
3  130_1p3_Lr_mc_AKGC417L.wav
4  130_1p3_Pl_mc_AKGC417L.wav
5  130_1p3_Pr_mc_AKGC417L.wav
6  130_1p3_Tc_mc_AKGC417L.wav
7  130_1p4_Al_mc_AKGC417L.wav


In [7]:
train_data=train_data['fname'].progress_apply(get_mfcc,path='./audio_train/')
print('done loading train mfcc')
test_data = test_data['fname'].progress_apply(get_mfcc, path='./audio_test/')
print('done loading test mfcc')



  0%|                                                                                           | 0/99 [00:00<?, ?it/s]

[0.06973912 0.10266001 0.09116188 ... 0.08305359 0.08018959 0.08612607] 22050


  2%|█▋                                                                                 | 2/99 [00:06<05:03,  3.13s/it]

[-0.02710845 -0.03993477 -0.03530764 ... -0.04230448 -0.0414599
 -0.04527015] 22050


  3%|██▌                                                                                | 3/99 [00:08<04:36,  2.88s/it]

[ 0.00283427  0.00423394  0.0036414  ... -0.01369482 -0.01395124
 -0.01601286] 22050


  4%|███▎                                                                               | 4/99 [00:10<03:55,  2.48s/it]

[-0.2545665  -0.37054616 -0.3232944  ... -0.05147256 -0.04832996
 -0.0513258 ] 22050


  5%|████▏                                                                              | 5/99 [00:11<03:25,  2.19s/it]

[ 3.1871754e-05  6.1540527e-06 -3.7155998e-05 ... -1.4125325e-02
 -8.7606525e-03  0.0000000e+00] 22050


  6%|█████                                                                              | 6/99 [00:12<02:56,  1.90s/it]

[ 0.00079253  0.00089992  0.00091092 ... -0.0049351  -0.00259066
  0.        ] 22050


  7%|█████▊                                                                             | 7/99 [00:14<02:46,  1.80s/it]

[ 3.0208554e-05  3.0756044e-05  2.5381032e-05 ... -1.8259089e-02
 -1.1751885e-02 -5.7575861e-03] 22050


  8%|██████▋                                                                            | 8/99 [00:15<02:20,  1.54s/it]

[-0.00064508 -0.00077814 -0.0008623  ... -0.01482992 -0.00782498
  0.        ] 22050


  9%|███████▌                                                                           | 9/99 [00:16<01:58,  1.32s/it]

[ 0.00110417  0.00130484  0.00140896 ... -0.01235658 -0.00798214
 -0.00392708] 22050


 10%|████████▎                                                                         | 10/99 [00:18<02:13,  1.50s/it]

[ 4.3292630e-07  3.4875336e-06  7.9502988e-06 ... -4.9829770e-02
 -2.8054921e-02  0.0000000e+00] 22050


 11%|█████████                                                                         | 11/99 [00:19<02:06,  1.44s/it]

[0.00072087 0.00177281 0.00336674 ... 0.03278232 0.03167795 0.0341762 ] 22050


 12%|█████████▉                                                                        | 12/99 [00:21<02:11,  1.51s/it]

[-0.00511142 -0.00661265 -0.00532051 ...  0.05818591  0.05825811
  0.06405238] 22050


 13%|██████████▊                                                                       | 13/99 [00:22<02:04,  1.45s/it]

[ 0.13884057  0.20461525  0.18165357 ... -0.07205642 -0.07238604
 -0.08182055] 22050


 14%|███████████▌                                                                      | 14/99 [00:23<02:03,  1.45s/it]

[ 0.          0.          0.         ... -0.03222465 -0.02863552
 -0.02814007] 22050


 15%|████████████▍                                                                     | 15/99 [00:25<02:03,  1.47s/it]

[0.         0.         0.         ... 0.81409144 0.7837968  0.8404915 ] 22050


 16%|█████████████▎                                                                    | 16/99 [00:26<02:04,  1.50s/it]

[0.         0.         0.         ... 0.2893713  0.28139624 0.3021213 ] 22050


 17%|██████████████                                                                    | 17/99 [00:28<02:02,  1.50s/it]

[ 0.          0.          0.         ... -0.15555128 -0.14919281
 -0.1552921 ] 22050


 18%|██████████████▉                                                                   | 18/99 [00:30<02:12,  1.64s/it]

[0.         0.         0.         ... 0.02468135 0.02214165 0.01943384] 22050


 19%|███████████████▋                                                                  | 19/99 [00:31<02:07,  1.59s/it]

[ 0.          0.          0.         ... -0.34570888 -0.34052533
 -0.37189066] 22050


 20%|████████████████▌                                                                 | 20/99 [00:33<02:12,  1.68s/it]

[ 0.          0.          0.         ... -0.36525172 -0.35147998
 -0.3764349 ] 22050


 21%|█████████████████▍                                                                | 21/99 [00:35<02:07,  1.64s/it]

[0.         0.         0.         ... 0.29563662 0.29204592 0.32384074] 22050


 22%|██████████████████▏                                                               | 22/99 [00:36<02:07,  1.66s/it]

[ 0.          0.          0.         ... -0.87329555 -0.8426997
 -0.904122  ] 22050


 23%|███████████████████                                                               | 23/99 [00:38<02:07,  1.68s/it]

[0.         0.         0.         ... 0.08035016 0.07610521 0.08158155] 22050


 24%|███████████████████▉                                                              | 24/99 [00:40<02:00,  1.61s/it]

[0.         0.         0.         ... 0.07361161 0.07532007 0.08183191] 22050


 25%|████████████████████▋                                                             | 25/99 [00:42<02:07,  1.72s/it]

[ 0.          0.          0.         ... -0.05342972 -0.0532412
 -0.06048   ] 22050


 26%|█████████████████████▌                                                            | 26/99 [00:43<02:03,  1.70s/it]

[0.         0.         0.         ... 0.48654523 0.47395992 0.5123876 ] 22050


 27%|██████████████████████▎                                                           | 27/99 [00:45<02:03,  1.71s/it]

[0.         0.         0.         ... 0.01937228 0.01565968 0.01233602] 22050


 28%|███████████████████████▏                                                          | 28/99 [00:47<02:06,  1.78s/it]

[0.         0.         0.         ... 0.21377535 0.19589575 0.19898888] 22050


 29%|████████████████████████                                                          | 29/99 [00:49<02:00,  1.73s/it]

[ 0.          0.          0.         ... -0.03692322 -0.04029846
 -0.03779646] 22050


 30%|████████████████████████▊                                                         | 30/99 [00:50<01:55,  1.67s/it]

[ 0.          0.          0.         ... -0.00111335  0.00120612
 -0.00136599] 22050


 31%|█████████████████████████▋                                                        | 31/99 [00:52<01:51,  1.64s/it]

[ 0.          0.          0.         ... -0.27843747 -0.2646894
 -0.28205138] 22050


 32%|██████████████████████████▌                                                       | 32/99 [00:53<01:48,  1.62s/it]

[ 0.          0.          0.         ... -0.26306844 -0.2522001
 -0.26922488] 22050


 33%|███████████████████████████▎                                                      | 33/99 [00:55<01:47,  1.63s/it]

[0.         0.         0.         ... 0.1735332  0.17125647 0.19119985] 22050


 34%|████████████████████████████▏                                                     | 34/99 [00:57<01:47,  1.65s/it]

[ 0.          0.          0.         ... -0.2167718  -0.2080332
 -0.22265384] 22050


 35%|████████████████████████████▉                                                     | 35/99 [00:58<01:43,  1.61s/it]

[ 0.          0.          0.         ... -0.05900886 -0.06246108
 -0.06871106] 22050


 36%|█████████████████████████████▊                                                    | 36/99 [01:00<01:42,  1.63s/it]

[0.         0.         0.         ... 0.7010785  0.68610245 0.7446819 ] 22050


 37%|██████████████████████████████▋                                                   | 37/99 [01:01<01:41,  1.64s/it]

[ 0.          0.          0.         ... -0.1005215  -0.09558512
 -0.09833872] 22050


 38%|███████████████████████████████▍                                                  | 38/99 [01:03<01:40,  1.65s/it]

[ 0.          0.          0.         ... -0.09970824 -0.10170659
 -0.11256789] 22050


 39%|████████████████████████████████▎                                                 | 39/99 [01:05<01:39,  1.66s/it]

[ 0.          0.          0.         ... -0.09393648 -0.0905112
 -0.09887574] 22050


 40%|█████████████████████████████████▏                                                | 40/99 [01:07<01:43,  1.75s/it]

[ 0.          0.          0.         ... -0.10736632 -0.10226438
 -0.10872729] 22050


 41%|█████████████████████████████████▉                                                | 41/99 [01:08<01:36,  1.66s/it]

[ 0.          0.          0.         ... -0.3698437  -0.36839765
 -0.4094729 ] 22050


 42%|██████████████████████████████████▊                                               | 42/99 [01:10<01:29,  1.57s/it]

[-0.00949201 -0.01515351 -0.01494985 ...  0.03122446  0.03000467
  0.03189378] 22050


 43%|███████████████████████████████████▌                                              | 43/99 [01:11<01:29,  1.61s/it]

[-1.7585522e-06 -2.2429733e-06 -1.9274846e-06 ... -1.1987473e-02
 -7.4312286e-03  0.0000000e+00] 22050


 44%|████████████████████████████████████▍                                             | 44/99 [01:12<01:20,  1.46s/it]

[-3.1364743e-05 -3.4258581e-05 -3.3931665e-05 ...  5.3538714e-04
  3.7836187e-04  0.0000000e+00] 22050


 45%|█████████████████████████████████████▎                                            | 45/99 [01:14<01:14,  1.37s/it]

[-2.9586021e-05 -3.3629472e-05 -3.4923316e-05 ... -2.4650006e-03
 -1.3031738e-03  0.0000000e+00] 22050


 46%|██████████████████████████████████████                                            | 46/99 [01:14<01:03,  1.20s/it]

[3.0384650e-05 3.1305051e-05 2.8012693e-05 ... 3.9614424e-02 2.4514157e-02
 0.0000000e+00] 22050


 47%|██████████████████████████████████████▉                                           | 47/99 [01:15<00:56,  1.09s/it]

[-0.00015414 -0.00019182 -0.00021949 ...  0.02211454  0.01247506
  0.        ] 22050


 48%|███████████████████████████████████████▊                                          | 48/99 [01:16<00:58,  1.15s/it]

[2.9788309e-05 3.2301657e-05 3.1995405e-05 ... 1.5126610e-03 9.7192550e-04
 4.7570144e-04] 22050


 49%|████████████████████████████████████████▌                                         | 49/99 [01:18<01:00,  1.22s/it]

[-0.30551556 -0.337594   -0.35426965 ...  0.04488467  0.02582479
  0.        ] 22050


 51%|█████████████████████████████████████████▍                                        | 50/99 [01:21<01:27,  1.79s/it]

[-0.30030748 -0.3313869  -0.3471481  ... -0.10257331 -0.06606323
 -0.03239066] 22050


 52%|██████████████████████████████████████████▏                                       | 51/99 [01:22<01:21,  1.70s/it]

[-0.5566892  -0.61342674 -0.6413218  ... -0.07702224 -0.0493612
 -0.02408693] 22050


 53%|███████████████████████████████████████████                                       | 52/99 [01:24<01:16,  1.62s/it]

[-0.87746686 -0.9691256  -1.0164407  ... -0.2245433  -0.14452285
 -0.07082193] 22050


 54%|███████████████████████████████████████████▉                                      | 53/99 [01:25<01:12,  1.57s/it]

[-0.14500825 -0.16018207 -0.16798463 ...  0.11473081  0.06627245
  0.        ] 22050


 55%|████████████████████████████████████████████▋                                     | 54/99 [01:29<01:37,  2.16s/it]

[-0.00199708 -0.00319508 -0.00331803 ... -0.00064225 -0.00038474
  0.        ] 22050


 56%|█████████████████████████████████████████████▌                                    | 55/99 [01:30<01:23,  1.91s/it]

[-0.00066345 -0.00110385 -0.00104151 ...  0.00647592  0.00655071
  0.        ] 22050


 57%|██████████████████████████████████████████████▍                                   | 56/99 [01:32<01:14,  1.73s/it]

[-0.2739319  -0.3025994  -0.31744638 ...  0.01044763  0.00608007
  0.        ] 22050


 58%|███████████████████████████████████████████████▏                                  | 57/99 [01:35<01:29,  2.13s/it]

[-0.06291798 -0.07026124 -0.07465484 ... -0.14951584 -0.09621288
 -0.04716552] 22050


 59%|████████████████████████████████████████████████                                  | 58/99 [01:36<01:19,  1.94s/it]

[-1.7918481e-06 -5.5685846e-06 -9.9844920e-06 ...  2.7333383e-02
  1.7636651e-02  8.6638099e-03] 22050


 60%|████████████████████████████████████████████████▊                                 | 59/99 [01:37<01:10,  1.75s/it]

[ 8.5524260e-07 -2.3861974e-06 -7.3340552e-06 ... -1.3542055e-01
 -8.7212533e-02 -4.2756353e-02] 22050


 61%|█████████████████████████████████████████████████▋                                | 60/99 [01:39<01:03,  1.64s/it]

[-0.00027686 -0.00032779 -0.00035314 ... -0.03754111 -0.02402511
 -0.01169831] 22050


 62%|██████████████████████████████████████████████████▌                               | 61/99 [01:40<00:59,  1.57s/it]

[-1.7565626e-06 -1.2353955e-06  5.4582960e-09 ... -2.6573552e-02
 -1.6467988e-02  0.0000000e+00] 22050


 63%|███████████████████████████████████████████████████▎                              | 62/99 [01:41<00:49,  1.34s/it]

[0.000215   0.00023683 0.00023057 ... 0.0034874  0.00196025 0.        ] 22050


 64%|████████████████████████████████████████████████████▏                             | 63/99 [01:42<00:42,  1.19s/it]

[-3.0497395e-07  1.2244502e-06  3.1903026e-06 ... -9.8866746e-03
 -5.5146376e-03  0.0000000e+00] 22050


 65%|█████████████████████████████████████████████████████                             | 64/99 [01:43<00:39,  1.12s/it]

[6.2300285e-05 7.5929711e-05 8.4309846e-05 ... 9.5062396e-03 5.8767227e-03
 0.0000000e+00] 22050


 66%|█████████████████████████████████████████████████████▊                            | 65/99 [01:43<00:33,  1.01it/s]

[2.0636191e-06 5.3742210e-06 7.9173615e-06 ... 8.8258702e-03 5.2438602e-03
 0.0000000e+00] 22050


 67%|██████████████████████████████████████████████████████▋                           | 66/99 [01:44<00:31,  1.04it/s]

[-1.5476845e-06 -1.4929913e-06  7.7756016e-07 ...  1.0041645e-03
  6.2980881e-04  0.0000000e+00] 22050


 68%|███████████████████████████████████████████████████████▍                          | 67/99 [01:45<00:31,  1.00it/s]

[ 0.          0.          0.         ... -0.12468348 -0.1273278
 -0.14731203] 22050


 69%|████████████████████████████████████████████████████████▎                         | 68/99 [01:47<00:33,  1.09s/it]

[ 0.          0.          0.         ... -0.02251784 -0.02150127
 -0.02269199] 22050


 70%|█████████████████████████████████████████████████████████▏                        | 69/99 [01:48<00:34,  1.16s/it]

[ 0.          0.          0.         ... -0.01567137 -0.01457954
 -0.0151326 ] 22050


 71%|█████████████████████████████████████████████████████████▉                        | 70/99 [01:49<00:35,  1.21s/it]

[0.         0.         0.         ... 0.06823757 0.06161449 0.0576618 ] 22050


 72%|██████████████████████████████████████████████████████████▊                       | 71/99 [01:51<00:34,  1.24s/it]

[ 0.          0.          0.         ... -0.0593754  -0.06029727
 -0.06811669] 22050


 73%|███████████████████████████████████████████████████████████▋                      | 72/99 [01:52<00:34,  1.27s/it]

[ 0.15286843  0.22476168  0.19892806 ... -0.01032892 -0.01059519
 -0.01229354] 22050


 74%|████████████████████████████████████████████████████████████▍                     | 73/99 [01:53<00:33,  1.28s/it]

[0.01386719 0.02011131 0.01776993 ... 0.00524451 0.00579907 0.        ] 22050


 75%|█████████████████████████████████████████████████████████████▎                    | 74/99 [01:55<00:32,  1.30s/it]

[-0.00679656 -0.01003796 -0.00873371 ... -0.02517475 -0.03054456
  0.        ] 22050


 76%|██████████████████████████████████████████████████████████████                    | 75/99 [01:56<00:31,  1.30s/it]

[ 0.00579983  0.00852321  0.00752403 ... -0.00082801 -0.00068914
 -0.00070964] 22050


 77%|██████████████████████████████████████████████████████████████▉                   | 76/99 [01:57<00:30,  1.31s/it]

[-0.00053421 -0.00082033 -0.00076593 ... -0.00522986 -0.00525398
 -0.00585139] 22050


 78%|███████████████████████████████████████████████████████████████▊                  | 77/99 [01:59<00:28,  1.31s/it]

[-2.8764509e-05 -3.0061437e-05 -2.9183469e-05 ... -1.0795601e-03
 -5.5044401e-04  0.0000000e+00] 22050


 79%|████████████████████████████████████████████████████████████████▌                 | 78/99 [01:59<00:24,  1.16s/it]

[-7.8413684e-08  9.5552173e-07  1.9807621e-06 ... -3.6296784e-03
 -2.0876050e-03  0.0000000e+00] 22050


 80%|█████████████████████████████████████████████████████████████████▍                | 79/99 [02:00<00:21,  1.06s/it]

[1.8421345e-06 3.9703418e-06 4.0728492e-06 ... 1.1935446e-03 6.8373588e-04
 0.0000000e+00] 22050


 81%|██████████████████████████████████████████████████████████████████▎               | 80/99 [02:01<00:17,  1.08it/s]

[-2.2084580e-06 -5.9585232e-06 -8.7529661e-06 ... -3.4101740e-02
 -2.1929748e-02 -1.0731890e-02] 22050


 82%|███████████████████████████████████████████████████████████████████               | 81/99 [02:02<00:16,  1.07it/s]

[-5.8840362e-07  2.2181875e-06  5.4235775e-06 ...  3.1400897e-02
  1.6541665e-02  0.0000000e+00] 22050


 83%|███████████████████████████████████████████████████████████████████▉              | 82/99 [02:02<00:14,  1.21it/s]

[ 5.9769508e-07  8.8926954e-06  2.1092692e-05 ... -1.6348783e-02
 -8.8511044e-03  0.0000000e+00] 22050


 84%|████████████████████████████████████████████████████████████████████▋             | 83/99 [02:03<00:11,  1.34it/s]

[ 0.00772112  0.01154974  0.01025985 ... -0.00331298 -0.00319685
 -0.0037348 ] 22050


 85%|█████████████████████████████████████████████████████████████████████▌            | 84/99 [02:04<00:13,  1.11it/s]

[0.28596535 0.3158219  0.33115914 ... 0.08994886 0.05179574 0.        ] 22050


 86%|██████████████████████████████████████████████████████████████████████▍           | 85/99 [02:07<00:21,  1.55s/it]

[-0.27563092 -0.30399603 -0.31818    ...  0.00215952  0.00126481
  0.        ] 22050


 87%|███████████████████████████████████████████████████████████████████████▏          | 86/99 [02:10<00:26,  2.02s/it]

[0.03946353 0.04340422 0.04541007 ... 0.4538223  0.29210246 0.14312147] 22050


 88%|████████████████████████████████████████████████████████████████████████          | 87/99 [02:15<00:33,  2.77s/it]

[-0.3726952  -0.41175988 -0.43205068 ... -0.15957749 -0.10276388
 -0.05036703] 22050


 89%|████████████████████████████████████████████████████████████████████████▉         | 88/99 [02:18<00:32,  2.92s/it]

[-0.2810858  -0.31157294 -0.32829928 ... -0.1266794  -0.08168591
 -0.04014152] 22050


 90%|█████████████████████████████████████████████████████████████████████████▋        | 89/99 [02:21<00:29,  2.92s/it]

[-0.07494406 -0.10856454 -0.09363515 ...  0.01878147  0.01818044
  0.01986458] 22050


 91%|██████████████████████████████████████████████████████████████████████████▌       | 90/99 [02:23<00:22,  2.50s/it]

[ 0.03124345  0.04578807  0.04021889 ... -0.01389698 -0.01351108
 -0.01445538] 22050


 92%|███████████████████████████████████████████████████████████████████████████▎      | 91/99 [02:24<00:17,  2.24s/it]

[-0.02912769 -0.04266582 -0.03835926 ... -0.07225096 -0.07003564
 -0.07565343] 22050


 93%|████████████████████████████████████████████████████████████████████████████▏     | 92/99 [02:26<00:13,  1.98s/it]

[ 0.00182807  0.00246826  0.00192033 ... -0.00439787 -0.00413904
 -0.00436127] 22050


 94%|█████████████████████████████████████████████████████████████████████████████     | 93/99 [02:27<00:10,  1.80s/it]

[-0.06445651 -0.09444108 -0.08404209 ... -0.01689324 -0.01542289
 -0.01585781] 22050


 95%|█████████████████████████████████████████████████████████████████████████████▊    | 94/99 [02:28<00:08,  1.66s/it]

[0.06414742 0.09454045 0.08388222 ... 0.24822964 0.24023329 0.2587387 ] 22050


 96%|██████████████████████████████████████████████████████████████████████████████▋   | 95/99 [02:30<00:06,  1.57s/it]

[ 0.08259647  0.12127037  0.1070242  ... -0.02367939 -0.02266011
 -0.0243049 ] 22050


 97%|███████████████████████████████████████████████████████████████████████████████▌  | 96/99 [02:31<00:04,  1.50s/it]

[-0.0151329  -0.02294918 -0.0202172  ... -0.04157927 -0.04070212
 -0.04374132] 22050


 98%|████████████████████████████████████████████████████████████████████████████████▎ | 97/99 [02:33<00:03,  1.62s/it]

[-0.00485999 -0.00679087 -0.00545568 ...  0.01482467  0.0137242
  0.01388321] 22050


 99%|█████████████████████████████████████████████████████████████████████████████████▏| 98/99 [02:35<00:01,  1.72s/it]

[0.13323113 0.19474407 0.17157386 ... 0.08486681 0.08216646 0.08880045] 22050


100%|██████████████████████████████████████████████████████████████████████████████████| 99/99 [02:37<00:00,  1.84s/it]

[0.02923446 0.04403316 0.04038239 ... 0.07650845 0.07465485 0.08051185] 22050


done loading train mfcc


  0%|                                                                                            | 0/8 [00:00<?, ?it/s]

[ 0.          0.          0.         ... -0.03819335 -0.03791534
 -0.04188127] 22050


 25%|█████████████████████                                                               | 2/8 [00:02<00:06,  1.07s/it]

[ 0.          0.          0.         ... -0.06268332 -0.06022708
 -0.06461953] 22050


 38%|███████████████████████████████▌                                                    | 3/8 [00:03<00:05,  1.17s/it]

[ 0.          0.          0.         ... -0.28731927 -0.2788944
 -0.3043653 ] 22050


 50%|██████████████████████████████████████████                                          | 4/8 [00:05<00:05,  1.29s/it]

[ 0.          0.          0.         ... -0.12467527 -0.11601477
 -0.12351672] 22050


 62%|████████████████████████████████████████████████████▌                               | 5/8 [00:06<00:03,  1.33s/it]

[ 0.          0.          0.         ... -0.3117757  -0.30287907
 -0.32905123] 22050


 75%|███████████████████████████████████████████████████████████████                     | 6/8 [00:07<00:02,  1.36s/it]

[ 0.          0.          0.         ... -0.60128844 -0.5866989
 -0.6393383 ] 22050


 88%|█████████████████████████████████████████████████████████████████████████▌          | 7/8 [00:09<00:01,  1.38s/it]

[ 0.          0.          0.         ... -0.09460735 -0.09186393
 -0.10033422] 22050


100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:10<00:00,  1.40s/it]

[0.         0.         0.         ... 0.06824436 0.06823804 0.07497056] 22050


done loading test mfcc


In [8]:
train_data['fname'] = train['fname']
train_data['label'] = train['label']

test_data['fname'] = audio_test_files
test_data['label'] = np.zeros((len(audio_test_files)))

In [9]:
#print(train_data)
print(test_data)

            0           1          2          3          4          5  \
0 -374.568476  121.653345  68.564955  35.947216  30.422790  31.903702   
1 -397.516973   97.320405  71.506663  47.443845  33.989614  28.778871   
2 -309.153916  108.590946  49.665790  39.516736  30.495293  28.091219   
3 -270.489556  161.700804  49.739469  17.809513  13.739956  18.044573   
4 -266.609507  158.940668  69.044580  38.555959  28.130570  21.142545   
5 -286.585566  149.852568  74.347056  30.249630  16.780876  14.380454   
6 -243.604437  144.016071   9.083950  25.720157  23.012074  19.829217   
7 -333.424073  134.835047  62.990353  28.851085  28.611614  31.429581   

           6          7          8          9  ...          202       203  \
0  27.481430  19.513747  14.341624  13.400741  ...    18.338631  7.468611   
1  24.618514  18.687007  13.254794  10.825098  ...    18.039230  7.656408   
2  23.433613  16.137411  14.933775  15.932992  ...    20.245296  5.962564   
3  16.730022  12.005675  10.303434

In [21]:
X = train_data.drop(['label', 'fname'], axis=1)
feature_names = list(X.columns)
X = X.values
labels = np.sort(np.unique(train_data.label.values))
num_class = len(labels)
c2i = {}
i2c = {}
for i, c in enumerate(labels):
    c2i[c] = i
    i2c[i] = c
y = np.array([c2i[x] for x in train_data.label.values])

#print(X)
#y는 train 데이터들이 라벨링한 것
print(y)

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]


In [11]:
X_test = test_data.drop(['label', 'fname'], axis=1)
X_test = X_test.values

In [24]:
print(X.shape)
print(X_test.shape)
#test의 라벨링은 어디서?

(99, 210)
(8, 210)


In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)
#이놈이 뭘까

In [14]:
#pca = PCA(n_components=65).fit(X_scaled)
#65땜에 오류뜸
pca = PCA(n_components=65).fit(X_scaled)
#이 값 고쳐야
X_pca = pca.transform(X_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(sum(pca.explained_variance_ratio_)) 

0.9927819852312187


In [28]:
# Fit an SVM model
X_train, X_val, y_train, y_val = train_test_split(X_pca, y, test_size = 0.2, random_state = 42, shuffle = True)
#test_size와 random_state 확인

#train 관련
#print(X_train)
#print(y_train) - train 라벨링

#train 내에서 쪼개는 것으로 추측됨 test 0.2가 100개중 20개로 맞네
#test를 따로 만드는게 아니라 train 내에서 일부를 test에 사용하여 정확도 측정
print(X_val)
print(y_val)

clf = SVC(kernel = 'rbf', probability=True)

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

[[ 4.88100404 -3.43397136 -3.29845388 ... -0.61609378  0.23458665
   0.97816446]
 [ 0.26160425  5.18237066 -2.43019333 ... -0.24010789 -0.35883319
  -0.09569657]
 [ 0.91343711 -2.02287154  2.09438045 ... -0.59792007 -1.20865358
  -0.2661965 ]
 ...
 [-6.1306718  -4.3883038  -6.27430465 ...  0.18317393  0.20533995
   0.42573345]
 [ 2.40666755  3.78935566  9.21096189 ... -0.21731497  0.16284491
  -0.09165545]
 [ 1.16133406  8.34994398  7.72972024 ...  0.04968694  0.01360946
  -0.70441906]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.95


In [16]:
C_grid = [0.001, 0.01, 0.1, 1, 10]
gamma_grid = [0.001, 0.01, 0.1, 1, 10]
param_grid = {'C': C_grid, 'gamma' : gamma_grid}

#grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
#이부분 수정해야
#데이터 갯수 확 느니까 바로먹음
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, cv = 3, scoring = "accuracy")
grid.fit(X_train, y_train)

# Find the best model
print(grid.best_score_)

print(grid.best_params_)

print(grid.best_estimator_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.9746835443037974
{'C': 0.001, 'gamma': 0.001}
SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [17]:

clf.fit(X_train, y_train)

print(accuracy_score(clf.predict(X_val), y_val))

0.95


In [18]:
# Fit the entire training sets
clf.fit(X_pca, y)


SVC(C=4, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
'''
#나중에 위로 올릴 것
def convert_to_labels(preds, i2c, k=3):
    ans = []
    ids = []
    for p in preds:
        idx = np.argsort(p)[::-1]
        ids.append([i for i in idx[:k]])
        ans.append(' '.join([i2c[i] for i in idx[:k]]))

    return ans, ids

#test 폴더 submission 만들기 - 오류
submission = pd.read_csv('./sample_submission.csv')

str_preds, _ = convert_to_labels(clf.predict_proba(X_test_pca), i2c, k=3)

# Write to outputs
subm = pd.DataFrame()
subm['fname'] = audio_test_files
subm['label'] = str_preds
subm.to_csv('submission.csv', index=False)
'''

"\n#나중에 위로 올릴 것\ndef convert_to_labels(preds, i2c, k=3):\n    ans = []\n    ids = []\n    for p in preds:\n        idx = np.argsort(p)[::-1]\n        ids.append([i for i in idx[:k]])\n        ans.append(' '.join([i2c[i] for i in idx[:k]]))\n\n    return ans, ids\n\n#test 폴더 submission 만들기 - 오류\nsubmission = pd.read_csv('./sample_submission.csv')\n\nstr_preds, _ = convert_to_labels(clf.predict_proba(X_test_pca), i2c, k=3)\n\n# Write to outputs\nsubm = pd.DataFrame()\nsubm['fname'] = audio_test_files\nsubm['label'] = str_preds\nsubm.to_csv('submission.csv', index=False)\n"